import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import createManifold from 'manifold-3d';import {glbFromPreview} from '../public/src/mesh-glb-export.js';
const manifold=await createManifold();manifold.setup();const solid=manifold.Manifold.cube([40,60,35]),mesh=solid.getMesh(),positions=new Float32Array(mesh.triVerts.length*3);mesh.triVerts.forEach((v,i)=>positions.set(mesh.vertProperties.subarray(v*mesh.numProp,v*mesh.numProp+3),i*3));solid.delete();
const dir=await mkdtemp(join(tmpdir(),'orders-flow-')),server=createApp({accountsEnabled:true,accountDir:dir}),model={mesh:positions},glb=new Uint8Array(await glbFromPreview({...model,originalColors:model.colors}).arrayBuffer()),image=await readFile('public/assets/keepsakes/memory-1.webp');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('artifacts/accounts',{recursive:true});
try{
 const opContext=await browser.newContext({acceptDownloads:true}),userContext=await browser.newContext({acceptDownloads:true}),op=await opContext.newPage(),user=await userContext.newPage(),errors=[],rebuildRequests=[];op.on('request',r=>{if(/\/api\/(agent|artwork|cloud|sculpture)/.test(r.url()))rebuildRequests.push(r.url());});op.on('pageerror',e=>errors.push('operator: '+e.message));user.on('pageerror',e=>errors.push('user: '+e.message));
 const auth=async(ctx,path,data)=>{const r=await ctx.request.post(base+path,{headers:{Origin:base},data});assert.ok(r.ok(),await r.text());};
 await auth(opContext,'/api/auth/setup',{username:'studio',password:'safe-password',name:'文创工作室'});await op.goto(base+'/operator.html');
 await auth(userContext,'/api/auth/register',{username:'visitor',password:'safe-password',name:'旅行体验者'});await user.goto(base+'/orders.html#new');await user.locator('#order-form').waitFor();
 await user.evaluate(async data=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),photo=new Blob([Uint8Array.from(atob(data.image),c=>c.charCodeAt(0))],{type:'image/webp'});await s.save({keepsake:{id:'customer-work',schemaVersion:1,title:'城市旅行数字纪念',city:'广州',kind:'miniature',productType:'figurine',baseMode:'round',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'generated:customer-work-0001:0',generationId:'customer-work-0001',assetIndex:0,sourcePhotoId:'customer-photo',memoryIds:['customer-memory'],collectionStory:'城市旅行的记忆',createdAt:1,updatedAt:1},memories:[{id:'customer-memory',keepsakeId:'customer-work',authorId:'me',date:'',placeName:'广州',story:'城市旅行的记忆',photoIds:['customer-photo']}],photos:[{id:'customer-photo',blob:photo}]});await s.setMeta('generated-asset:customer-work-0001:0',{reference:photo,glb:new Blob([new Uint8Array(data.glb)],{type:'model/gltf-binary'}),productType:'figurine',baseMode:'round',preview:null,exportable:true,report:{checks:[{name:'topology',status:'pass'},{name:'connected',status:'pass'},{name:'standing-stability',status:'pass'}]}});s.close();},{image:image.toString('base64'),glb:[...glb]});
 await user.goto(base+'/orders.html?work=customer-work');await user.getByRole('heading',{name:'确认实体制作',exact:true}).waitFor();assert.equal(await user.locator('.product-choice:visible,[name=photos]:visible,[name=raw]:visible').count(),0);await user.locator('[name=productionNote]').fill('请先确认最终尺寸');await user.getByRole('button',{name:'提交给经营者',exact:true}).click();await user.getByText('实体制作申请已提交，经营者可以开始生产检查。',{exact:true}).waitFor();const orderId=new URL(user.url()).hash.slice(1);
 await op.locator('.list-row').filter({hasText:'城市旅行数字纪念'}).waitFor({timeout:15000});await op.locator('.list-row').filter({hasText:'城市旅行数字纪念'}).click();await op.getByRole('button',{name:'接受委托，确认打印规格',exact:true}).click();
 await op.locator('[name=sizeCm]').waitFor();
 assert.equal(await op.locator('[data-action=creator],[data-action=confirm-reference],[data-action=use-input]').count(),0,'existing assets skip proposal creation and adoption');
 assert.equal(await op.getByRole('button',{name:'方案预览',exact:true}).count(),0);
 await op.locator('#work-view canvas').waitFor();
 await op.locator('[name=sizeCm]').fill('18');await op.locator('[name=material]').fill('树脂');await op.locator('[name=quantity]').fill('2');
 await op.locator('[name=productionNote]').fill('报价 180 元，按最长边 18 cm 制作两件，先确认费用再打印。');
 await op.getByRole('button',{name:'发送尺寸与报价',exact:true}).click();await user.getByText(/制作规格：.*18 cm/).waitFor();
 const stlDownload=op.waitForEvent('download');await op.getByRole('button',{name:'导出 STL 打印文件',exact:true}).click();
 const stl=await readFile(await(await stlDownload).path()),triangles=stl.readUInt32LE(80),min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];
 for(let i=0;i<triangles;i++)for(let j=0;j<9;j++){const axis=j%3,value=stl.readFloatLE(84+i*50+12+j*4);min[axis]=Math.min(min[axis],value);max[axis]=Math.max(max[axis],value);}
 assert.ok(Math.abs(Math.max(...max.map((v,i)=>v-min[i]))-180)<.001);assert.equal(min[2],0);
 const original=await(await opContext.request.get(base+'/api/orders/'+orderId)).json();assert.equal(original.commission.sizeCm,18);assert.equal(original.commission.quantity,2);assert.ok(original.commission.selection);assert.ok(!original.proposal);
 assert.deepEqual(await(await opContext.request.get(base+original.result.files.find(f=>f.kind==='model').url)).body(),Buffer.from(glb),'the server still uses the original submitted model');
 await op.screenshot({path:'artifacts/accounts/production-specs.png',fullPage:true});
 await op.goto(base+'/production.html?operator='+orderId+'#single-create');await op.waitForURL('**/operator.html#commission/'+orderId+'/make');
 await op.locator('[name=sizeCm]').waitFor();await op.locator('[data-work-stage=review]').first().click();await op.locator('[name=reviewNote]').waitFor({timeout:10000}).catch(async error=>{console.error('REVIEW STATE:',op.url(),await op.locator('#operator-status').textContent(),await op.locator('.work-content').innerText());throw error;});await op.locator('[name=sizeCm]').fill('19');await op.locator('[name=quantity]').fill('3');await op.locator('[name=reviewNote]').fill('已核对用户素材与生产模型');await op.locator('[name=physicalEvidence]').fill('已按最长边19 cm完成切片检查与树脂试打，结构稳定');await op.locator('[name=physicalVerified]').check();await op.getByRole('button',{name:'审核通过，去交付',exact:true}).click();await op.getByRole('button',{name:'导出交付包',exact:true}).waitFor();const approved=await(await opContext.request.get(base+'/api/orders/'+orderId)).json();assert.equal(approved.commission.sizeCm,19);assert.equal(approved.commission.quantity,3);assert.equal(approved.commission.review.briefVersion,approved.commission.briefVersion);assert.equal(approved.commission.confirmedVersion,approved.commission.briefVersion);
 await user.getByRole('button',{name:'确认这版作品',exact:true}).waitFor({timeout:15000});assert.equal(await user.getByRole('link',{name:'下载3D模型',exact:true}).count(),1);await user.locator('[name=customerNote]').fill('这版数字作品符合预期');await user.getByRole('button',{name:'确认这版作品',exact:true}).click();await op.getByText('当前：用户已确认',{exact:true}).waitFor({timeout:15000});
 const download=op.waitForEvent('download');await op.getByRole('button',{name:'导出交付包',exact:true}).click();await download;await op.getByText('本委托的交付包已导出；尚未自动记录实际交付。',{exact:true}).waitFor();await op.locator('[name=deliveryMethod]').fill('用户在订单页面领取数字文件');await op.getByRole('button',{name:'记录实际交付',exact:true}).click();await op.getByText('实际交付记录已保存。',{exact:true}).waitFor();await user.getByText('经营者已记录交付，交付文件仍可在本页领取。',{exact:true}).waitFor({timeout:15000});
 await op.setViewportSize({width:1440,height:960});await user.setViewportSize({width:1440,height:960});await op.screenshot({path:'artifacts/accounts/operator.png',fullPage:true});await user.screenshot({path:'artifacts/accounts/customer.png',fullPage:true});await user.setViewportSize({width:390,height:844});assert.ok(await user.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await user.screenshot({path:'artifacts/accounts/customer-mobile.png',fullPage:true});
 const other=await browser.newContext(),third=await other.newPage();await third.goto(base+'/portal.html');await third.evaluate(async()=>{const {accountApi}=await import('/src/account-client.js');await accountApi('/api/auth/register',{username:'outsider',password:'safe-password',name:'其他用户'});});assert.equal(await third.evaluate(async id=>(await fetch('/api/orders/'+id)).status,orderId),403);await third.reload();assert.equal(await third.getByRole('button',{name:'切换到经营者端',exact:true}).count(),0);
 assert.deepEqual(errors,[]);assert.deepEqual(rebuildRequests,[],'the production path never generates or rebuilds a 3D asset');await other.close();console.log('PASS accounts: common login, independent customer/operator contexts, selected source/model submission, review, result confirmation, delivery, role permissions, private orders, desktop/mobile; no AI calls.');
}finally{await browser.close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
