import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {makeMiniature} from '../public/src/travel-miniature.js';import {glbFromPreview} from '../public/src/mesh-glb-export.js';
const dir=await mkdtemp(join(tmpdir(),'orders-flow-')),server=createApp({accountsEnabled:true,accountDir:dir}),model=makeMiniature('gz'),glb=new Uint8Array(await glbFromPreview({...model,originalColors:model.colors}).arrayBuffer()),image=await readFile('public/assets/keepsakes/memory-1.webp');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('artifacts/accounts',{recursive:true});
try{
 const opContext=await browser.newContext({acceptDownloads:true}),userContext=await browser.newContext({acceptDownloads:true}),op=await opContext.newPage(),user=await userContext.newPage(),errors=[];op.on('pageerror',e=>errors.push('operator: '+e.message));user.on('pageerror',e=>errors.push('user: '+e.message));
 await op.goto(base+'/portal.html');await op.locator('[data-mode=setup]').click();await op.locator('[name=username]').fill('studio');await op.locator('[name=password]').fill('safe-password');await op.locator('[name=name]').fill('文创工作室');await op.getByRole('button',{name:'创建工作室并进入',exact:true}).click();await op.waitForURL('**/operator.html');await op.getByRole('button',{name:'切换到用户端',exact:true}).waitFor();
 await user.goto(base+'/portal.html');await user.locator('[data-mode=register]').click();await user.locator('[name=username]').fill('visitor');await user.locator('[name=password]').fill('safe-password');await user.locator('[name=name]').fill('旅行体验者');await user.getByRole('button',{name:'注册并进入用户端',exact:true}).click();await user.waitForURL('**/collection.html**');await user.getByRole('link',{name:'我的订单',exact:true}).first().waitFor();
 await user.evaluate(async data=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),photo=new Blob([Uint8Array.from(atob(data.image),c=>c.charCodeAt(0))],{type:'image/webp'});await s.save({keepsake:{id:'customer-work',schemaVersion:1,title:'城市旅行数字纪念',city:'广州',kind:'miniature',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'generated:customer-work-0001:0',generationId:'customer-work-0001',assetIndex:0,sourcePhotoId:'customer-photo',memoryIds:['customer-memory'],createdAt:1,updatedAt:1},memories:[{id:'customer-memory',keepsakeId:'customer-work',authorId:'me',date:'',placeName:'广州',story:'城市旅行的记忆',photoIds:['customer-photo']}],photos:[{id:'customer-photo',blob:photo}]});await s.setMeta('generated-asset:customer-work-0001:0',{reference:photo,glb:new Blob([new Uint8Array(data.glb)],{type:'model/gltf-binary'}),preview:null,report:{checks:[]}});s.close();},{image:image.toString('base64'),glb:[...glb]});
 await user.goto(base+'/orders.html?work=customer-work');await user.locator('[name=title]').waitFor();await user.locator('[name=productType][value=figurine]').check();await user.waitForFunction(()=>document.querySelector('#selected-note')?.textContent.includes('已有作品'));assert.equal(await user.locator('[name=raw]').inputValue(),'城市旅行的记忆');await user.locator('[name=raw]').fill('城市旅行的记忆。'.repeat(130));await user.getByRole('button',{name:'提交给经营者审核',exact:true}).click();await user.getByText('需求已提交，经营者可以收到并审核。',{exact:true}).waitFor();const orderId=new URL(user.url()).hash.slice(1);
 await op.locator('.list-row').filter({hasText:'城市旅行数字纪念'}).waitFor({timeout:15000});await op.locator('.list-row').filter({hasText:'城市旅行数字纪念'}).click();await op.getByRole('button',{name:'接受需求，开始制作',exact:true}).click();await op.getByRole('button',{name:'采用用户提交的作品',exact:true}).waitFor();await op.getByRole('button',{name:'采用用户提交的作品',exact:true}).click();await op.getByRole('button',{name:'提交审核',exact:true}).click();await op.locator('[name=reviewNote]').fill('已核对用户素材，数字模型可交付；实体尚未验证');await op.getByRole('button',{name:'审核通过，去交付',exact:true}).click();await op.getByRole('button',{name:'导出交付包',exact:true}).waitFor();
 await user.getByRole('button',{name:'确认这版作品',exact:true}).waitFor({timeout:15000});assert.equal(await user.getByRole('link',{name:'下载3D模型',exact:true}).count(),1);await user.locator('[name=customerNote]').fill('这版数字作品符合预期');await user.getByRole('button',{name:'确认这版作品',exact:true}).click();await op.getByText(/用户提交 · 摆件 · 用户已确认/).waitFor({timeout:15000});
 const download=op.waitForEvent('download');await op.getByRole('button',{name:'导出交付包',exact:true}).click();await download;await op.getByText('本委托的交付包已导出；尚未自动记录实际交付。',{exact:true}).waitFor();await op.locator('[name=deliveryMethod]').fill('用户在订单页面领取数字文件');await op.getByRole('button',{name:'记录实际交付',exact:true}).click();await op.getByText('实际交付记录已保存。',{exact:true}).waitFor();await user.getByText('经营者已记录交付，交付文件仍可在本页领取。',{exact:true}).waitFor({timeout:15000});
 await op.setViewportSize({width:1440,height:960});await user.setViewportSize({width:1440,height:960});await op.screenshot({path:'artifacts/accounts/operator.png',fullPage:true});await user.screenshot({path:'artifacts/accounts/customer.png',fullPage:true});await user.setViewportSize({width:390,height:844});assert.ok(await user.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await user.screenshot({path:'artifacts/accounts/customer-mobile.png',fullPage:true});
 const other=await browser.newContext(),third=await other.newPage();await third.goto(base+'/portal.html');await third.evaluate(async()=>{const {accountApi}=await import('/src/account-client.js');await accountApi('/api/auth/register',{username:'outsider',password:'safe-password',name:'其他用户'});});assert.equal(await third.evaluate(async id=>(await fetch('/api/orders/'+id)).status,orderId),403);await third.reload();assert.equal(await third.getByRole('button',{name:'切换到经营者端',exact:true}).count(),0);
 assert.deepEqual(errors,[]);await other.close();console.log('PASS accounts: common login, independent customer/operator contexts, selected source/model submission, review, result confirmation, delivery, role permissions, private orders, desktop/mobile; no AI calls.');
}finally{await browser.close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
