import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createAccountWorkspace} from '../account-workspace.js';
import {makeMiniature} from '../public/src/travel-miniature.js';
import {glbFromPreview} from '../public/src/mesh-glb-export.js';
test('accounts enforce roles, persist sessions and owned orders, reject stale writes and hide internal records',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'accounts-test-'));try{let w=await createAccountWorkspace(dir);const owner=await w.register({username:'owner',password:'safe-password',name:'工作室'},{operator:true}),alice=await w.register({username:'alice',password:'safe-password',name:'游客A'}),bob=await w.register({username:'bob',password:'safe-password',name:'游客B'});assert.deepEqual(owner.roles,['user','operator']);assert.deepEqual(alice.roles,['user']);await assert.rejects(w.register({username:'eve',password:'safe-password',roles:['operator']}),/权限/);await assert.rejects(w.login({username:'alice',password:'wrong-password'}),/账号或密码/);const login=await w.login({username:'alice',password:'safe-password',role:'user'});assert.equal((await w.session(login.token)).user.id,alice.id);
 const order=await w.createOrder(alice,{title:'毕业纪念',raw:'保留照片可见人物',productType:'magnet',deliveryType:'image',photos:[{image:'data:image/png;base64,iVBORw0KGgo='}]});assert.equal(order.status,'submitted');assert.equal((await w.listOrders(owner)).length,1);assert.equal((await w.listOrders(bob)).length,0);await assert.rejects(w.getOrder(bob,order.id),/权限|不存在/);
 const accepted=await w.updateOrder(owner,order.id,{revision:order.revision,action:'accept',internalNote:'private-secret'});assert.equal(accepted.status,'making');await assert.rejects(w.updateOrder(owner,order.id,{revision:order.revision,action:'accept'}),/更新/);assert.ok(!JSON.stringify(await w.getOrder(alice,order.id)).includes('private-secret'));
 w=await createAccountWorkspace(dir);assert.equal((await w.session(login.token)).user.id,alice.id);assert.equal((await w.getOrder(owner,order.id)).status,'making');const raw=await readFile(join(dir,'workspace.json'),'utf8');assert.ok(!raw.includes('safe-password'));assert.ok(!raw.includes(login.token));
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('published and delivered results require current reviews, current customer confirmation and current export',async()=>{const dir=await mkdtemp(join(tmpdir(),'order-review-'));try{const w=await createAccountWorkspace(dir),op=await w.register({username:'studio',password:'safe-password'},{operator:true}),user=await w.register({username:'visitor',password:'safe-password'});let o=await w.createOrder(user,{title:'数字纪念',raw:'依据照片',productType:'magnet',deliveryType:'image',photos:[{image:'data:image/png;base64,iVBORw0KGgo='}]});o=await w.updateOrder(op,o.id,{revision:o.revision,action:'accept'});o=await w.putResult(op,o.id,{revision:o.revision,reference:{image:'data:image/png;base64,iVBORw0KGgo='},work:{id:'test-work',revision:1,title:'作品'}});const c=structuredClone(o.commission);c.status='delivery';c.review={accepted:true,briefVersion:0,assetRevision:0,note:'旧审核'};await assert.rejects(w.putCommission(op,o.id,c),/审核|版本/);c.review={accepted:true,briefVersion:c.briefVersion,assetRevision:c.assetRevision,note:'已核对'};let saved=await w.putCommission(op,o.id,c);o=await w.getOrder(user,o.id);assert.equal(o.status,'awaiting_confirmation');await assert.rejects(w.putCommission(op,o.id,{...saved,status:'delivered'}),/确认|导出/);o=await w.updateOrder(user,o.id,{revision:o.revision,action:'confirm'});saved=(await w.getOrder(op,o.id)).commission;await assert.rejects(w.putCommission(op,o.id,{...saved,status:'delivered'}),/导出/);saved.exports=[{version:`${saved.briefVersion}.${saved.assetRevision}`,at:Date.now(),name:'作品.zip'}];saved.status='delivered';saved=await w.putCommission(op,o.id,saved);saved.internalNote='交付后补充记录';saved=await w.putCommission(op,o.id,saved);assert.equal(saved.internalNote,'交付后补充记录');assert.equal((await w.getOrder(user,o.id)).status,'delivered');}finally{await rm(dir,{recursive:true,force:true});}});
test('an order carrying a GLB starts in the existing-asset production path',async()=>{const dir=await mkdtemp(join(tmpdir(),'asset-order-'));try{const w=await createAccountWorkspace(dir),op=await w.register({username:'studio2',password:'safe-password'},{operator:true}),user=await w.register({username:'visitor2',password:'safe-password'}),model=makeMiniature('gz'),glb=Buffer.from(await glbFromPreview({...model,originalColors:model.colors}).arrayBuffer());const order=await w.createOrder(user,{title:'现有摆件',raw:'直接生产',productType:'figurine',baseMode:'round',deliveryType:'physical',photos:[{image:'data:image/png;base64,iVBORw0KGgo='}],inputModel:{base64:glb.toString('base64')}}),shared=await w.getOrder(op,order.id);assert.equal(shared.commission.serviceMode,'production');assert.equal(shared.commission.productionStatus,'checking');const accepted=await w.updateOrder(op,order.id,{revision:shared.revision,action:'accept'});assert.ok(accepted.commission.selection,'accepting a model order automatically selects the submitted asset');assert.equal(accepted.result.files.find(f=>f.kind==='model').id,shared.inputs.find(f=>f.kind==='model').id);assert.deepEqual((await w.getFile(op,order.id,accepted.result.files.find(f=>f.kind==='model').id)).bytes,glb);assert.ok(!accepted.proposal);assert.doesNotMatch(accepted.messages.at(-1).text,/方案/);await assert.rejects(w.updateOrder(op,order.id,{revision:accepted.revision,action:'publish-proposal'}),/已有.*3D|无需.*方案/);const old=JSON.parse(await readFile(join(dir,'workspace.json'),'utf8')),legacy=old.orders.find(o=>o.id===order.id);legacy.commission.serviceMode='assisted';await writeFile(join(dir,'workspace.json'),JSON.stringify(old));const kept=await createAccountWorkspace(dir),keptOrder=await kept.getOrder(op,order.id);assert.equal(keptOrder.commission.serviceMode,'production');assert.equal(keptOrder.result.id,accepted.result.id,'migration keeps an existing selected result');legacy.result=null;legacy.commission.selection=null;legacy.commission.assetRevision=0;legacy.commission.status='make';await writeFile(join(dir,'workspace.json'),JSON.stringify(old));const restored=await createAccountWorkspace(dir);assert.equal((await restored.getOrder(op,order.id)).commission.serviceMode,'production');const adopted=await restored.updateOrder(op,order.id,{revision:legacy.revision,action:'use-submitted'});assert.ok(adopted.commission.selection,'previously accepted model orders can recover their submitted model');const again=await restored.updateOrder(op,order.id,{revision:adopted.revision,action:'use-submitted'});assert.equal(again.result.id,adopted.result.id);assert.equal(again.commission.assetRevision,adopted.commission.assetRevision,'adoption does not create another asset version');}finally{await rm(dir,{recursive:true,force:true});}});
