import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createAccountWorkspace} from '../account-workspace.js';
test('accounts enforce roles, persist sessions and owned orders, reject stale writes and hide internal records',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'accounts-test-'));try{let w=await createAccountWorkspace(dir);const owner=await w.register({username:'owner',password:'safe-password',name:'工作室'},{operator:true}),alice=await w.register({username:'alice',password:'safe-password',name:'游客A'}),bob=await w.register({username:'bob',password:'safe-password',name:'游客B'});assert.deepEqual(owner.roles,['user','operator']);assert.deepEqual(alice.roles,['user']);await assert.rejects(w.register({username:'eve',password:'safe-password',roles:['operator']}),/权限/);await assert.rejects(w.login({username:'alice',password:'wrong-password'}),/账号或密码/);const login=await w.login({username:'alice',password:'safe-password',role:'user'});assert.equal((await w.session(login.token)).user.id,alice.id);
 const order=await w.createOrder(alice,{title:'毕业纪念',raw:'保留照片可见人物',productType:'magnet',deliveryType:'image',photos:[{image:'data:image/png;base64,iVBORw0KGgo='}]});assert.equal(order.status,'submitted');assert.equal((await w.listOrders(owner)).length,1);assert.equal((await w.listOrders(bob)).length,0);await assert.rejects(w.getOrder(bob,order.id),/权限|不存在/);
 const accepted=await w.updateOrder(owner,order.id,{revision:order.revision,action:'accept',internalNote:'private-secret'});assert.equal(accepted.status,'making');await assert.rejects(w.updateOrder(owner,order.id,{revision:order.revision,action:'accept'}),/更新/);assert.ok(!JSON.stringify(await w.getOrder(alice,order.id)).includes('private-secret'));
 w=await createAccountWorkspace(dir);assert.equal((await w.session(login.token)).user.id,alice.id);assert.equal((await w.getOrder(owner,order.id)).status,'making');const raw=await readFile(join(dir,'workspace.json'),'utf8');assert.ok(!raw.includes('safe-password'));assert.ok(!raw.includes(login.token));
 }finally{await rm(dir,{recursive:true,force:true});}
});
test('published and delivered results require current reviews, current customer confirmation and current export',async()=>{const dir=await mkdtemp(join(tmpdir(),'order-review-'));try{const w=await createAccountWorkspace(dir),op=await w.register({username:'studio',password:'safe-password'},{operator:true}),user=await w.register({username:'visitor',password:'safe-password'});let o=await w.createOrder(user,{title:'数字纪念',raw:'依据照片',productType:'magnet',deliveryType:'image',photos:[{image:'data:image/png;base64,iVBORw0KGgo='}]});o=await w.updateOrder(op,o.id,{revision:o.revision,action:'accept'});o=await w.putResult(op,o.id,{revision:o.revision,reference:{image:'data:image/png;base64,iVBORw0KGgo='},work:{id:'test-work',revision:1,title:'作品'}});const c=structuredClone(o.commission);c.status='delivery';c.review={accepted:true,briefVersion:0,assetRevision:0,note:'旧审核'};await assert.rejects(w.putCommission(op,o.id,c),/审核|版本/);c.review={accepted:true,briefVersion:c.briefVersion,assetRevision:c.assetRevision,note:'已核对'};let saved=await w.putCommission(op,o.id,c);o=await w.getOrder(user,o.id);assert.equal(o.status,'awaiting_confirmation');await assert.rejects(w.putCommission(op,o.id,{...saved,status:'delivered'}),/确认|导出/);o=await w.updateOrder(user,o.id,{revision:o.revision,action:'confirm'});saved=(await w.getOrder(op,o.id)).commission;await assert.rejects(w.putCommission(op,o.id,{...saved,status:'delivered'}),/导出/);saved.exports=[{version:`${saved.briefVersion}.${saved.assetRevision}`,at:Date.now(),name:'作品.zip'}];saved.status='delivered';saved=await w.putCommission(op,o.id,saved);saved.internalNote='交付后补充记录';saved=await w.putCommission(op,o.id,saved);assert.equal(saved.internalNote,'交付后补充记录');assert.equal((await w.getOrder(user,o.id)).status,'delivered');}finally{await rm(dir,{recursive:true,force:true});}});
