import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {createCollectionJobs} from '../collection-jobs.js';
const image='data:image/png;base64,iVBORw0KGgo=';
const input={requestId:'cover-request-0001',photos:[{id:'p1',image}],cover:{guide:image,memories:[{id:'m1',photoId:'p1',title:'照片1',evidence:'来源照片',target:'source scene',kind:'scene'}]}};
async function settle(jobs,id){for(let i=0;i<200;i++){const j=await jobs.get(id);if(!['running','queued'].includes(j.status))return j;await new Promise(r=>setTimeout(r,5));}throw Error('job did not settle');}
function baseServices(){return {curate:async()=>({story:'照片',points:[{photoId:'p1',title:'回忆',evidence:'照片',storyDraft:'照片'}]}),design:async()=>({caption:'回忆',brief:{elements:['主体']}}),startArtwork:async()=> 'art',readArtwork:async()=>({status:'success',image}),prepareImage:async x=>x,startModel:async()=> 'model',readModel:async()=>({status:'success',glb:Buffer.from('model')}),inspect:async()=>({report:{checks:[]},exportable:false})};}
test('a photo-only collection generates its cover without design or model calls',async()=>{const dir=await mkdtemp(join(tmpdir(),'cover-photo-'));let covers=0;const jobs=await createCollectionJobs({dir,pollMs:1,services:{...baseServices(),curate:async()=>{throw Error('not requested');},startModel:async()=>{throw Error('paid model must not run');},startCover:async()=>{covers++;return 'photo-cover';}}});try{await jobs.createCoverOnly(input);const j=await settle(jobs,input.requestId);assert.equal(j.mode,'cover-only');assert.equal(j.coverStatus,'completed');assert.equal(j.assets.length,0);assert.equal(j.steps.length,2);assert.equal(covers,1);}finally{await jobs.close();await rm(dir,{recursive:true,force:true});}});
test('a cover-only request never retries a previously failed paid model',async()=>{const dir=await mkdtemp(join(tmpdir(),'cover-only-'));let models=0,covers=0;const jobs=await createCollectionJobs({dir,pollMs:1,services:{...baseServices(),startModel:async()=>{models++;return 'model';},readModel:async()=>({status:'failed'}),startCover:async()=>{covers++;return 'cover';}}});try{const body={...input,cover:undefined};await jobs.create(body);assert.equal((await settle(jobs,input.requestId)).status,'failed');await jobs.createCover(input.requestId,input.cover);const j=await settle(jobs,input.requestId);assert.ok(j.cover);assert.equal(j.status,'failed');assert.equal(models,1);assert.equal(covers,1);}finally{await jobs.close();await rm(dir,{recursive:true,force:true});}});
test('ambiguous cover submission resumes by remote ID without another paid run',async()=>{const dir=await mkdtemp(join(tmpdir(),'cover-resolve-'));let covers=0;const jobs=await createCollectionJobs({dir,pollMs:1,services:{...baseServices(),startCover:async()=>{covers++;throw Error('Tripo cover 请求失败（HTTP 502）');}}});try{await jobs.create(input);let j=await settle(jobs,input.requestId);assert.equal(j.coverUncertain,'artwork');assert.equal(j.coverStatus,'failed');await jobs.createCover(j.id,{resolveTaskId:'cover-already-submitted'});j=await settle(jobs,j.id);assert.equal(j.coverStatus,'completed');assert.ok(j.cover);assert.equal(covers,1);}finally{await jobs.close();await rm(dir,{recursive:true,force:true});}});
test('automatic cover is saved after models and retry does not resubmit completed assets',async()=>{const dir=await mkdtemp(join(tmpdir(),'lvzang-cover-'));let covers=0,models=0;const jobs=await createCollectionJobs({dir,pollMs:1,services:{curate:async()=>({story:'来源旅行照片',points:[{photoId:'p1',title:'回忆',evidence:'照片',storyDraft:'照片'}]}),design:async()=>({caption:'回忆',brief:{elements:['主体']}}),startArtwork:async()=> 'art',readArtwork:async()=>({status:'success',image}),prepareImage:async x=>x,startModel:async()=>{models++;return 'model';},readModel:async()=>({status:'success',glb:Buffer.from('model')}),inspect:async()=>({report:{checks:[]},exportable:false}),startCover:async()=>{covers++;return 'cover';}}});try{await jobs.create(input);let j;for(let i=0;i<150;i++){j=await jobs.get(input.requestId);if(j.status==='completed')break;await new Promise(r=>setTimeout(r,5));}assert.equal(j.coverStatus,'completed');assert.ok(j.cover);assert.ok((await jobs.exportFiles(j.id))['cover.jpg']);await jobs.retry(j.id);for(let i=0;i<100;i++){if((await jobs.get(j.id)).status==='completed')break;await new Promise(r=>setTimeout(r,5));}assert.equal(covers,1);assert.equal(models,1);}finally{await jobs.close();await rm(dir,{recursive:true,force:true});}});
