import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createApp} from '../server.js';
import {decodeKeepsakeBackup} from '../public/src/travel-keepsake-backup.js';

const dir=await mkdtemp(join(tmpdir(),'lvzang-browser-')),photo=await readFile('public/assets/keepsakes/memory-1.webp');
let artCalls=0,modelCalls=0,ready=false,failFirst=false;
const task=data=>Response.json({code:0,data});
const glb=Buffer.alloc(20);glb.write('glTF');glb.writeUInt32LE(2,4);glb.writeUInt32LE(20,8);
const fetchImpl=async(url,options)=>{
  if(url.includes('deepseek.com')){const body=JSON.parse(options.body),curation=body.messages[0].content.includes('selectedPhotoIds');return Response.json({choices:[{message:{content:JSON.stringify(curation?{story:'照片里，留下了这趟旅行的记忆。',selectedPhotoIds:['p1','p2'],points:['p1','p2'].map(photoId=>({photoId,title:'旅行记忆'+photoId,evidence:'照片可见主体',storyDraft:'照片里的一刻',cutoutKind:'scene'}))}:{caption:'旅行记忆',reason:'依据照片可见主体',brief:{summary:'照片里的旅行记忆',elements:['可见主体'],composition:'主体居中，厚实体连接',imagePrompt:'依据广州来源照片设计厚实体旅行纪念物',decisions:['framing','place','lettering','occlusion'].map(topic=>({topic,evidence:'来源照片',action:'依据照片构图',uncertainty:'未确认信息保持未知'}))}})}}]});}
  if(url.endsWith('/files'))return task({file_token:'photo'});
  if(url.includes('/generation/'))return task({task_id:'art-'+(++artCalls)});
  if(url.includes('/tasks/'))return task({status:'success',progress:100,output:{generated_image_url:'https://cdn.tripo3d.ai/reference.webp'}});
  if(url.endsWith('reference.webp'))return new Response(photo);
  if(url.endsWith('/upload/sts'))return task({image_token:'image'});
  if(url.endsWith('/task'))return task({task_id:'model-'+(++modelCalls)});
  if(url.includes('/task/'))return task(failFirst&&url.endsWith('model-3')?{status:'failed'}:ready?{status:'success',progress:100,output:{model:'https://cdn.tripo3d.ai/model.glb'}}:{status:'running',progress:37});
  if(url.endsWith('model.glb'))return new Response(glb);
  throw Error('unexpected URL '+url);
};
const server=createApp({key:'test',tripoKey:'test',fetchImpl,collectionDir:dir,collectionPollMs:10,build:async()=>({mesh:[-20,0,0,20,0,0,0,30,0],originalColors:[255,100,80,255,100,80,255,100,80],widthMm:40,heightMm:30,totalDepthMm:2,report:{source:'glb',checks:[{name:'slicing',status:'warn',detail:'需切片验证'}]},parts:[]})});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('artifacts/collection-generation',{recursive:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/collection.html');await page.locator('.world-viewport').waitFor();assert.equal(artCalls,0,'opening must not spend credits');
  await page.getByRole('button',{name:'添加旅行回忆',exact:true}).click();await page.locator('[name=photo]').setInputFiles(['public/assets/keepsakes/memory-1.webp','public/assets/keepsakes/memory-2.webp']);await page.locator('.studio-extra summary').click();await page.locator('[name=trip-name]').fill('广州毕业旅行');await page.locator('[name=city]').fill('广州');await page.locator('[name=note]').fill('和朋友一起留下旅行回忆');await page.waitForFunction(()=>!document.querySelector('[data-action=generate-upload]').disabled);await page.getByRole('button',{name:'一键制作旅行合集',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.generation-job')?.textContent.includes('正在生成 3D'));
  await page.screenshot({path:'artifacts/collection-generation/01-desktop-progress.png',fullPage:true});await page.reload();await page.locator('.generation-job').waitFor();assert.equal(artCalls,1);assert.equal(modelCalls,1);ready=true;await page.waitForFunction(()=>document.querySelector('.generation-job')?.textContent.includes('合集已完成'),{},{timeout:15000});await page.waitForFunction(()=>document.querySelectorAll('.world-group').length===1&&document.querySelectorAll('.asset-model').length===2);
  assert.equal(artCalls,2);assert.equal(modelCalls,2);assert.equal(await page.locator('.asset-photo').count(),2);await page.locator('.studio-shelf button[data-asset]').first().click();await page.locator('.generated-preview canvas').waitFor();await page.locator('.studio-tools .world-inspector').getByRole('link',{name:'下载 3D 模型'}).waitFor();await page.screenshot({path:'artifacts/collection-generation/02-desktop-completed.png',fullPage:true});
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出完整备份',exact:true}).click();const downloaded=await downloadPromise;const backup=decodeKeepsakeBackup(await readFile(await downloaded.path()));assert.equal(backup.keepsakes.length,2);assert.equal(backup.meta.filter(m=>m.id.startsWith('generated-asset:')).length,2);
  await page.reload();await page.locator('.studio-shelf-item').first().waitFor();assert.equal(artCalls,2);assert.equal(modelCalls,2);await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/collection-generation/03-mobile-completed.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  await page.getByRole('button',{name:'添加旅行回忆',exact:true}).click();await page.locator('[name=photo]').setInputFiles('public/assets/keepsakes/memory-1.webp');await page.waitForFunction(()=>!document.querySelector('[data-action=generate-upload]').disabled);await page.screenshot({path:'artifacts/collection-generation/04-mobile-upload.png',fullPage:true});
  failFirst=true;const partialContext=await browser.newContext(),partialPage=await partialContext.newPage();await partialPage.goto(base+'/collection.html');await partialPage.getByRole('button',{name:'添加旅行回忆',exact:true}).click();await partialPage.locator('[name=photo]').setInputFiles(['public/assets/keepsakes/memory-1.webp','public/assets/keepsakes/memory-2.webp']);await partialPage.locator('.studio-extra summary').click();await partialPage.locator('[name=city]').fill('广州');await partialPage.waitForFunction(()=>!document.querySelector('[data-action=generate-upload]').disabled);await partialPage.getByRole('button',{name:'一键制作旅行合集',exact:true}).click();await partialPage.waitForFunction(()=>document.querySelector('.generation-job')?.textContent.includes('部分作品已完成'));await partialPage.locator('.studio-shelf-item').first().waitFor();const partialBackupPromise=partialPage.waitForEvent('download');await partialPage.getByRole('button',{name:'导出完整备份',exact:true}).click();const partialBackup=decodeKeepsakeBackup(await readFile(await (await partialBackupPromise).path()));assert.equal(partialBackup.photos.length,2,'partial success retains every original photo');assert.equal(partialBackup.keepsakes.length,1);failFirst=false;await partialPage.getByRole('button',{name:'重试这一件',exact:true}).click();await partialPage.waitForFunction(()=>document.querySelector('.generation-job')?.textContent.includes('合集已完成'));await partialPage.waitForFunction(()=>document.querySelectorAll('.asset-model').length===2);assert.equal(modelCalls,5,'only failed model is submitted again');
  const restored=await partialPage.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),store=await openKeepsakeStore(),full=await store.dump(),ids=full.keepsakes.map(k=>k.id);await store.deleteKeepsake(ids[1]);const result=await store.restore(full);const count=(await store.list()).length;store.close();return {result,count};});assert.equal(restored.result.imported,1);assert.equal(restored.count,2,'later backup reuses identical photos already in a partial collection');await partialContext.close();
  console.log('PASS: real server adapters with mocked external AI, no calls on open, one-click pipeline, reload recovery, two models and original photos in one collection, WebGL preview, GLB downloads, portable model backup, mobile layout, no page errors.');
}finally{await browser.close();await (await server.resumeCollections()).close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
