import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createCollectionJobs} from '../collection-jobs.js';

const image='data:image/png;base64,iVBORw0KGgo=';
const request=(id='test-request-0001')=>({requestId:id,name:'广州旅行',place:'广州',story:'一起看珠江',photos:[{id:'p1',image},{id:'p2',image}],style:'clay',memoryMode:'personal'});
function services(overrides={}){let art=0,model=0;return {curate:async input=>({story:input.story,points:input.photos.map(p=>({photoId:p.id,title:p.id,evidence:'照片可见主体',storyDraft:'珠江边',cutoutKind:'scene'}))}),design:async()=>({caption:'旅行',brief:{elements:['江边'],summary:'珠江边'}}),startArtwork:async()=>`art-${++art}`,readArtwork:async()=>({status:'success',image}),prepareImage:async x=>x,startModel:async()=>`model-${++model}`,readModel:async()=>({status:'success',glb:Buffer.from('saved-model')}),inspect:async()=>({report:{checks:[]},preview:{mesh:[0,0,0]},exportable:false}),...overrides};}
async function setup(t,overrides={}){const dir=await mkdtemp(join(tmpdir(),'lvzang-jobs-'));const deps=services(overrides);const jobs=await createCollectionJobs({dir,services:deps,pollMs:2});t.after(async()=>{await jobs.close();await rm(dir,{recursive:true,force:true});});return {jobs,dir,deps};}
async function finished(jobs,id){for(let i=0;i<250;i++){const j=await jobs.get(id);if(!['queued','running'].includes(j.status))return j;await new Promise(r=>setTimeout(r,5));}throw Error('task did not settle');}

test('background collection saves assets, real counts and idempotent submissions without a browser',async t=>{let paid=0;const {jobs}=await setup(t,{startModel:async()=>`model-${++paid}`});const a=await jobs.create(request());const b=await jobs.create(request());assert.equal(a.id,b.id);const j=await finished(jobs,a.id);assert.equal(j.status,'completed');assert.equal(j.assets.length,2);assert.equal(paid,2);assert.equal(j.steps.at(-1).status,'completed');assert.equal(j.counts.photos,2);assert.equal((await jobs.asset(j.id,'0.glb')).toString(),'saved-model');await assert.rejects(jobs.create({...request(),story:'changed'}),/重复|冲突/);});
test('selected product rules reach design and replace the download with manufactured geometry',async t=>{let designed,inspected;const {jobs}=await setup(t,{design:async input=>{designed=input;return {caption:'桌面摆件',brief:{elements:['人物'],summary:'带底座摆件'}};},inspect:async(_glb,input)=>{inspected=input;return {report:{checks:[]},preview:{mesh:[0,0,0]},exportable:true,glb:Buffer.from('manufactured-figurine')};}});const body={...request('product-request-0001'),photos:[{id:'p1',image}],productType:'figurine',baseMode:'round',style:'wood'};const created=await jobs.create(body);const job=await finished(jobs,created.id);assert.equal(job.status,'completed');assert.equal(designed.productType,'figurine');assert.equal(designed.baseMode,'round');assert.equal(designed.style,'wood');assert.equal(inspected.productType,'figurine');assert.equal(inspected.baseMode,'round');assert.equal((await jobs.asset(job.id,'0.glb')).toString(),'manufactured-figurine');});
test('failed item can resume alone and completed paid generations are kept',async t=>{let calls=0,fail=true;const {jobs}=await setup(t,{startModel:async()=>`m-${++calls}`,readModel:async id=>id==='m-2'&&fail?{status:'failed'}:{status:'success',glb:Buffer.from(id)}});const a=await jobs.create(request());assert.equal((await finished(jobs,a.id)).status,'partial');fail=false;await jobs.retry(a.id);const j=await finished(jobs,a.id);assert.equal(j.status,'completed');assert.equal(calls,3);assert.equal(j.assets.length,2);});
test('ambiguous paid submission never gets automatically repeated',async t=>{let calls=0;const {jobs}=await setup(t,{startArtwork:async()=>{calls++;throw Error('无法连接 Tripo');}});const a=await jobs.create(request());let j=await finished(jobs,a.id);assert.equal(j.items[0].uncertain,'artwork');await jobs.retry(a.id);j=await finished(jobs,a.id);assert.equal(calls,2);assert.match(j.items[0].error,/核对/);});
test('cancel prevents following stages while retaining an in-flight remote ID',async t=>{let release;const pending=new Promise(r=>release=r);const {jobs}=await setup(t,{startArtwork:async()=>{await pending;return 'in-flight';}});const a=await jobs.create(request());for(let i=0;i<100;i++){if((await jobs.get(a.id)).items[0]?.uncertain)break;await new Promise(r=>setTimeout(r,2));}await jobs.cancel(a.id);release();await jobs.close();const j=await jobs.get(a.id);assert.equal(j.status,'cancelled');assert.equal(j.items[0].artworkTaskId,'in-flight');assert.equal(j.assets.length,0);});
test('restart resumes a remote model by ID without another submission',async t=>{let calls=0;const {jobs,dir,deps}=await setup(t,{startModel:async()=>{calls++;return 'saved-id';},readModel:async()=>({status:'running',progress:35})});const a=await jobs.create(request());for(let i=0;i<100;i++){if((await jobs.get(a.id)).items[0]?.modelTaskId)break;await new Promise(r=>setTimeout(r,2));}await jobs.close();const restarted=await createCollectionJobs({dir,services:{...deps,readModel:async()=>({status:'success',glb:Buffer.from('ok')})},pollMs:2});t.after(()=>restarted.close());assert.equal((await finished(restarted,a.id)).status,'completed');assert.equal(calls,2);});
test('validation rejects hostile IDs, invalid images and more than nine photos',async t=>{const {jobs}=await setup(t);for(const body of [{...request(),requestId:'../escape'},{...request(),photos:[]},{...request(),photos:Array(10).fill({id:'p1',image})},{...request(),photos:[{id:'p1',image:'data:image/png;base64,AAAA'}]}])await assert.rejects(jobs.create(body));await assert.rejects(jobs.asset('../escape','0.glb'));await assert.rejects(jobs.asset('test-request-0001','../state.json'));});
test('HTTP 502 at paid submission remains uncertain on retry',async t=>{let calls=0;const {jobs}=await setup(t,{startArtwork:async()=>{calls++;throw Error('Tripo generation 请求失败（HTTP 502）');}});const a=await jobs.create(request());await finished(jobs,a.id);await jobs.retry(a.id);const j=await finished(jobs,a.id);assert.equal(calls,2);assert.equal(j.items[0].uncertain,'artwork');});
test('damaged task folders do not block healthy recovery',async t=>{const {jobs,dir,deps}=await setup(t);const a=await jobs.create(request());await finished(jobs,a.id);await jobs.close();await mkdir(join(dir,'orphan-request-0001'));await mkdir(join(dir,'damaged-request-0001'));await writeFile(join(dir,'damaged-request-0001','state.json'),'{broken');const recovered=await createCollectionJobs({dir,services:deps,pollMs:2});t.after(()=>recovered.close());assert.equal((await recovered.get(a.id)).status,'completed');});
test('retry one selected failed item leaves the other paid job untouched',async t=>{let calls=0,fail=true;const {jobs}=await setup(t,{startModel:async()=>`single-${++calls}`,readModel:async()=>fail?{status:'failed'}:{status:'success',glb:Buffer.from('ok')}});const a=await jobs.create(request());await finished(jobs,a.id);fail=false;await jobs.retry(a.id,undefined,1);const j=await finished(jobs,a.id);assert.equal(calls,3);assert.equal(j.items[0].status,'failed');assert.equal(j.items[1].status,'completed');});
test('cancel one item retains its remote ID and continues the other item',async t=>{let id=0;const {jobs}=await setup(t,{startArtwork:async()=>`cancel-item-${++id}`,readArtwork:async remote=>remote==='cancel-item-1'?{status:'running',progress:25}:{status:'success',image}});const a=await jobs.create(request());for(let i=0;i<100;i++){if((await jobs.get(a.id)).items[0]?.artworkTaskId)break;await new Promise(r=>setTimeout(r,2));}await jobs.cancel(a.id,0);const j=await finished(jobs,a.id);assert.equal(j.status,'partial');assert.equal(j.items[0].status,'cancelled');assert.equal(j.items[0].artworkTaskId,'cancel-item-1');assert.equal(j.items[1].status,'completed');});
