import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {Document,NodeIO} from '@gltf-transform/core';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.js';
import {createModelPreview} from '../model-preview.js';

const dir=await mkdtemp(join(tmpdir(),'gallery-feedback-')),image='data:image/webp;base64,'+(await readFile('public/assets/keepsakes/memory-1.webp')).toString('base64');
const doc=new Document(),buffer=doc.createBuffer(),positions=doc.createAccessor().setBuffer(buffer).setType('VEC3').setArray(new Float32Array([-1,0,0,1,0,0,0,2,0])),material=doc.createMaterial().setBaseColorFactor([.3,.7,.5,1]);
doc.createScene().addChild(doc.createNode().setMesh(doc.createMesh().addPrimitive(doc.createPrimitive().setAttribute('POSITION',positions).setMaterial(material))));
const glb=await new NodeIO().writeBinary(doc);let ready=false,coverReady=false,coverCalls=0;const coverNames=[],createdNames=[];
const services={curate:async input=>({story:'共同的江南记忆',selectedPhotoIds:['p1'],points:input.photos.map(p=>({photoId:p.id,title:'水乡记忆',evidence:'照片可见画面',storyDraft:'共同的江南记忆'}))}),design:async()=>({caption:'水乡作品',brief:{summary:'共同的江南记忆',elements:[]}}),startArtwork:async()=> 'mock-art',readArtwork:async id=>id==='mock-cover'&&!coverReady?{status:'running',progress:41}:{status:'success',image},prepareImage:async()=>image,startModel:async()=> 'mock-model',readModel:async()=>ready?{status:'success',glb}:{status:'running',progress:32},inspect:async bytes=>({report:{checks:[]},exportable:false,preview:await createModelPreview(bytes)}),preview:createModelPreview,startCover:async input=>{coverNames.push(input.name);coverCalls++;return 'mock-cover';}};
const server=createApp({key:'mock',tripoKey:'mock',accountsEnabled:true,testRoles:true,serverLibrary:true,accountDir:join(dir,'accounts'),libraryDir:join(dir,'library'),collectionDir:join(dir,'jobs'),collectionServices:services,collectionPollMs:20});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage({viewport:{width:1440,height:1000}}),errors=[];let fullAssetReads=0;
page.on('pageerror',e=>errors.push(e.message));
page.on('request',r=>{if(r.url().endsWith('/api/library')){const b=r.postDataJSON();if(b.method==='getMeta'&&b.args[0]?.startsWith('generated-asset:'))fullAssetReads++;}});
try{
 await context.request.post(base+'/api/auth/experience',{headers:{Origin:base},data:{role:'user'}});
 await page.route('**/api/collection-jobs',async route=>{if(route.request().method()==='POST'){const body=route.request().postDataJSON();createdNames.push(body.name);delete body.cover;await route.continue({postData:JSON.stringify(body)});}else await route.continue();});
 await page.goto(base+'/collection.html');await page.getByRole('button',{name:'添加旅行回忆',exact:true}).waitFor();await page.evaluate(()=>document.dispatchEvent(new CustomEvent('collection-generation-progress',{detail:{jobs:[{id:'previous-task-0001',name:'上一次已完成的项目',status:'completed',steps:[],assets:[],items:[]}]}})));await page.getByRole('button',{name:'添加旅行回忆',exact:true}).click();await page.locator('.create-view').waitFor();assert.equal(await page.locator('.canvas-generation .canvas-job').count(),0,'new creation must not show the previous job');assert.ok(await page.locator('[name=trip-name]').isVisible(),'title must be visible before opening optional fields');assert.equal(await page.locator('.studio-extra [name=trip-name]').count(),0);await page.locator('[name=photo]').setInputFiles('public/assets/keepsakes/memory-1.webp');await page.getByRole('button',{name:'一键制作旅行合集',exact:true}).click();assert.equal(createdNames.length,0,'empty title must not submit a paid job');await page.locator('[name=trip-name]').fill('画布上的江南项目');await page.getByRole('button',{name:'一键制作旅行合集',exact:true}).click();
 await page.locator('.canvas-generation').getByText('画布上的江南项目',{exact:true}).waitFor();await page.locator('.canvas-generation').getByText(/云端建模 32%/).waitFor();
 assert.deepEqual(createdNames,['画布上的江南项目'],'the initial job must receive the entered title');
 assert.equal(await page.locator('.gallery-sidebar .gallery-task-panel').count(),0);assert.equal(await page.locator('.canvas-generation [data-canvas-job]').count(),1);assert.ok(await page.locator('.canvas-task-actions').getByRole('button',{name:'停止后续生成',exact:true}).isVisible());
 await mkdir('artifacts/gallery-feedback',{recursive:true});await page.screenshot({path:'artifacts/gallery-feedback/desktop-progress.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/gallery-feedback/mobile-progress.png',fullPage:true});
 ready=true;await page.waitForFunction(()=>document.querySelector('.generation-job')?.textContent.includes('合集已完成'),{},{timeout:20000});
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'查看旅行合集',exact:true}).click();await page.locator('.exhibit-model[data-preview-mode="3d"]').waitFor();
 const original=fullAssetReads;await page.getByRole('button',{name:'放大查看',exact:true}).click();await page.locator('.piece-main-model[data-preview-mode="3d"]').waitFor();await page.getByRole('button',{name:'返回合集',exact:true}).first().click();await page.locator('.exhibit-model[data-preview-mode="3d"]').waitFor();assert.equal(fullAssetReads,original,'model route changes reuse loaded assets');
 // Collection ID and underlying model job ID differ after regrouping.
 const grouped=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore(),k=(await s.list())[0],b=await s.get(k.id);b.keepsake.tripId='renamed-collection';await s.save(b);s.close();return {id:k.id,job:k.generationId};});
 await page.goto(base+'/collection.html#world/trip/renamed-collection');await page.reload();await page.locator('.exhibit-model[data-preview-mode="3d"]').waitFor();await page.getByRole('button',{name:'编辑合集',exact:true}).click();await page.getByLabel('合集名称',{exact:true}).fill('江南夜游纪念');await page.getByRole('button',{name:'保存合集',exact:true}).click();await page.getByRole('heading',{name:'江南夜游纪念',exact:true}).waitFor();const coverRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/cover'));await page.getByRole('button',{name:'生成旅行合集图',exact:true}).click();const coverBody=(await coverRequest).postDataJSON();assert.equal(coverBody.name,'江南夜游纪念');
 await page.locator('.canvas-generation .canvas-job>p').filter({hasText:'正在生成旅行合集图'}).waitFor();for(let i=0;i<100&&coverCalls===0;i++)await new Promise(r=>setTimeout(r,20));assert.equal(coverCalls,1);coverReady=true;await page.waitForFunction(()=>!document.querySelector('[data-action=cover]'),{},{timeout:20000});assert.equal(coverCalls,1);await page.screenshot({path:'artifacts/gallery-feedback/completed-model.png',fullPage:true});
 // A failed model read must not leave a blank pedestal or an unhandled promise.
 assert.deepEqual(coverNames,['江南夜游纪念']);await page.getByRole('button',{name:'编辑合集',exact:true}).click();await page.getByLabel('合集名称',{exact:true}).fill('我们的江南夜游');await page.getByRole('button',{name:'保存合集',exact:true}).click();await page.getByRole('button',{name:'按新名称重新生成合集图',exact:true}).waitFor();assert.equal(coverCalls,1,'renaming must not automatically charge for a new image');await page.getByRole('button',{name:'按新名称重新生成合集图',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-action=cover]'),{},{timeout:20000});assert.deepEqual(coverNames,['江南夜游纪念','我们的江南夜游']);const coverName=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore();return (await s.getMeta('collection-cover:renamed-collection')).name;});assert.equal(coverName,'我们的江南夜游');
 await page.getByRole('button',{name:'收起制作进度',exact:true}).click();assert.equal(await page.locator('.canvas-generation.is-collapsed').count(),1);assert.equal(await page.locator('.canvas-generation .canvas-job').count(),0);assert.equal(await page.locator('.exhibit-model[data-preview-mode="3d"]').count(),1);await page.screenshot({path:'artifacts/gallery-feedback/collapsed-progress.png',fullPage:true});await page.getByRole('button',{name:'展开制作进度',exact:true}).click();assert.equal(await page.locator('.canvas-generation.is-collapsed').count(),0);assert.ok(await page.locator('.canvas-generation .canvas-job-meter').isVisible());
 let failModelReads=true;await page.route('**/api/library',async route=>{const b=route.request().postDataJSON();if(failModelReads&&b.method==='getMeta'&&b.args[0]?.startsWith('generated-asset:'))await route.fulfill({status:503,json:{error:'模型服务暂时不可用'}});else await route.continue();});await page.reload();await page.getByRole('button',{name:'重新读取模型',exact:true}).waitFor();assert.match(await page.locator('.preview-status').textContent(),/读取失败/);await page.waitForTimeout(500);failModelReads=false;await page.getByRole('button',{name:'重新读取模型',exact:true}).click();await page.locator('.exhibit-model[data-preview-mode="3d"]').waitFor();assert.deepEqual(errors,[]);
 console.log('PASS: server-backed model cache, canvas project/phases/real upstream progress, mobile fit, parent cover routing, completed cover sync, explicit model failure and retry; all generation mocked.');
}catch(error){console.log(JSON.stringify({url:page.url(),errors,body:(await page.locator('body').innerText()).slice(0,5000)}));await page.screenshot({path:'artifacts/gallery-feedback/failure.png',fullPage:true});throw error;}finally{ready=true;coverReady=true;await browser.close();await (await server.resumeCollections()).close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
