// Run with NODE_PATH pointing to an installed Playwright package directory:
// node tests/history.browser.js (requires Chrome; no paid API calls).
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, mkdir } from 'node:fs/promises';
import { createApp } from '../server.js';
import { createDesign } from '../public/src/design.js';
const { chromium }=createRequire(import.meta.url)('playwright');
const server=createApp({key:'',tripoKey:''});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
  const page=await browser.newPage();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const fixture=new URL('../public/assets/chikan-style-sample.png',import.meta.url);
  const image='data:image/png;base64,'+(await readFile(fixture)).toString('base64');
  let task=0;
  await page.route('**/api/**',async route=>{
    const path=new URL(route.request().url()).pathname;
    if(path==='/api/agent')return route.continue();
    const json=path==='/api/config'?{configured:true,tripoConfigured:true}:path==='/api/design'?{design:createDesign({story:'和妈妈旅行'})}:path==='/api/artwork'?{taskId:`test-${++task}`}:{status:'success',image};
    await route.fulfill({json});
  });
  const root=`http://127.0.0.1:${server.address().port}`;
  await page.goto(root);await page.locator('.developer-options summary').click();await page.locator('#sample').click();await page.waitForFunction(()=>!document.getElementById('export').disabled);
  assert.equal(await page.locator('.history-card').count(),0,'fixed sample must not be saved');
  await page.locator('#upload').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:await readFile(fixture)});
  await page.waitForFunction(()=>document.getElementById('photo-status').textContent.includes('已就绪'));
  assert.equal(await page.locator('#photo-card').isVisible(),true,'selected file becomes a single thumbnail');
  assert.equal(await page.locator('#photo-replace').isVisible(),true,'an existing photo can be replaced directly');
  await page.locator('#remove-photo').click();
  assert.equal(await page.locator('#photo-card').isHidden(),true,'corner button removes the photo');
  assert.equal(await page.locator('#photo-prompt').isVisible(),true,'picker returns after removal');
  await page.locator('#upload').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:await readFile(fixture)});
  await page.waitForFunction(()=>document.getElementById('photo-status').textContent.includes('已就绪'));
  await page.locator('#mode').selectOption('tripo');
  await page.locator('#story').fill('和妈妈旅行');await page.locator('#place').fill('广州');
  await page.locator('#generate').click();
  await page.waitForFunction(()=>document.querySelectorAll('.history-card').length===1,{},{timeout:15000});
  await page.locator('#relief-depth').evaluate(el=>{document.getElementById('history-status').textContent='';el.value='24';el.dispatchEvent(new Event('change'));});
  await page.waitForFunction(()=>document.getElementById('history-status').textContent.includes('已保存'));
  await page.reload();await page.locator('.history>summary').click();await page.locator('.history-card').waitFor();
  await page.getByRole('button',{name:'打开作品'}).click();
  await page.waitForFunction(()=>document.getElementById('place').value==='广州');
  assert.equal(await page.locator('#story').inputValue(),'和妈妈旅行');
  assert.equal(await page.locator('#relief-depth').inputValue(),'24');
  assert.equal(await page.locator('#export').isEnabled(),true);
  assert.equal(await page.locator('.history-card').count(),1,'opening must not create a duplicate');
  const download=page.waitForEvent('download');await page.locator('#export').click();
  assert.match((await download).suggestedFilename(),/广州.*\.stl$/);
  await page.locator('#revision').fill('人物更大一些');await page.locator('#revise').click();
  await page.waitForFunction(()=>document.querySelectorAll('.history-card').length===2);
  page.on('dialog',dialog=>dialog.accept());
  await page.getByRole('button',{name:'删除作品',exact:true}).first().click();
  await page.waitForFunction(()=>document.querySelectorAll('.history-card').length===1);
  await page.reload();await page.locator('.history>summary').click();await page.locator('.history-card').waitFor();
  assert.equal(await page.locator('.history-card').count(),1);
  await mkdir('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/history-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'artifacts/history-mobile.png',fullPage:true});
  await page.locator('#upload').setInputFiles({name:'reference.png',mimeType:'image/png',buffer:await readFile(fixture)});
  await page.waitForFunction(()=>document.getElementById('photo-status').textContent.includes('已就绪'));
  await page.locator('.developer-options summary').click();
  await page.locator('#mode').selectOption('local');await page.locator('#generate').click();
  await page.waitForFunction(()=>document.querySelectorAll('.history-card').length===2);
  assert.equal(task,2,'local conversion must not submit a paid task');
  await page.reload();await page.locator('.history>summary').click();await page.getByRole('button',{name:'打开作品'}).first().click();
  await page.waitForFunction(()=>document.getElementById('photo-status').textContent.includes('已恢复'));
  assert.equal(await page.locator('#mode').inputValue(),'local');
  assert.equal(await page.locator('#photo-thumb').isVisible(),true);
  await page.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('Full','QuotaExceededError');};});
  await page.locator('#generate').click();
  await page.waitForFunction(()=>document.getElementById('history-status').textContent.includes('保存失败'));
  assert.equal(await page.locator('#export').isEnabled(),true,'storage failure must leave the generated model exportable');
  assert.equal(await page.locator('.history-card').count(),2);
  assert.deepEqual(errors,[]);
  console.log('History browser checks passed: AI/local save, reload, restore photo and settings, STL, revision, deletion, mobile layout, storage failure.');
} finally {await browser.close();await new Promise(resolve=>server.close(resolve));}
