import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';import {readFile,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const photo=await readFile('public/assets/keepsakes/memory-1.webp'),dir=await mkdtemp(join(tmpdir(),'operator-recovery-'));
let modelCalls=0,artCalls=0,referenceReady=false;const task=data=>Response.json({code:0,data});
const fetchImpl=async(url,o)=>{if(url.includes('deepseek.com'))return Response.json({choices:[{message:{content:JSON.stringify({caption:'纪念作品',reason:'来源照片',brief:{summary:'来源照片中的可见主体',elements:['可见主体'],composition:'单一连接构图',imagePrompt:'按照片可见主体制作纪念作品',decisions:['framing','place','lettering','occlusion'].map(topic=>({topic,evidence:'来源照片',action:'按照片构图',uncertainty:'未知保持未知'}))}})}}]});if(url.endsWith('/files'))return task({file_token:'photo'});if(url.includes('/generation/')){artCalls++;return task({task_id:'reference-1'});}if(url.includes('/tasks/'))return task(referenceReady?{status:'success',progress:100,output:{generated_image_url:'https://cdn.tripo3d.ai/photo.webp'}}:{status:'running',progress:30});if(url.endsWith('photo.webp'))return new Response(photo);if(url.endsWith('/task')){modelCalls++;throw Error('unexpected automatic model generation');}throw Error('unexpected mock request '+url);};
const server=createApp({key:'test',tripoKey:'test',fetchImpl,collectionDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage();await page.goto(base+'/operator.html');await page.getByRole('button',{name:'新建委托',exact:true}).waitFor();
 const ids=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{createCommission,saveCommission}=await import('/src/operator-domain.js');const s=await openKeepsakeStore(),a=await saveCommission(s,createCommission({productType:'magnet',title:'委托A',summary:'依据照片制作'})),b=await saveCommission(s,createCommission({productType:'magnet',title:'委托B',summary:'第二位体验者'}));s.close();const original=window.createImageBitmap;window.createImageBitmap=async(...args)=>{await new Promise(r=>setTimeout(r,500));return original(...args);};return {a:a.id,b:b.id};});
 await page.goto(base+'/operator.html#commission/'+ids.a+'/brief');await page.locator('[name=sourcePhotos]').setInputFiles('public/assets/keepsakes/memory-1.webp');
 await page.evaluate(id=>location.hash='commission/'+id+'/brief',ids.b);await page.waitForTimeout(1200);
 const wrong=await page.evaluate(async id=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),c=await s.getMeta('operator-commission:'+id);s.close();return c.photoIds.length;},ids.b);
 assert.equal(wrong,0,'a late upload from A must never attach to B');
 await page.goto(base+'/operator.html#commission/'+ids.a+'/brief');await page.locator('[name=sourcePhotos]').setInputFiles('public/assets/keepsakes/memory-1.webp');await page.getByText('来源照片已保存，可先整理并确认需求。',{exact:true}).waitFor();
 await page.getByRole('button',{name:'确认需求，去制作',exact:true}).click();await page.getByRole('button',{name:'打开单件创作',exact:true}).click();await page.getByRole('link',{name:'返回委托工作台',exact:true}).waitFor();await page.waitForFunction(()=>document.getElementById('photo-status').textContent.includes('来源照片'));
 assert.equal(await page.locator('#creation-flow').inputValue(),'manual');assert.equal(modelCalls,0);
 await page.locator('#generate').click();await page.waitForFunction(async id=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),c=await s.getMeta('operator-commission:'+id);s.close();return Boolean(c.creationJob?.id);},ids.a,{timeout:5000});
 await page.reload();await page.locator('#resume').waitFor({state:'visible',timeout:8000}).catch(async e=>{console.log('RESTORE DEBUG',await page.evaluate(async id=>{const {loadOperatorCreation}=await import('/src/operator-bridge.js');let info;try{const value=await loadOperatorCreation(id);info={pendingId:value.pendingJob?.id,recordId:value.recordId};}catch(e){info={error:e.message};}return {url:location.href,status:document.getElementById('status').textContent,info};},ids.a));throw e;});referenceReady=true;await page.locator('#resume').click();await page.locator('#build-reference').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('generate').disabled);assert.equal(artCalls,1,'reload resumes paid reference without another submission');
 const result=await page.evaluate(async id=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),c=await s.getMeta('operator-commission:'+id);s.close();return c.selection;},ids.a);
 assert.ok(result,'reference must return to the same commission before 3D');assert.equal(modelCalls,0);
 await page.getByRole('link',{name:'返回委托工作台',exact:true}).click();await page.getByRole('button',{name:'经营备份',exact:true}).waitFor();
 const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'经营备份',exact:true}).click();const backup=await readFile(await (await waiting).path());
 const other=await browser.newContext(),restored=await other.newPage();await restored.goto(base+'/operator.html');await restored.locator('[name=operatorBackup]').setInputFiles({name:'经营备份.zip',mimeType:'application/zip',buffer:backup});await restored.getByText('经营备份已恢复。',{exact:true}).waitFor();
 const count=await restored.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{listCommissions}=await import('/src/operator-domain.js');const s=await openKeepsakeStore(),all=await listCommissions(s),c=all.find(c=>c.title==='委托A');const photo=await s.getPhoto(c.photoIds[0]),k=await s.get(c.selection.id);s.close();return {count:all.length,photo:Boolean(photo),work:Boolean(k)};});
 assert.equal(count.count,2);assert.ok(count.photo&&count.work);await other.close();console.log('PASS: upload ownership, real creator reference roundtrip, manual generation, image-stage backup and clean-context restore; mocks only.');
}finally{await browser.close();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
