import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';

const dir=await mkdtemp(join(tmpdir(),'operator-workbench-'));
const server=createApp({accountsEnabled:true,serverLibrary:true,accountDir:dir,libraryDir:join(dir,'library')});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({channel:'chrome',headless:true});
await mkdir('artifacts/operator-workbench',{recursive:true});
try {
 const opContext=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
 const userContext=await browser.newContext({viewport:{width:1280,height:900}});
 const post=async(ctx,path,data)=>{const r=await ctx.request.post(base+path,{headers:{Origin:base},data});assert.ok(r.ok(),await r.text());return r.json();};
 await post(opContext,'/api/auth/setup',{username:'studio',password:'safe-password',name:'经营者'});
 await post(userContext,'/api/auth/register',{username:'visitor',password:'safe-password',name:'小林'});
 const image='data:image/webp;base64,'+(await readFile('public/assets/keepsakes/memory-1.webp')).toString('base64');
 const order=await post(userContext,'/api/orders',{title:'我的旅行合集',raw:'保留旅行中的人物与城市景色，人物更突出，底座简洁。',place:'广州',productType:'figurine',deliveryType:'image',photos:[{image}],inputReference:{image}});
 for(const title of ['苏州亲子纪念','杭州毕业旅行','广州城市摆件','大理旅行冰箱贴'])await post(userContext,'/api/orders',{title,raw:'保留旅行故事',productType:'figurine',deliveryType:'image',photos:[{image}]});
 const op=await opContext.newPage(),user=await userContext.newPage(),errors=[],libraryCalls=[];
 op.on('request',r=>{if(r.url()===base+'/api/library'&&r.method()==='POST')libraryCalls.push(r.postDataJSON().method);});
 for(const page of [op,user]){page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));}
 await op.goto(base+'/operator.html#commission/'+order.id+'/make');
 await op.locator('.list-row').first().waitFor();assert.ok(!libraryCalls.includes('dump'),'opening the workbench must not download the full library');
 await user.goto(base+'/orders.html#'+order.id);
 // A delayed response must not erase a newer draft after switching orders.
 let release,received;const pending=new Promise(r=>release=r),requestSeen=new Promise(r=>received=r);
 await op.route('**/api/orders/*/messages',async route=>{const response=await route.fetch();received();await pending;await route.fulfill({response});});
 await op.locator('[name=chatText]').fill('我正在查看你的旅行素材。');await op.getByRole('button',{name:'发送',exact:true}).click();await requestSeen;
 await op.locator('.list-row').filter({hasText:'苏州亲子纪念'}).click();await op.locator('.order-name h1').filter({hasText:'苏州亲子纪念'}).waitFor();
 await op.locator('.list-row').filter({hasText:'我的旅行合集'}).click();await op.locator('.order-name h1').filter({hasText:'我的旅行合集'}).waitFor();
 await op.locator('[name=chatText]').fill('这是一条尚未发送的新草稿');release();await op.waitForFunction(()=>document.querySelector('[name=chatText]')?.textContent==='这是一条尚未发送的新草稿');
 assert.equal(await op.locator('[name=chatText]').inputValue(),'这是一条尚未发送的新草稿');await op.unroute('**/api/orders/*/messages');await op.locator('[name=chatText]').fill('');
 await user.locator('[name=chatText]').fill('人物可以突出一些，保留旅行的感觉。');
 await user.getByRole('button',{name:'发送',exact:true}).click();
 await op.getByText('人物可以突出一些，保留旅行的感觉。',{exact:true}).waitFor();
 await user.locator('[name=chatText]').fill('可以，底座尽量简洁。');
 await op.locator('[name=chatText]').fill('收到，我会缩小背景建筑，保留城市特色。');
 await op.getByRole('button',{name:'发送',exact:true}).click();
 await user.getByText('收到，我会缩小背景建筑，保留城市特色。',{exact:true}).waitFor();
 assert.equal(await user.locator('[name=chatText]').inputValue(),'可以，底座尽量简洁。','polling preserves drafts');
 await user.getByRole('button',{name:'发送',exact:true}).click();
 await op.getByRole('button',{name:'接受需求，开始制作',exact:true}).click();
 await op.getByRole('button',{name:'采用用户提交的作品',exact:true}).click();
 await op.getByRole('button',{name:'发送方案给用户',exact:true}).waitFor();
 await op.getByText('可以，底座尽量简洁。',{exact:true}).waitFor();
 await op.getByRole('button',{name:'放大预览',exact:true}).click();assert.equal(await op.locator('[data-view-zoom=reset]').textContent(),'110%');await op.getByRole('button',{name:'重置预览缩放',exact:true}).click();
 const layout=await op.evaluate(()=>({height:innerHeight,document:document.documentElement.scrollHeight,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,send:document.querySelector('.chat-send').getBoundingClientRect().bottom,action:document.querySelector('[data-action=confirm-reference]').getBoundingClientRect().bottom,preview:document.querySelector('#work-view').getBoundingClientRect().height}));
 assert.ok(layout.document<=layout.height+1,JSON.stringify(layout));assert.ok(layout.scrollWidth<=layout.width,JSON.stringify(layout));assert.ok(layout.send<=layout.height&&layout.action<=layout.height,JSON.stringify(layout));assert.ok(layout.preview>200);
 await op.waitForFunction(()=>!document.getElementById('operator-status').textContent);
 await op.screenshot({path:'artifacts/operator-workbench/desktop.png'});
 await op.getByRole('button',{name:'发送方案给用户',exact:true}).click();
 let shared=await(await opContext.request.get(base+'/api/orders/'+order.id)).json();assert.equal(shared.commission.userConfirmedAt,null);assert.equal(shared.status,'awaiting_proposal');
 await user.getByRole('button',{name:'确认方案，继续制作',exact:true}).click();
 await op.getByRole('button',{name:'提交审核',exact:true}).waitFor();
 await op.getByRole('button',{name:'提交审核',exact:true}).click();
 await op.locator('[name=reviewNote]').fill('人物、背景与用户确认的方案一致。');
 await op.getByRole('button',{name:'审核通过，去交付',exact:true}).click();
 await user.getByRole('button',{name:'确认这版作品',exact:true}).click();
 await op.getByText('当前：用户已确认',{exact:true}).waitFor();
 const downloaded=op.waitForEvent('download');await op.getByRole('button',{name:'导出交付包',exact:true}).click();await downloaded;
 await op.getByText('本订单的交付包已导出；尚未自动记录实际交付。',{exact:true}).waitFor();
 await op.locator('[name=deliveryMethod]').fill('用户在订单中领取数字图像');
 await op.getByRole('button',{name:'记录实际交付',exact:true}).click();
 await user.getByText('经营者已记录交付，交付文件仍可在本页领取。',{exact:true}).waitFor();
 await user.locator('[name=chatImage]').setInputFiles('public/assets/keepsakes/memory-2.webp');
 await user.locator('.chat-attachment:not([hidden])').waitFor();await user.getByRole('button',{name:'发送',exact:true}).click();
 await op.locator('.chat-bubble img').waitFor();
 await op.reload();await op.locator('.chat-bubble img').waitFor();assert.equal(await op.getByText('可以，底座尽量简洁。',{exact:true}).count(),1);
 await op.getByRole('button',{name:'方案预览',exact:true}).click();
 await op.setViewportSize({width:1366,height:768});
 assert.ok(await op.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));
 await op.screenshot({path:'artifacts/operator-workbench/laptop.png'});
 await op.setViewportSize({width:390,height:844});await user.setViewportSize({width:390,height:844});
 assert.ok(await op.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await user.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await op.screenshot({path:'artifacts/operator-workbench/mobile.png',fullPage:true});await user.screenshot({path:'artifacts/operator-workbench/customer-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: single-screen desktop, preserved chat drafts, real bidirectional text/images, customer-owned proposal confirmation, review, final confirmation, export, delivery, persisted messages, mobile; no AI calls.');
}finally{
 await browser.close();await new Promise(r=>server.close(r));
 if(!resolve(dir).startsWith(resolve(tmpdir())+sep))throw Error('Unexpected test directory');
 await rm(dir,{recursive:true,force:true});
}
