import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';import {readFile} from 'node:fs/promises';
const server=createApp();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true}),photo=await readFile('public/assets/keepsakes/memory-1.webp');
try{
 const context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();await a.goto(base+'/operator.html');await a.getByRole('button',{name:'新建委托',exact:true}).waitFor();
 const ids=await a.evaluate(async image=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{createCommission,saveCommission,confirmBrief,attachSelection,reviewCommission}=await import('/src/operator-domain.js');const s=await openKeepsakeStore(),blob=new Blob([Uint8Array.from(atob(image),c=>c.charCodeAt(0))],{type:'image/webp'});await s.save({keepsake:{id:'library-work',schemaVersion:1,title:'选择用作品',city:'广州',kind:'miniature',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'generated:adversarial-work-0001:0',generationId:'adversarial-work-0001',assetIndex:0,memoryIds:[],createdAt:1,updatedAt:1},memories:[],photos:[]});await s.setMeta('generated-asset:adversarial-work-0001:0',{glb:null,reference:blob,report:{checks:[],note:'数字图像'},preview:null});const make=async title=>{let c=createCommission({productType:'magnet',title,summary:'选定的数字作品',deliveryType:'image',selection:{id:'library-work',revision:1}});c=confirmBrief(c);c=attachSelection(c,{id:'library-work',revision:1});c=reviewCommission(c,{accepted:true,note:'已核对'});return saveCommission(s,c);};const A=await make('委托A'),B=await make('委托B'),C=await saveCommission(s,createCommission({productType:'magnet',title:'委托C',summary:'选择素材'})),D=await saveCommission(s,createCommission({productType:'magnet',title:'委托D',summary:'另一位'}));s.close();return {A:A.id,B:B.id,C:C.id,D:D.id};},photo.toString('base64'));
 await a.goto(base+'/operator.html#commission/'+ids.C+'/brief');await a.getByRole('button',{name:'选择已有作品',exact:true}).click();await a.getByRole('button',{name:'选择这件作品',exact:true}).waitFor();
 await b.goto(base+'/operator.html#commission/'+ids.D+'/brief');await b.getByRole('button',{name:'选择已有作品',exact:true}).click();await b.getByRole('button',{name:'选择这件作品',exact:true}).waitFor();
 await a.getByRole('button',{name:'选择这件作品',exact:true}).click();await a.locator('[name=summary]').waitFor();
 const library=await a.evaluate(async ids=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore();const c=await s.getMeta('operator-commission:'+ids.C),d=await s.getMeta('operator-commission:'+ids.D);s.close();return {c:c.selection,d:d.selection};},ids);assert.ok(library.c);assert.equal(library.d,null);
 await a.goto(base+'/operator.html#commission/'+ids.A+'/delivery');await a.getByRole('button',{name:'导出交付包',exact:true}).waitFor();
 await a.evaluate(()=>{const original=window.matchMedia;window.matchMedia=q=>q==='(pointer:coarse)'?{matches:true}:original(q);navigator.canShare=()=>true;navigator.share=async()=>{window.sharing=true;await new Promise(r=>window.finishShare=r);};});
 await a.getByRole('button',{name:'导出交付包',exact:true}).click();await a.waitForFunction(()=>window.sharing);await a.evaluate(id=>location.hash='commission/'+id+'/delivery',ids.B);await a.waitForTimeout(150);await a.evaluate(()=>window.finishShare());await a.getByText('本委托的交付包已导出；尚未自动记录实际交付。',{exact:true}).waitFor();
 const read=async()=>a.evaluate(async ids=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore(),A=await s.getMeta('operator-commission:'+ids.A),B=await s.getMeta('operator-commission:'+ids.B);s.close();return {a:A.exports.length,b:B.exports.length};},ids);
 assert.deepEqual(await read(),{a:1,b:0});
 await a.evaluate(()=>navigator.share=async()=>{throw new DOMException('cancel','AbortError');});await a.getByRole('button',{name:'导出交付包',exact:true}).click();await a.getByText('分享已取消，本次未记录已导出。',{exact:true}).waitFor();assert.deepEqual(await read(),{a:1,b:0});
 const late=await a.evaluate(async image=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{createCommission,saveCommission,confirmBrief,reviseCommission}=await import('/src/operator-domain.js'),{attachOperatorArtwork}=await import('/src/operator-bridge.js');const s=await openKeepsakeStore(),blob=new Blob([Uint8Array.from(atob(image),c=>c.charCodeAt(0))],{type:'image/webp'});await s.save({keepsake:{id:'late-source',schemaVersion:1,title:'原始素材',city:'广州',kind:'miniature',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'pending',memoryIds:['late-memory'],createdAt:1,updatedAt:1},memories:[{id:'late-memory',keepsakeId:'late-source',authorId:'me',date:'',placeName:'广州',story:'旧故事',photoIds:['late-photo']}],photos:[{id:'late-photo',blob}]});let c=await saveCommission(s,confirmBrief(createCommission({productType:'magnet',title:'旧版本',summary:'旧故事',photoIds:['late-photo'],place:'广州'})));const record={id:crypto.randomUUID(),operatorId:c.id,operatorBriefVersion:c.briefVersion,operatorSourcePhotoId:'late-photo',operatorTitle:'旧版本',createdAt:1,phase:'reference',image:'data:image/webp;base64,'+image,photo:'data:image/webp;base64,'+image,design:{caption:'旧结果'},input:{place:'广州',story:'旧故事',date:''}};await saveCommission(s,reviseCommission(c,{place:'杭州',summary:'新故事'}));s.close();await attachOperatorArtwork(record);const t=await openKeepsakeStore(),k=await t.get('operator-work-'+record.id),now=await t.getMeta('operator-commission:'+c.id);t.close();return {city:k.keepsake.city,story:k.memories[0].story,selection:now.selection};},photo.toString('base64'));
 assert.equal(late.city,'广州');assert.equal(late.story,'旧故事');assert.equal(late.selection,null);
 const failure=await a.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{createCommission,confirmBrief,saveCommission}=await import('/src/operator-domain.js'),{recordOperatorJob,finishOperatorJob}=await import('/src/operator-bridge.js');const s=await openKeepsakeStore(),c=await saveCommission(s,confirmBrief(createCommission({productType:'magnet',title:'失败后可重试',summary:'照片创作',photoIds:['late-photo']})));s.close();const job={id:'failed-paid-task',context:{operatorId:c.id,operatorBriefVersion:c.briefVersion}};await recordOperatorJob(job);await finishOperatorJob(job,'云端明确失败');const t=await openKeepsakeStore(),value=await t.getMeta('operator-commission:'+c.id);t.close();return {pending:value.creationJob,status:value.status,error:value.lastCreationError};});
 assert.equal(failure.pending,null);assert.equal(failure.status,'make');assert.match(failure.error,/失败/);
 console.log('PASS: per-tab library ownership, delayed export ownership, cancelled sharing not exported, late creator source facts retained; no paid calls.');await context.close();
}finally{await browser.close();await new Promise(r=>server.close(r));}
