import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createAccountWorkspace} from '../account-workspace.js';

test('order conversation persists private messages and only the customer confirms the current proposal',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'order-conversation-'));
 try {
  let w=await createAccountWorkspace(dir);
  const op=await w.register({username:'studio',password:'safe-password'},{operator:true});
  const user=await w.register({username:'visitor',password:'safe-password'});
  const other=await w.register({username:'outsider',password:'safe-password'});
  const image='data:image/png;base64,iVBORw0KGgo=';
  let o=await w.createOrder(user,{title:'旅行纪念',raw:'保留夜景',productType:'figurine',deliveryType:'image',photos:[{image}]});
  await w.sendMessage(user,o.id,{clientId:'message-1',text:'人物突出一些',image:{image}});
  await w.sendMessage(user,o.id,{clientId:'message-1',text:'人物突出一些',image:{image}});
  await w.sendMessage(op,o.id,{clientId:'message-2',text:'收到，我来调整'});
  await assert.rejects(w.sendMessage(other,o.id,{clientId:'message-3',text:'其他用户'}),/权限/);
  await assert.rejects(w.sendMessage(user,o.id,{clientId:'message-4',text:''}),/消息/);
  o=await w.getOrder(op,o.id);
  assert.equal(o.messages.length,2);
  assert.equal(o.messages[0].role,'user');
  assert.equal(o.messages[1].role,'operator');
  const attachment=o.messages[0].file;
  await assert.rejects(w.getFile(other,o.id,attachment.id),/权限/);
  assert.ok((await w.getFile(user,o.id,attachment.id)).bytes.length);
  o=await w.updateOrder(op,o.id,{revision:o.revision,action:'accept'});
  o=await w.putResult(op,o.id,{revision:o.revision,reference:{image},work:{id:'reference-one',revision:1,title:'方案一'}});
  const forged=await w.putCommission(op,o.id,{...o.commission,userConfirmedAt:Date.now()});
  assert.equal(forged.userConfirmedAt,null,'operator cannot forge customer confirmation');
  o=await w.updateOrder(op,o.id,{revision:forged.revision,action:'publish-proposal'});
  assert.equal(o.status,'awaiting_proposal');
  assert.equal(o.commission.userConfirmedAt,null);
  let customer=await w.getOrder(user,o.id);
  assert.equal(customer.proposal.status,'pending');
  assert.ok((await w.getFile(user,o.id,customer.proposal.reference.id)).bytes.length);
  assert.equal(customer.result,null,'unreviewed production result stays private');
  await assert.rejects(w.updateOrder(op,o.id,{revision:o.revision,action:'confirm-proposal'}),/权限/);
  await w.updateOrder(user,o.id,{revision:o.revision,action:'confirm-proposal'});
  o=await w.getOrder(op,o.id);
  assert.ok(o.commission.userConfirmedAt);
  assert.equal(o.proposal.status,'confirmed');
  o=await w.putResult(op,o.id,{revision:o.revision,reference:{image},work:{id:'reference-two',revision:1,title:'方案二'}});
  assert.equal(o.commission.userConfirmedAt,null);
  await assert.rejects(w.updateOrder(user,o.id,{revision:o.revision,action:'confirm-proposal'}),/方案/);
  o=await w.updateOrder(op,o.id,{revision:o.revision,action:'publish-proposal'});
  await w.updateOrder(user,o.id,{revision:o.revision,action:'revise',note:'底座更简洁'});
  o=await w.getOrder(op,o.id);
  assert.equal(o.proposal.status,'superseded');
  assert.equal(o.commission.userConfirmedAt,null);
  w=await createAccountWorkspace(dir);
  customer=await w.getOrder(user,o.id);
  assert.ok(customer.messages.some(m=>m.text==='收到，我来调整'));
  assert.ok(customer.messages.some(m=>m.text.includes('底座更简洁')));
  assert.equal(customer.commission,undefined);
  const saved=JSON.parse(await readFile(join(dir,'workspace.json'),'utf8'));
  saved.orders[0].commission.userConfirmedAt=Date.now();delete saved.orders[0].proposal;
  await writeFile(join(dir,'workspace.json'),JSON.stringify(saved));
  w=await createAccountWorkspace(dir);
  assert.equal((await w.getOrder(op,o.id)).commission.userConfirmedAt,null,'legacy operator-entered confirmations are not customer consent');
 } finally {await rm(dir,{recursive:true,force:true});}
});
