import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';
const server=createApp({key:'',tripoKey:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage();await page.goto(base+'/collection.html?legacy=1');await page.locator('.map-viewport').waitFor();
 const collision=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');const s=await openKeepsakeStore();const k=id=>({id,schemaVersion:1,title:id,city:'广州',kind:'magnet',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'gz',memoryIds:[id+'-m'],dateStart:'2026-10-05',dateEnd:'2026-10-05',createdAt:1,updatedAt:1,origin:'user'}),m=id=>({id:id+'-m',keepsakeId:id,authorId:'me',date:'2026-10-05',placeName:'广州',story:id,photoIds:['same-photo']});await s.save({keepsake:k('existing'),memories:[m('existing')],photos:[{id:'same-photo',blob:new Blob(['ORIGINAL'],{type:'image/jpeg'})}]});let rejected=false;try{await s.restore({keepsakes:[k('incoming')],memories:[m('incoming')],photos:[{id:'same-photo',blob:new Blob(['REPLACED'],{type:'image/jpeg'})}],requests:[]});}catch{rejected=true;}return {rejected,photo:await (await s.getPhoto('same-photo')).text(),incoming:await s.get('incoming')};});
 assert.equal(collision.rejected,true,'photo ID conflicts must reject before overwriting');assert.equal(collision.photo,'ORIGINAL');assert.equal(collision.incoming,null,'failed restore is atomic');
 await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore();await s.deleteKeepsake('existing');for(let i=0;i<30;i++)await s.save({keepsake:{id:'trip-'+i,schemaVersion:1,title:'广州第'+i+'次旅行',city:'广州',kind:'magnet',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'gz',memoryIds:[],dateStart:'2026-10-05',dateEnd:'2026-10-05',createdAt:i,updatedAt:i,origin:'user'},memories:[],photos:[]});});await page.reload();await page.locator('.wall-magnet').waitFor();assert.equal(await page.locator('.wall-magnet').count(),1);await page.locator('.wall-magnet').click();assert.equal(await page.locator('.city-works button').count(),30);await page.keyboard.press('Escape');
 await page.setViewportSize({width:360,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.goto(base+'/collection.html?legacy=1');await page.locator('.map-viewport').waitFor();await page.getByRole('button',{name:'创作纪念品',exact:true}).click();await page.locator('[name=title]').fill('个人的广州');await page.getByRole('button',{name:'创建这件纪念品',exact:true}).click();await page.waitForFunction(()=>location.hash.includes('/item/'));await page.getByRole('button',{name:'翻开这枚冰箱贴的回忆',exact:true}).click();await page.getByRole('button',{name:'添加我的回忆',exact:true}).click();await page.locator('[name=story]').fill('纯文字也可以保存');await page.getByRole('button',{name:'保存这段回忆',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.memory-story')?.textContent.includes('纯文字'));await page.reload();await page.locator('.memory-book').waitFor();assert.match(await page.locator('.memory-story').textContent(),/纯文字/);
 console.log('PASS: atomic conflicting backup, 30 same-city works, 360px viewport, create own work, text-only memories and reload.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
