import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';
const server=createApp({key:'',tripoKey:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage();await page.goto(base+'/collection.html?legacy=1');await page.locator('.map-viewport').waitFor();
 const race=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore();const k={id:'stale',schemaVersion:1,title:'两页签',city:'广州',kind:'magnet',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'gz',memoryIds:[],dateStart:'2026-10-05',dateEnd:'2026-10-05',createdAt:1,updatedAt:1,origin:'user'};await s.save({keepsake:k,memories:[],photos:[]});const a=structuredClone((await s.get('stale')).keepsake),b=structuredClone(a),m=id=>({id,keepsakeId:'stale',authorId:'me',story:id,photoIds:[],date:'2026-10-05',placeName:'广州'});b.memoryIds=['b'];await s.save({keepsake:b,memories:[m('b')],photos:[]});a.memoryIds=['a'];let rejected=false;try{await s.save({keepsake:a,memories:[m('a')],photos:[]});}catch{rejected=true;}return {rejected,memories:(await s.get('stale')).memories.map(m=>m.id)};});assert.equal(race.rejected,true);assert.deepEqual(race.memories,['b']);
 await page.getByRole('button',{name:'浏览示例作品',exact:true}).first().click();await page.locator('.wall-magnet[data-city="广州"]').click();await page.getByRole('button',{name:'翻开这枚冰箱贴的回忆',exact:true}).click();await page.getByRole('button',{name:'编辑这段回忆',exact:true}).click();await page.locator('[name=story]').fill('编辑转存后的第一页');await page.getByRole('button',{name:'保存这段回忆',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.memory-story')?.textContent.includes('转存'));assert.match(await page.locator('.page-count').textContent(),/01 \/ 03/);
 await page.getByRole('button',{name:'添加我的回忆',exact:true}).click();await page.locator('[name=story]').fill('照片上传后保存');await page.locator('[name=photo]').setInputFiles('public/assets/keepsakes/memory-1.webp');await page.locator('[data-uploaded-photo]').waitFor();assert.equal(await page.getByRole('button',{name:'保存这段回忆',exact:true}).isEnabled(),true);await page.getByRole('button',{name:'保存这段回忆',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.memory-story')?.textContent.includes('上传'));await page.keyboard.press('Escape');
 await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore();const k={id:'future',schemaVersion:1,title:'未知模型的回忆',city:'广州',kind:'magnet',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'future-model',memoryIds:['future-m'],dateStart:'2026-10-05',dateEnd:'2026-10-05',createdAt:1,updatedAt:1,origin:'user'};await s.save({keepsake:k,memories:[{id:'future-m',keepsakeId:'future',authorId:'me',story:'模型丢了，故事还在',date:'2026-10-05',placeName:'广州',photoIds:[]}],photos:[]});});await page.goto(base+'/collection.html?legacy=1#collection/item/future');await page.locator('.model-fallback').waitFor();await page.getByRole('button',{name:'翻开这枚冰箱贴的回忆',exact:true}).click();await page.locator('.memory-book').waitFor();assert.match(await page.locator('.memory-story').textContent(),/故事还在/);await page.keyboard.press('Escape');
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.get;IDBObjectStore.prototype.get=function(key){if(key==='future'){const until=performance.now()+70;while(performance.now()<until){}}return original.call(this,key);};location.hash='collection/item/stale';setTimeout(()=>location.hash='collection/map',0);});await page.waitForFunction(()=>location.hash==='#collection/map'&&!!document.querySelector('.map-viewport'));assert.equal(await page.locator('#model-canvas').count(),0);
 console.log('PASS: stale saves rejected, migrated demo edit keeps 3 pages, upload unlocks, unknown model memories preserved, latest route wins.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
