import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import {createApp} from '../server.js';
import {initialState} from '../public/src/travel-state.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';
import {getExplorationLandmarks} from '../public/src/travel-map-exploration.js';

// Browser fixtures exercise the SDK contract without using a real key or making provider calls.
import {sdkSource} from './fixtures/amap-sdk.js';
const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州三天，每天4小时',patch:{destination:'广州',dayCount:3,dailyHours:4}}).profile;
const base={...planFromCatalog(normalizeRequest({description:'广州一天',hours:8}),undefined,{placeIds:['gz-museum','gz-square','gz-tower','gz-opera']}),mode:'demo',trace:[]};
const daily=buildDailyPlan({...base,stops:base.stops.map((stop,index)=>({...stop,dayIndex:index<3?1:2}))},profile);
const signatureCount=daily.stops.length+getExplorationLandmarks('广州',{acceptedStops:daily.stops}).length;
const detailedCount=daily.stops.length+getExplorationLandmarks('广州',{acceptedStops:daily.stops,density:'detailed'}).length;
const saved=JSON.stringify({...initialState(),profile,plan:daily});
const server=createApp({key:'',tripoKey:'',accountsEnabled:false,amapJsKey:'public-fixture-key',amapSecurityJsCode:'private-fixture-code',fetchImpl:async()=>{throw new Error('Fixture forbids all external API calls');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const root=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[];
async function newPage({disabled=false,failSdk=false,failMap=false,mapDelay=5,neverComplete=false,seed=true,fixtures={},savedState=saved}={}){
  const page=await browser.newPage({viewport:{width:1500,height:1000},reducedMotion:'reduce'});page.on('pageerror',error=>errors.push(error.message));
  await page.addInitScript(({saved,seed,failMap,mapDelay,neverComplete,fixtures})=>{window.mock={maps:[],searches:[],poiResults:[],routes:[],fits:[],centers:[],drags:[],pitches:[],rotations:[],offsets:[],projections:[],clustered:false,removes:0,clears:0,destroys:0,mapFailures:failMap?1:0,mapDelay,neverComplete,fixtures,failRoutes:false,routeDelay:5,holdRoutes:false,pendingRoutes:[]};if(seed&&!sessionStorage.getItem('map-browser-fixture-seeded')){localStorage.setItem('lvzang.v1',saved);sessionStorage.setItem('map-browser-fixture-seeded','1');}},{saved:savedState,seed,failMap,mapDelay,neverComplete,fixtures});
  // Every provider request except the synthetic SDK is blocked before leaving the browser.
  await page.route('**/*',route=>route.request().url().startsWith(root+'/')?route.continue():route.abort());
  if(disabled)await page.route('**/api/map/config',route=>route.fulfill({json:{provider:'amap',enabled:false,reason:'not-configured'}}));
  let loads=0;await page.route('https://webapi.amap.com/maps?**',route=>{loads++;if(failSdk&&loads===1)return route.abort();return route.fulfill({contentType:'application/javascript',body:sdkSource});});
  await page.goto(root+'/travel.html');return {page,loads:()=>loads};
}
const waitReady=page=>page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='ready');
const comparisonRoutes=page=>page.locator('.fixture-route[data-color="#176b62"]');
const markerFor=(page,id)=>page.locator('.map-marker[data-stop="'+id+'"]');
const waitJourney=page=>page.waitForFunction(()=>/高德(?:步行|驾车)约/.test(document.getElementById('map-journey-result').textContent));
const waitClearJourney=page=>page.waitForFunction(()=>document.getElementById('map-journey-result').textContent.includes('点击建筑选择起点'));
const markerNames=page=>page.locator('.map-marker .landmark-name').allTextContents();
const flushLayout=page=>page.evaluate(async()=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});
const sdkBackgroundPoint=page=>page.locator('#amap-viewport').evaluate(node=>{const bounds=node.getBoundingClientRect();for(const fy of [.85,.55,.35,.7,.9])for(const fx of [.08,.9,.2,.4,.6,.8]){const x=bounds.x+bounds.width*fx,y=bounds.y+bounds.height*fy,target=document.elementFromPoint(x,y);if(target&&node.contains(target)&&!target.closest('.map-marker,button,.amap-copyright,.fixture-scale'))return {x,y,dx:Math.min(64,bounds.width*.18),dy:Math.min(24,bounds.height*.08)};}throw new Error('No visible SDK background is available for the gesture assertion');});
async function assertMapPan(page,label,{touch=false}={}){
  await page.locator('#amap-viewport').scrollIntoViewIfNeeded();await flushLayout(page);
  const snapshot=()=>page.evaluate(()=>{const map=window.mock.maps.at(-1),marker=map.overlays.find(item=>item.kind==='marker'),point=map.lngLatToContainer(marker.position),node=document.getElementById('map-node'),world=document.getElementById('canvas-world');return {center:[...map.getCenter()],projection:[point.getX(),point.getY()],world:{inline:world.style.transform,computed:getComputedStyle(world).transform,scale:document.getElementById('zoom-value').textContent},node:[node.dataset.x,node.dataset.y]};});
  const before=await snapshot(),point=await sdkBackgroundPoint(page);
  if(touch){const session=await page.context().newCDPSession(page);try{await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:point.x,y:point.y,id:1}]});for(let step=1;step<=6;step++)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x+point.dx*step/6,y:point.y+point.dy*step/6,id:1}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}finally{await session.detach();}}
  else{await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+point.dx,point.y+point.dy,{steps:6});await page.mouse.up();}
  await flushLayout(page);const after=await snapshot();assert.notDeepEqual(after.center,before.center,label+': dragging the SDK background changes its geographic center');assert.ok(Math.hypot(after.projection[0]-before.projection[0],after.projection[1]-before.projection[1])>8,label+': the same provider POI projects to a different screen position');assert.deepEqual(after.world,before.world,label+': map dragging does not move or scale the workspace');assert.deepEqual(after.node,before.node,label+': map dragging does not move the workspace map card');
}
async function assertDenseMobileGeography(page){
  await page.setViewportSize({width:390,height:844});await page.locator('#amap-viewport').scrollIntoViewIfNeeded();await flushLayout(page);
  const initial=await page.evaluate(()=>window.mock.maps.at(-1).overlays.filter(item=>item.kind==='marker').map(marker=>({id:marker.content.dataset.stop,position:[...marker.position],offset:[marker.getOffset().x,marker.getOffset().y]})));
  assert.equal(initial.length,signatureCount,'signature landmarks remain available on a narrow map');
  assert.ok(initial.every(marker=>Math.hypot(...marker.offset)<=36.001),'signature display offsets stay within 36px of provider coordinates even when crowded');
  assert.equal(await page.locator('.map-marker').evaluateAll(nodes=>nodes.every(node=>node.tagName==='BUTTON'&&node.getAttribute('aria-label')&&node.tabIndex>=0)),true,'dense landmarks remain individually keyboard accessible');
  await page.getByLabel('地标密度',{exact:true}).selectOption('detailed');await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===26);await flushLayout(page);
  const dense=await page.evaluate(()=>window.mock.maps.at(-1).overlays.filter(item=>item.kind==='marker').map(marker=>({position:[...marker.position],offset:[marker.getOffset().x,marker.getOffset().y]})));
  for(const id of ['gz-ctf','gz-youth-palace']){assert.equal(await markerFor(page,id).getAttribute('data-landmark-kind'),id,'detailed buildings retain their distinct miniature geometry');}
  assert.equal(dense.length,detailedCount);assert.ok(dense.every(marker=>marker.offset.every(value=>value===0)),'detailed discovery uses exact provider anchors, not city-wide packing');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'dense discovery does not overflow the document');
  await page.getByLabel('地标密度',{exact:true}).selectOption('signature');await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12);
  await page.evaluate(()=>{window.mock.clustered=false;});await page.setViewportSize({width:1500,height:1000});await page.locator('#map-fit').click();await flushLayout(page);
}
async function assertLateExplorationPreservesWheelZoom(){
  const {page}=await newPage({fixtures:{'广州|广州图书馆':{delay:6500}}});
  try{
    await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===11);assert.equal(await markerFor(page,'gz-library').count(),0);await page.locator('#amap-viewport').scrollIntoViewIfNeeded();await flushLayout(page);
    const point=await sdkBackgroundPoint(page),beforeZoom=await page.evaluate(()=>window.mock.maps.at(-1).getZoom());await page.mouse.move(point.x,point.y);await page.mouse.wheel(0,-160);await flushLayout(page);assert.equal(await page.evaluate(()=>window.mock.maps.at(-1).getZoom()),beforeZoom+1,'native SDK background wheel zoom changes the map zoom');
    const camera=()=>page.evaluate(()=>({center:[...window.mock.maps.at(-1).getCenter()],zoom:window.mock.maps.at(-1).getZoom(),fits:window.mock.fits.length})),chosen=await camera();await markerFor(page,'gz-library').waitFor({state:'attached'});await flushLayout(page);assert.deepEqual(await camera(),chosen,'a late exploration POI never resets native wheel zoom or refits its camera');assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'native map zoom and late POI results preserve the accepted trip');
  }finally{await page.close();}
}
async function assertMapComparisonNeverEditsItinerary(){
  const {page}=await newPage();
  try{
    await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12&&document.querySelectorAll('.fixture-route').length===2);
    const itinerary=()=>page.evaluate(()=>({
      saved:localStorage.getItem('lvzang.v1'),
      day:document.querySelector('#day-selector [aria-pressed="true"]')?.dataset.day,
      time:document.getElementById('time-detail').textContent,
      stops:[...document.querySelectorAll('[data-stop-card]')].map(node=>({id:node.dataset.stopCard,name:node.querySelector('h3')?.textContent,time:node.querySelector('.stop-time')?.textContent,selected:node.classList.contains('selected')})),
    }));
    const original=await itinerary();
    const unchanged=async action=>assert.deepEqual(await itinerary(),original,action+' must not edit storage, day, itinerary content or selected cards');
    assert.match(await page.locator('#map-comparison-note').textContent(),/点击建筑只查看和比较路程.*加入或移出行程.*对应按钮/);
    await markerFor(page,'gz-museum').click();
    assert.match(await page.locator('#map-place-day').textContent(),/已在行程/);
    assert.equal(await markerFor(page,'gz-museum').evaluate(node=>node===document.activeElement),true,'clicking an accepted building keeps keyboard focus in the map');
    await unchanged('an accepted origin');
    await markerFor(page,'gz-square').click();await waitJourney(page);await unchanged('an accepted destination');
    await page.locator('#map-fit').click();await markerFor(page,'gz-library').click();await waitJourney(page);
    assert.match(await page.locator('#map-place-day').textContent(),/未加入行程/);await unchanged('an exploration destination');
    await page.locator('#map-set-origin').click();await page.waitForFunction(()=>document.getElementById('map-journey-panel').dataset.selectionStage==='origin');await unchanged('an explicit exploration origin');
    await markerFor(page,'gz-opera').click();await waitJourney(page);await page.locator('#map-set-destination').click();
    assert.match(await page.locator('#map-place-day').textContent(),/已在行程.*第2天/);await unchanged('a building from another itinerary day');
    await page.locator('#map-route-mode').selectOption('drive');await waitJourney(page);assert.match(await page.locator('#map-journey-result').textContent(),/驾车/);await unchanged('changing comparison transport');
    await page.locator('#map-swap').click();await waitJourney(page);await unchanged('swapping comparison endpoints');
    await page.locator('#map-clear-selection').click();await waitClearJourney(page);await unchanged('clearing comparison endpoints');
    await page.getByRole('button',{name:'查看示意图',exact:true}).click();await markerFor(page,'gz-square').focus();await page.keyboard.press('Enter');await unchanged('selecting an illustration building');
    assert.equal(await markerFor(page,'gz-square').evaluate(node=>node===document.activeElement),true,'illustration clicks also keep focus in the map');
    await page.getByRole('button',{name:'返回高德地图',exact:true}).click();await waitReady(page);
    await page.evaluate(async()=>{const {renderMap}=await import('/src/travel-workspace.js'),plan=JSON.parse(localStorage.getItem('lvzang.v1')).plan;renderMap({...plan,...plan.days[0]},[],plan.stops,{isExample:true});});
    await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12);
    assert.match(await markerFor(page,'gz-museum').locator('.landmark-day').textContent(),/示例.*未加入/);
    assert.doesNotMatch(await markerFor(page,'gz-museum').getAttribute('aria-label'),/已在行程|第\d+天/);
    await markerFor(page,'gz-museum').click();assert.match(await page.locator('#map-place-day').textContent(),/示例地点.*未加入行程/);
    await page.locator('#map-route-mode').selectOption('walk');await waitReady(page);
    assert.match(await markerFor(page,'gz-museum').locator('.landmark-day').textContent(),/示例.*未加入/,'transport redraw preserves example provenance');
    await unchanged('browsing example buildings');
  }finally{await page.close();}
}
async function assertExplicitMapMembership(){
  const {page}=await newPage();
  try{
    await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12);
    await page.locator('[data-day="1"]').click();await waitReady(page);
    const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1'))),original=await read(),payloads=[];
    page.on('request',request=>{if(request.url().endsWith('/api/travel-chat/stream'))payloads.push(request.postDataJSON());});
    await page.locator('#map-fit').click();await markerFor(page,'gz-library').click();assert.deepEqual(await read(),original,'normal discovery click does not join the trip');
    assert.equal(await page.locator('#map-membership').textContent(),'加入行程');
    await page.locator('#map-membership').click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled&&JSON.parse(localStorage.getItem('lvzang.v1')).plan.stops.some(stop=>stop.id==='gz-library'));
    const added=await read();assert.equal(payloads.length,1);assert.deepEqual(payloads[0].itineraryEdit,{action:'add',stopId:'gz-library',stopName:'广州图书馆',dayIndex:2});
    assert.equal(added.plan.stops.find(stop=>stop.id==='gz-library').dayIndex,2,'explicit add uses the selected day');
    assert.deepEqual(added.collection,original.collection);assert.deepEqual(added.profile.fields.dayCount,original.profile.fields.dayCount);assert.deepEqual(added.profile.fields.dailyHours,original.profile.fields.dailyHours);
    assert.equal(await page.locator('[data-remove-stop="gz-library"]').count(),1,'new place appears in the actual itinerary');
    await page.reload();await waitReady(page);assert.equal((await read()).plan.stops.filter(stop=>stop.id==='gz-library').length,1,'explicit addition survives refresh');
    await markerFor(page,'gz-library').waitFor({state:'attached'});await page.locator('#map-fit').click();await markerFor(page,'gz-library').click();assert.equal(await page.locator('#map-membership').textContent(),'移出行程');
    await page.locator('#map-membership').click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled&&JSON.parse(localStorage.getItem('lvzang.v1')).plan.stops.every(stop=>stop.id!=='gz-library'));
    const removed=await read();assert.equal(payloads.length,2);assert.equal(payloads[1].itineraryEdit.action,'remove');assert.ok(removed.profile.fields.excludedPlaces.value.includes('广州图书馆'));assert.deepEqual(removed.collection,original.collection);
    await page.reload();await waitReady(page);assert.equal((await read()).plan.stops.some(stop=>stop.id==='gz-library'),false);assert.equal(await markerFor(page,'gz-library').count(),0,'explicitly excluded place is not silently restored as discovery');
  }finally{await page.close();}
}
async function markerPosition(page,id){return page.evaluate(id=>window.mock.maps.at(-1).overlays.find(item=>item.kind==='marker'&&item.content.dataset.stop===id)?.position,id);}
async function comparisonPath(page){return comparisonRoutes(page).evaluate(node=>JSON.parse(node.dataset.path));}
async function draw(page,city,names){
  // Legacy POI ambiguity/error scenarios isolate their own landmarks through the public control.
  if(await page.locator('#map-exploration-toggle').getAttribute('aria-pressed')==='true'){await page.locator('#map-exploration-toggle').click();await waitReady(page);}
  return page.evaluate(async({city,names})=>{const {renderMap}=await import('/src/travel-workspace.js');const stops=names.map((name,index)=>({id:'fixture-'+index,name,city,aliases:[],coords:[80,1]}));document.getElementById('route-stops').replaceChildren(...stops.map(stop=>{const article=document.createElement('article');article.className='stop-card';article.dataset.stopCard=stop.id;article.tabIndex=-1;const link=document.createElement('a');link.dataset.navigationStop=stop.id;article.append(link);return article;}));renderMap({city,stops},[]);return window.mock.maps[0]?.overlays.length||0;},{city,names});
}
try{
  const {page,loads}=await newPage();await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12&&document.querySelectorAll('.fixture-route').length===2);
  // This broad interaction flow deliberately explores every district; the
  // initial day-focused camera is covered by travel-map-initial-view.browser.js.
  await page.locator('#map-fit').click();await assertMapPan(page,'desktop');await page.locator('#map-fit').click();
  assert.equal(loads(),1);assert.equal(await page.locator('#city-map').evaluate(node=>getComputedStyle(node).visibility),'hidden');
  assert.equal(await page.locator('.map-marker').count(),signatureCount,'all accepted full-trip landmarks and signature exploration landmarks remain available');assert.equal(await page.locator('.fixture-route').count(),2,'only today\'s three accepted stops form the automatic route');assert.equal(await page.locator('#route-line path').count(),0);
  const firstStarts=await page.evaluate(()=>window.mock.searches.map(search=>search.startTime));assert.equal(firstStarts.length,signatureCount);for(let index=1;index<firstStarts.length;index++)assert.ok(firstStarts[index]-firstStarts[index-1]>=390,'the signature POI calls start at least 390 ms apart; observed '+(firstStarts[index]-firstStarts[index-1]).toFixed(1)+' ms');
  const camera=await page.evaluate(()=>window.mock.maps[0].options);assert.equal(camera.viewMode,'3D');assert.equal(camera.pitch,45);assert.equal(camera.rotation,0);assert.equal(camera.showBuildingBlock,true);
  assert.match(await markerFor(page,'gz-opera').locator('.landmark-day').textContent(),/第2天/);assert.match(await markerFor(page,'gz-museum').locator('.landmark-day').textContent(),/已在行程.*第1天/);assert.match(await markerFor(page,'gz-museum').getAttribute('aria-label'),/第1天.*第1站/,'the first stop uses its zero-based itinerary index');
  assert.equal(await page.locator('.map-marker').evaluateAll(nodes=>nodes.every(node=>node.tagName==='BUTTON'&&node.getAttribute('aria-label')&&node.querySelector('canvas[aria-hidden="true"]'))),true,'landmark miniatures retain native keyboard buttons and decorative canvas');
  await flushLayout(page);const geographicBefore=await page.evaluate(()=>({positions:window.mock.maps[0].overlays.filter(item=>item.kind==='marker').map(item=>({id:item.content.dataset.stop,position:item.getPosition()})),paths:window.mock.maps[0].overlays.filter(item=>item.kind==='route').map(item=>item.path)}));const projectionCount=await page.evaluate(()=>window.mock.projections.length);
  await page.evaluate(()=>{window.mock.clustered=true;for(const event of ['mapmove','zoomchange','moveend','zoomend','rotatechange','pitchchange'])window.mock.maps[0].emit(event);});await flushLayout(page);
  const layout=await page.evaluate(()=>({offsets:window.mock.offsets,projectionCount:window.mock.projections.length,positions:window.mock.maps[0].overlays.filter(item=>item.kind==='marker').map(item=>({id:item.content.dataset.stop,position:item.getPosition()})),paths:window.mock.maps[0].overlays.filter(item=>item.kind==='route').map(item=>item.path),allFromProvider:window.mock.maps[0].overlays.filter(item=>item.kind==='marker').every(marker=>window.mock.poiResults.some(result=>result.pois.some(poi=>JSON.stringify(poi.location)===JSON.stringify(marker.getPosition()))))}));assert.ok(layout.offsets.length>0&&layout.offsets.some(offset=>Math.hypot(offset.x,offset.y)>2),'nearby POIs receive display offsets');assert.ok(layout.offsets.every(offset=>Number.isFinite(offset.x)&&Number.isFinite(offset.y)),'all SDK marker offsets are finite');assert.ok(layout.offsets.every(offset=>Math.hypot(offset.x,offset.y)<=36.001),'display offsets never move landmarks farther than 36px');assert.deepEqual(layout.positions,geographicBefore.positions,'collision handling never changes provider marker positions');assert.deepEqual(layout.paths,geographicBefore.paths,'collision handling never changes provider route geometry');assert.equal(layout.allFromProvider,true);assert.ok(layout.projectionCount-projectionCount<=signatureCount*2,'six SDK events share one animation-frame layout');assert.equal(await page.locator('.landmark-leaders').getAttribute('aria-hidden'),'true');assert.equal(await page.locator('.landmark-leaders').evaluate(node=>getComputedStyle(node).pointerEvents),'none');assert.equal(await page.locator('.landmark-leaders circle').count(),signatureCount);assert.ok(await page.locator('.landmark-leaders line').count()>0,'display offsets retain leaders to actual POI anchors');
  await assertDenseMobileGeography(page);
  await assertLateExplorationPreservesWheelZoom();
  await assertMapComparisonNeverEditsItinerary();
  await assertExplicitMapMembership();
  await page.locator('#map-camera-toggle').click();assert.equal(await page.evaluate(()=>window.mock.maps[0].pitch),0);await page.locator('#map-camera-toggle').click();assert.equal(await page.evaluate(()=>window.mock.maps[0].pitch),45);
  await page.evaluate(()=>{window.mock.maps[0].rotation=37;});await page.locator('#map-reset-bearing').click();assert.equal(await page.evaluate(()=>window.mock.maps[0].rotation),0);const fitsBefore=await page.evaluate(()=>window.mock.fits.length);await page.locator('#map-fit').click();assert.equal(await page.evaluate(()=>window.mock.fits.length),fitsBefore+1);
  const zoomBefore=await page.evaluate(()=>window.mock.maps[0].getZoom()),zoomWorld=await page.locator('#canvas-world').evaluate(node=>node.style.transform);await page.locator('#map-zoom-in').click();assert.equal(await page.evaluate(()=>window.mock.maps[0].getZoom()),zoomBefore+1,'map plus changes SDK zoom');await page.locator('#map-zoom-out').click();assert.equal(await page.evaluate(()=>window.mock.maps[0].getZoom()),zoomBefore,'map minus changes SDK zoom');assert.equal(await page.locator('#canvas-world').evaluate(node=>node.style.transform),zoomWorld,'map zoom controls never change workspace zoom');
  const protocol=await page.evaluate(()=>({security:window.mock.securityAtLoad,searches:window.mock.searches,routes:window.mock.routes,overlays:window.mock.maps[0].overlays.filter(item=>item.kind==='route').map(item=>item.path)}));
  assert.equal(protocol.security.serviceHost,root+'/_AMapService');assert.ok(protocol.searches.every(search=>search.city==='广州'&&search.citylimit===true));
  assert.ok(protocol.overlays.every(path=>path.length===3),'provider step geometry preserves the bend');assert.equal(protocol.routes.length,2);
  assert.match(await page.locator('#map-details').textContent(),/高德步行约 1.49 公里 · 6 分钟（高德查询估算）/);
  const links=await page.locator('[data-navigation-stop]').evaluateAll(nodes=>nodes.map(node=>({text:node.textContent,url:node.href})));assert.ok(links.every(link=>link.text==='在高德导航'&&new URL(link.url).searchParams.get('coordinate')==='gaode'));assert.equal(new URL(links[1].url).pathname,'/navigation');
  assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'provider results never mutate accepted plan bytes');
  assert.equal(await page.locator('#map-exploration-toggle').getAttribute('aria-pressed'),'true','the default view includes city exploration landmarks');
  for(const id of ['gz-library','gz-ifc','gz-parc-central','gz-grandview']){const marker=markerFor(page,id);assert.equal(await marker.count(),1);assert.equal(await marker.getAttribute('data-landmark-kind'),['gz-parc-central','gz-grandview'].includes(id)?'commercial':id,'signature buildings use their landmark or category geometry');assert.match(await marker.locator('.landmark-day').textContent(),/探索.*未入行程/,'exploration labels distinguish buildings from accepted itinerary stops');assert.match(await marker.getAttribute('aria-label'),/探索地标，未加入行程/);assert.doesNotMatch(await marker.getAttribute('aria-label'),/第\d+站/);assert.equal(await marker.evaluate(node=>!node.classList.contains('has-no-model')&&node.querySelector('canvas').width>0),true,'the new landmark geometry initializes its canvas');}
  const explorationQueries=await page.evaluate(()=>window.mock.routes.length);await markerFor(page,'gz-library').click();await markerFor(page,'gz-museum').click();await waitJourney(page);assert.equal(await page.evaluate(()=>window.mock.routes.length),explorationQueries+1,'an exploration origin can query a route to an accepted destination');assert.deepEqual((await comparisonPath(page))[0],await markerPosition(page,'gz-library'));assert.deepEqual((await comparisonPath(page)).at(-1),await markerPosition(page,'gz-museum'));assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'exploration comparison never adds a place to the accepted trip');
  await page.locator('#map-exploration-toggle').click();await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===4);await waitClearJourney(page);assert.equal(await comparisonRoutes(page).count(),0,'hiding an exploration origin clears its comparison');assert.equal(await markerFor(page,'gz-library').count(),0);assert.equal(await page.locator('#map-exploration-toggle').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'hiding exploration leaves saved itinerary bytes unchanged');
  await page.locator('#map-exploration-toggle').click();await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12);assert.equal(await page.locator('#map-exploration-toggle').getAttribute('aria-pressed'),'true');
  const initialRequests=await page.evaluate(()=>window.mock.routes.length),selectionView=await page.evaluate(()=>({zoom:window.mock.maps[0].zoom,center:window.mock.maps[0].center,centers:window.mock.centers.length}));await markerFor(page,'gz-museum').focus();await page.keyboard.press('Enter');await flushLayout(page);assert.match(await page.locator('#map-origin').textContent(),/广东省博物馆/);assert.equal(await markerFor(page,'gz-museum').getAttribute('data-endpoint'),'origin');assert.equal(await markerFor(page,'gz-museum').getAttribute('aria-pressed'),'true');assert.equal(await comparisonRoutes(page).count(),0);assert.deepEqual(await page.evaluate(()=>({zoom:window.mock.maps[0].zoom,center:window.mock.maps[0].center,centers:window.mock.centers.length})),selectionView,'choosing an origin keeps the current map view available for destination selection');assert.equal(await markerFor(page,'gz-square').evaluate(node=>{const bounds=node.getBoundingClientRect();return document.elementFromPoint(bounds.x+bounds.width/2,bounds.y+bounds.height/2)?.closest('.map-marker')?.dataset.stop;}),'gz-square','nearby destination remains visible and receives pointer events after choosing origin');
  await markerFor(page,'gz-museum').click();assert.equal(await page.evaluate(()=>window.mock.routes.length),initialRequests,'clicking the origin again never queries a self-route');assert.equal(await comparisonRoutes(page).count(),0);
  await markerFor(page,'gz-square').click();await waitJourney(page);assert.equal(await page.evaluate(()=>window.mock.routes.length),initialRequests,'selected comparison reuses the actual daily route cache');assert.equal(await comparisonRoutes(page).count(),1);assert.equal(await markerFor(page,'gz-square').getAttribute('data-endpoint'),'destination');assert.match(await page.locator('#map-destination').textContent(),/花城广场/);assert.match(await page.locator('#map-journey-result').textContent(),/高德步行约 1.49 公里 · 6 分钟/);const selectedPath=await comparisonPath(page);assert.equal(selectedPath.length,3);assert.deepEqual(selectedPath[0],await markerPosition(page,'gz-museum'));assert.deepEqual(selectedPath.at(-1),await markerPosition(page,'gz-square'));
  await page.locator('#map-set-destination').click();assert.equal(await page.evaluate(()=>window.mock.routes.length),initialRequests,'reaffirming the current destination keeps the cached comparison');await page.locator('#map-swap').click();await waitJourney(page);assert.match(await page.locator('#map-origin').textContent(),/花城广场/);assert.match(await page.locator('#map-destination').textContent(),/广东省博物馆/);assert.equal(await page.evaluate(()=>window.mock.routes.length),initialRequests+1,'swapping requests the distinct reverse direction');assert.deepEqual((await comparisonPath(page))[0],await markerPosition(page,'gz-square'));
  await page.locator('#map-set-origin').click();await page.waitForFunction(()=>document.getElementById('map-journey-result').textContent.includes('起点已选好'));assert.equal(await comparisonRoutes(page).count(),0,'explicit origin replacement removes the previous comparison');assert.equal(await page.locator('.map-marker.is-destination').count(),0);await page.locator('#map-clear-selection').click();await waitClearJourney(page);assert.equal(await comparisonRoutes(page).count(),0);assert.equal(await page.locator('.fixture-route').count(),2,'clearing comparison preserves the daily route');assert.equal(await page.locator('.map-marker.is-origin,.map-marker.is-destination').count(),0);
  await markerFor(page,'gz-museum').click();await markerFor(page,'gz-square').click();await waitJourney(page);assert.equal(await page.evaluate(()=>window.mock.routes.length),initialRequests+1,'a repeated pair reuses its successful route');assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'selection, swap and camera operations preserve saved itinerary bytes');
  await page.locator('[data-day="1"]').click();await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===12);await waitClearJourney(page);assert.equal(await page.locator('.fixture-route').count(),0);assert.match(await page.locator('#time-detail').textContent(),/第2天 \/ 共3天/);
  await page.locator('#map-fit').click();await markerFor(page,'gz-museum').click();await markerFor(page,'gz-opera').click();await waitJourney(page);assert.equal(await comparisonRoutes(page).count(),1,'single-stop day can compare accepted landmarks from another day');assert.deepEqual((await comparisonPath(page)).at(-1),await markerPosition(page,'gz-opera'));assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved);
  await page.locator('[data-day="2"]').click();await page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='empty'&&document.querySelectorAll('.map-marker').length===12);await waitClearJourney(page);assert.equal(await page.locator('.fixture-route').count(),0);assert.match(await page.locator('#time-detail').textContent(),/第3天 \/ 共3天/);assert.equal(await page.locator('.map-marker.is-origin,.map-marker.is-destination').count(),0,'day switching resets the pair while retaining full-trip context');
  const queries=await page.evaluate(()=>({searches:window.mock.searches.length,routes:window.mock.routes.length}));await page.locator('[data-day="0"]').click();await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);assert.deepEqual(await page.evaluate(()=>({searches:window.mock.searches.length,routes:window.mock.routes.length})),queries,'confirmed lookups/routes are reused when returning to a day');
  await page.evaluate(async()=>{const {renderMap}=await import('/src/travel-workspace.js');const plan=JSON.parse(localStorage.getItem('lvzang.v1')).plan;renderMap({...plan,...plan.days[0],input:{...plan.input,budget:'800元'}},[]);});await waitReady(page);await page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);assert.deepEqual(await page.evaluate(()=>({searches:window.mock.searches.length,routes:window.mock.routes.length})),queries,'budget-only render uses the same provider cache');assert.equal(loads(),1);
  await page.locator('#map-route-mode').selectOption('drive');await waitReady(page);await page.waitForFunction(()=>window.mock.routes.filter(route=>route.mode==='drive').length===2&&[...document.querySelectorAll('.map-route-estimate')].every(row=>row.textContent.includes('高德驾车')));assert.match(await page.locator('#map-details').textContent(),/高德驾车/);assert.equal(new URL(await page.locator('[data-navigation-stop]').nth(1).getAttribute('href')).searchParams.get('mode'),'car');
  await flushLayout(page);const world=await page.locator('#canvas-world').evaluate(node=>node.style.transform),nodeX=await page.locator('#map-node').getAttribute('data-x');const bounds=await page.locator('#amap-viewport').boundingBox();await page.mouse.move(bounds.x+5,bounds.y+5);await page.mouse.wheel(0,120);await page.mouse.down();await page.mouse.move(bounds.x+50,bounds.y+25);await page.mouse.up();await flushLayout(page);assert.equal(await page.locator('#canvas-world').evaluate(node=>node.style.transform),world,'gestures on the map background do not transform the workspace');assert.equal(await page.locator('#map-node').getAttribute('data-x'),nodeX);await page.locator('#amap-viewport').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#canvas-world').evaluate(node=>node.style.transform),world);await page.locator('#map-node .node-header').focus();await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('#map-node').getAttribute('data-x'),nodeX,'map header remains draggable by keyboard');
  await page.setViewportSize({width:565,height:685});await assertMapPan(page,'565px touch',{touch:true});await page.setViewportSize({width:1500,height:1000});
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const mapBounds=await page.locator('#amap-viewport').boundingBox(),credit=await page.locator('.amap-copyright').boundingBox(),scale=await page.locator('.fixture-scale').boundingBox();assert.ok(credit.x>=mapBounds.x&&credit.x+credit.width<=mapBounds.x+mapBounds.width&&credit.y+credit.height<=mapBounds.y+mapBounds.height);assert.ok(scale.x>=mapBounds.x&&scale.y+scale.height<=mapBounds.y+mapBounds.height);await mkdir('artifacts/map-advisor',{recursive:true});await page.screenshot({path:'artifacts/map-advisor/amap-fixture-mobile.png',fullPage:true,animations:'disabled'});await page.setViewportSize({width:1500,height:1000});

  await page.evaluate(()=>{window.mock.fixtures['广州|待选公园']={pois:[{id:'north',name:'待选公园',cityname:'广州市',address:'北门',location:[113.34,23.14]},{id:'south',name:'待选公园',cityname:'广州市',address:'南门',location:[113.35,23.15]}]};});
  assert.equal(await draw(page,'广州',['前站','待选公园','后站']),0,'new render removes all old overlays immediately');await page.waitForFunction(()=>document.querySelectorAll('.map-place-choice').length===2&&document.querySelectorAll('.map-marker').length===2);assert.equal(await page.locator('.fixture-route').count(),0,'unresolved middle point cannot be bridged');assert.equal(await page.locator('[data-navigation-stop]').nth(1).textContent(),'在高德搜索');assert.equal(new URL(await page.locator('[data-navigation-stop]').nth(2).getAttribute('href')).pathname,'/marker');const beforeChoice=await page.evaluate(()=>window.mock.searches.length);await page.getByRole('button',{name:'待选公园 · 广州市 南门',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);assert.equal(await page.evaluate(()=>window.mock.searches.length),beforeChoice);assert.deepEqual(await page.evaluate(()=>window.mock.maps[0].overlays.filter(item=>item.kind==='marker').map(item=>item.position).find(pos=>pos[0]===113.35)),[113.35,23.15]);

  for(let index=0;index<3;index++)assert.match(await markerFor(page,'fixture-'+index).locator('.landmark-day').textContent(),new RegExp('第'+(index+1)+'站'),'three-stop fixture retains itinerary numbering despite delayed middle confirmation');
  await page.evaluate(()=>{window.mock.fixtures['广州|失联地点']={status:'error'};window.mock.fixtures['广州|未收录地点']={status:'no_data'};window.mock.fixtures['广州|临近门店']={pois:[{id:'fuzzy',name:'临近门店分店',cityname:'广州市',address:'附近街道',location:[113.36,23.16]}]};});await draw(page,'广州',['失联地点','未收录地点','临近门店']);await page.waitForFunction(()=>document.querySelectorAll('.map-address-form').length===3);assert.equal(await page.locator('.map-marker').count(),0);assert.equal(await page.locator('.fixture-route').count(),0);assert.match(await page.locator('#map-details').textContent(),/地点查询失败，请重试或补充地址/);assert.match(await page.locator('#map-details').textContent(),/尚未定位/);assert.ok((await page.locator('[data-navigation-stop]').allTextContents()).every(text=>text==='在高德搜索'));
  await page.locator('.map-address-form').first().locator('input').fill('具体街道88号');await page.locator('.map-address-form').first().getByRole('button',{name:'查询地址'}).click();await page.waitForFunction(()=>document.querySelector('[data-map-stop="fixture-0"] .map-place-choice'));assert.equal(await page.locator('.map-marker').count(),0,'manual address results always require confirmation');await page.locator('[data-map-stop="fixture-0"] .map-place-choice').click();await page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===1);
  await page.evaluate(()=>{window.mock.fixtures['广州|未收录地点']={};});await page.getByRole('button',{name:'重试地点查询',exact:true}).first().click();await page.waitForFunction(()=>document.querySelectorAll('.map-address-form').length===1);assert.equal(await page.locator('.map-marker').count(),2,'retry preserves confirmed choices and can resolve earlier missing result');

  await page.evaluate(()=>{window.mock.failRoutes=true;});await draw(page,'北京',['路线失败起点','路线失败终点']);await waitReady(page);await page.waitForFunction(()=>document.querySelector('.map-route-estimate')?.textContent.includes('查询失败'));assert.equal(await page.locator('.fixture-route').count(),0);await page.evaluate(()=>{window.mock.failRoutes=false;});await page.getByRole('button',{name:'重试路线',exact:true}).click();await page.waitForSelector('.fixture-route',{state:'attached'});
  await page.evaluate(()=>{window.mock.routeDelay=250;});await draw(page,'北京',['旧路线起点','旧路线终点']);await page.waitForFunction(()=>window.mock.routes.some(route=>route.from[0]>116.4&&document.querySelector('.map-route-estimate')?.textContent.includes('正在查询')));await draw(page,'珠海',['珠海独立点']);await waitReady(page);await page.waitForTimeout(300);assert.equal(await page.locator('.fixture-route').count(),0);assert.deepEqual(await markerNames(page),['珠海独立点'],'old route callbacks cannot draw in another city/day');
  await page.evaluate(()=>{window.mock.fixtures['北京|旧地点']={delay:250};});await draw(page,'北京',['旧地点']);await page.waitForFunction(()=>window.mock.searches.some(search=>search.name==='旧地点'));await draw(page,'珠海',['新地点']);await waitReady(page);await page.waitForTimeout(300);assert.deepEqual(await markerNames(page),['新地点'],'stale POI callbacks cannot add markers');
  await draw(page,'北京',['同名公园']);await waitReady(page);const beijing=await page.evaluate(()=>window.mock.maps[0].overlays[0].position);await draw(page,'珠海',['同名公园']);await waitReady(page);const zhuhai=await page.evaluate(()=>window.mock.maps[0].overlays[0].position);assert.notDeepEqual(beijing,zhuhai,'lookup cache is scoped to city');assert.equal(loads(),1);assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved);await page.close();

  const repeat=await newPage();await waitReady(repeat.page);await repeat.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);const repeatQueries=await repeat.page.evaluate(()=>window.mock.routes.length);await draw(repeat.page,'广州',['折返甲','折返乙','折返甲','折返乙']);await repeat.page.waitForFunction(()=>document.querySelectorAll('.map-route-estimate').length===3&&[...document.querySelectorAll('.map-route-estimate')].every(row=>row.textContent.includes('公里')));assert.equal(await repeat.page.evaluate(()=>window.mock.routes.length),repeatQueries+2,'repeated directed legs share requests');assert.equal(await repeat.page.locator('.fixture-route').count(),2);assert.equal(await repeat.page.locator('.map-route-estimate').count(),3,'every itinerary leg retains its distance/time row');
  await repeat.page.evaluate(()=>{window.mock.fixtures['广州|晚到起点']={delay:1600};});await draw(repeat.page,'广州',['晚到起点','早到中点','早到终点']);await repeat.page.waitForFunction(()=>document.querySelectorAll('.map-route-estimate').length===1&&document.querySelector('.map-route-estimate').textContent.includes('公里'));assert.match(await repeat.page.locator('.map-route-estimate').first().textContent(),/^早到中点 → 早到终点/,'later adjacent leg resolves first');await repeat.page.waitForFunction(()=>document.querySelectorAll('.map-route-estimate').length===2&&[...document.querySelectorAll('.map-route-estimate')].every(row=>row.textContent.includes('公里')));const ordered=await repeat.page.locator('.map-route-estimate').allTextContents();assert.match(ordered[0],/^晚到起点 → 早到中点/);assert.match(ordered[1],/^早到中点 → 早到终点/,'estimate rows retain itinerary order despite POI callback order');assert.equal(await repeat.page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved);await repeat.page.close();

  const explorer=await newPage();await waitReady(explorer.page);
  await draw(explorer.page,'广州',['比较甲','比较乙','比较丙','比较丁']);await waitReady(explorer.page);await explorer.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===3);
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=true;window.mock.pendingRoutes=[];});
  await markerFor(explorer.page,'fixture-0').click();await markerFor(explorer.page,'fixture-3').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===1);assert.equal(await comparisonRoutes(explorer.page).count(),0);
  await markerFor(explorer.page,'fixture-2').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===2);assert.match(await explorer.page.locator('#map-destination').textContent(),/比较丙/);
  await explorer.page.evaluate(()=>window.mock.pendingRoutes[1].finish());await waitJourney(explorer.page);const latestPath=await comparisonPath(explorer.page);assert.deepEqual(latestPath.at(-1),await markerPosition(explorer.page,'fixture-2'));
  await explorer.page.evaluate(async()=>{window.mock.pendingRoutes[0].finish();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});assert.deepEqual(await comparisonPath(explorer.page),latestPath,'an older in-flight destination cannot replace the current geometry');assert.equal(await comparisonRoutes(explorer.page).count(),1);
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=false;});await explorer.page.locator('#map-route-mode').selectOption('drive');await waitJourney(explorer.page);assert.match(await explorer.page.locator('#map-journey-result').textContent(),/高德驾车约/);assert.match(await explorer.page.locator('#map-origin').textContent(),/比较甲/);assert.match(await explorer.page.locator('#map-destination').textContent(),/比较丙/);assert.equal(await markerFor(explorer.page,'fixture-0').getAttribute('data-endpoint'),'origin');assert.equal(await markerFor(explorer.page,'fixture-2').getAttribute('data-endpoint'),'destination');assert.deepEqual((await comparisonPath(explorer.page)).at(-1),await markerPosition(explorer.page,'fixture-2'));
  const selectedOverlay=await explorer.page.evaluate(()=>{const item=window.mock.maps.at(-1).overlays.find(item=>item.extData?.kind==='comparison');return {strokeWeight:item?.strokeWeight,zIndex:item?.zIndex,path:item?.path};});assert.equal(selectedOverlay.strokeWeight,6);assert.equal(selectedOverlay.zIndex,120);assert.equal(selectedOverlay.path.length,3,'comparison uses provider step geometry rather than a straight segment');
  await explorer.page.setViewportSize({width:390,height:844});assert.ok(await explorer.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const targets=await explorer.page.locator('#map-camera-toggle,#map-fit,#map-reset-bearing,#map-exploration-toggle,#map-zoom-in,#map-zoom-out,#map-set-origin,#map-set-destination,#map-swap,#map-clear-selection').evaluateAll(nodes=>nodes.map(node=>({id:node.id,width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height})));assert.ok(targets.every(target=>target.width>=36&&target.height>=36),'mobile map actions remain usable targets: '+JSON.stringify(targets));const landmarkBounds=await markerFor(explorer.page,'fixture-0').boundingBox();assert.ok(landmarkBounds.width>=44&&landmarkBounds.height>=44,'mobile landmark button has a usable target');await explorer.page.locator('#map-clear-selection').focus();await explorer.page.keyboard.press('Enter');await waitClearJourney(explorer.page);assert.equal(await comparisonRoutes(explorer.page).count(),0,'keyboard clear removes comparison');await explorer.page.setViewportSize({width:1500,height:1000});
  await explorer.page.locator('#map-route-mode').selectOption('walk');await explorer.page.waitForFunction(()=>[...document.querySelectorAll('.map-route-estimate')].every(node=>node.textContent.includes('高德步行')));
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=true;window.mock.pendingRoutes=[];});await markerFor(explorer.page,'fixture-2').click();await markerFor(explorer.page,'fixture-0').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===1);await explorer.page.locator('#map-clear-selection').click();await waitClearJourney(explorer.page);await explorer.page.evaluate(async()=>{window.mock.pendingRoutes[0].finish();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});assert.equal(await comparisonRoutes(explorer.page).count(),0,'clearing invalidates an in-flight comparison');assert.equal(await explorer.page.locator('.map-marker.is-origin,.map-marker.is-destination').count(),0);
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=false;});await draw(explorer.page,'北京',['失败比较起点','失败比较中点','失败比较终点']);await waitReady(explorer.page);await explorer.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);await explorer.page.evaluate(()=>{window.mock.failRoutes=true;});await markerFor(explorer.page,'fixture-0').click();await markerFor(explorer.page,'fixture-2').click();await explorer.page.waitForFunction(()=>document.getElementById('map-journey-result').textContent.includes('暂无完整步行路线'));assert.equal(await comparisonRoutes(explorer.page).count(),0);const failedRequests=await explorer.page.evaluate(()=>window.mock.routes.length);await explorer.page.evaluate(()=>{window.mock.failRoutes=false;});await explorer.page.locator('#map-journey-retry').click();await waitJourney(explorer.page);assert.equal(await explorer.page.evaluate(()=>window.mock.routes.length),failedRequests+1,'comparison retry performs a fresh provider query after failure');assert.equal(await comparisonRoutes(explorer.page).count(),1);
  await draw(explorer.page,'北京',['旧比较起点','旧比较中点','旧比较终点']);await waitReady(explorer.page);await explorer.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);await explorer.page.evaluate(()=>{window.mock.holdRoutes=true;window.mock.pendingRoutes=[];});await markerFor(explorer.page,'fixture-0').click();await markerFor(explorer.page,'fixture-2').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===1);await draw(explorer.page,'珠海',['新比较单点']);await waitReady(explorer.page);await waitClearJourney(explorer.page);await explorer.page.evaluate(async()=>{window.mock.pendingRoutes[0].finish();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});assert.equal(await comparisonRoutes(explorer.page).count(),0,'trip replacement invalidates an in-flight pair even when stop IDs are reused');assert.deepEqual(await markerNames(explorer.page),['新比较单点']);
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=false;});await draw(explorer.page,'广州',['示意比较起点','示意比较中点','示意比较终点']);await waitReady(explorer.page);await explorer.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);await explorer.page.evaluate(()=>{window.mock.holdRoutes=true;window.mock.pendingRoutes=[];});await markerFor(explorer.page,'fixture-0').click();await markerFor(explorer.page,'fixture-2').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===1);await explorer.page.getByRole('button',{name:'查看示意图',exact:true}).click();await explorer.page.evaluate(async()=>{window.mock.pendingRoutes[0].finish();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});assert.equal(await comparisonRoutes(explorer.page).count(),0,'illustration switching invalidates provider comparison callbacks');await explorer.page.getByRole('button',{name:'返回高德地图',exact:true}).click();await waitReady(explorer.page);await waitClearJourney(explorer.page);assert.equal(await explorer.page.locator('.map-marker.is-origin,.map-marker.is-destination').count(),0);
  await explorer.page.evaluate(()=>{window.mock.holdRoutes=false;});await draw(explorer.page,'广州',['地图错误起点','地图错误中点','地图错误终点']);await waitReady(explorer.page);await explorer.page.waitForFunction(()=>document.querySelectorAll('.fixture-route').length===2);await explorer.page.evaluate(()=>{window.mock.holdRoutes=true;window.mock.pendingRoutes=[];});await markerFor(explorer.page,'fixture-0').click();await markerFor(explorer.page,'fixture-2').click();await explorer.page.waitForFunction(()=>window.mock.pendingRoutes.length===1);await explorer.page.evaluate(async()=>{window.mock.maps.at(-1).emit('error');window.mock.pendingRoutes[0].finish();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);});assert.equal(await explorer.page.locator('.route-map').getAttribute('data-map-phase'),'error');assert.equal(await comparisonRoutes(explorer.page).count(),0,'map errors invalidate provider comparison callbacks');assert.equal(await explorer.page.locator('.map-marker').count(),0);assert.equal(await explorer.page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'all exploratory journeys leave accepted itinerary bytes unchanged');await explorer.page.close();

  const delayedExploration=await newPage({fixtures:{'广州|广州图书馆':{delay:6500}}});await waitReady(delayedExploration.page);await delayedExploration.page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===11);assert.equal(await markerFor(delayedExploration.page,'gz-library').count(),0);await assertMapPan(delayedExploration.page,'pending exploration');const draggedCamera=await delayedExploration.page.evaluate(()=>({center:[...window.mock.maps.at(-1).getCenter()],fits:window.mock.fits.length}));await markerFor(delayedExploration.page,'gz-library').waitFor({state:'attached'});await flushLayout(delayedExploration.page);assert.deepEqual(await delayedExploration.page.evaluate(()=>({center:[...window.mock.maps.at(-1).getCenter()],fits:window.mock.fits.length})),draggedCamera,'a late exploration POI does not refit or move the camera after a user drag');assert.equal(await delayedExploration.page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved);await delayedExploration.page.close();
  const rejectedProfile=updateTravelProfile(profile,{text:'不去广州塔',patch:{excludedPlaces:['广州塔']}}).profile,rejectedPlan=buildDailyPlan({...base,stops:base.stops.filter(stop=>stop.id!=='gz-tower').map((stop,index)=>({...stop,dayIndex:index<2?1:2}))},rejectedProfile),rejectedSaved=JSON.stringify({...initialState(),profile:rejectedProfile,plan:rejectedPlan});const rejected=await newPage({savedState:rejectedSaved});await waitReady(rejected.page);await rejected.page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===11);assert.equal(await markerFor(rejected.page,'gz-tower').count(),0,'an excluded landmark never reappears as exploration');assert.equal(await rejected.page.evaluate(()=>window.mock.searches.some(search=>search.name==='广州塔')),false,'an excluded landmark is not silently queried');await rejected.page.locator('#map-exploration-toggle').click();await waitReady(rejected.page);await rejected.page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===3);await rejected.page.locator('#map-exploration-toggle').click();await waitReady(rejected.page);await rejected.page.waitForFunction(()=>document.querySelectorAll('.map-marker').length===11);assert.equal(await markerFor(rejected.page,'gz-tower').count(),0);assert.equal(await rejected.page.evaluate(()=>localStorage.getItem('lvzang.v1')),rejectedSaved,'exploration visibility preserves accepted trip and exclusions');await rejected.page.close();
  const missing=await newPage({disabled:true});await missing.page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='unconfigured');assert.equal(missing.loads(),0);assert.equal(await missing.page.locator('.map-marker').count(),0);assert.match(await missing.page.locator('#map-message').textContent(),/尚未配置/);assert.equal(await missing.page.locator('[data-navigation-stop]').first().textContent(),'在高德搜索');await missing.page.getByRole('button',{name:'查看示意图',exact:true}).click();assert.equal(await missing.page.locator('.map-marker').count(),3);assert.match(await missing.page.locator('#map-status').textContent(),/未经高德核实/);await missing.page.getByRole('button',{name:'返回高德地图',exact:true}).click();await missing.page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='unconfigured');assert.equal(await missing.page.locator('.map-marker').count(),0);await missing.page.unroute('**/api/map/config');await missing.page.getByRole('button',{name:'重新加载地图',exact:true}).click();await waitReady(missing.page);assert.equal(missing.loads(),1);await missing.page.close();
  const retry=await newPage({failSdk:true});await retry.page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='error');assert.equal(await retry.page.locator('.map-marker').count(),0);await retry.page.getByRole('button',{name:'重新加载地图',exact:true}).click();await waitReady(retry.page);assert.equal(retry.loads(),2,'failed SDK load can retry once and successful SDK is reused');await retry.page.locator('[data-day="1"]').click();await waitReady(retry.page);assert.equal(retry.loads(),2);await retry.page.close();
  const basemap=await newPage({failMap:true});await basemap.page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='error');assert.equal(await basemap.page.evaluate(()=>window.mock.searches.length),0,'failed basemap never queries POIs');assert.equal(await basemap.page.evaluate(()=>window.mock.destroys),1);await basemap.page.getByRole('button',{name:'重新加载地图',exact:true}).click();await waitReady(basemap.page);assert.equal(basemap.loads(),1,'basemap retry reuses the successful SDK');assert.equal(await basemap.page.evaluate(()=>window.mock.maps.length),2);await basemap.page.evaluate(()=>window.mock.maps.at(-1).emit('error'));assert.equal(await basemap.page.locator('.map-marker').count(),0);assert.equal(await basemap.page.locator('[data-navigation-stop]').first().textContent(),'在高德搜索');await basemap.page.getByRole('button',{name:'重新加载地图',exact:true}).click();await waitReady(basemap.page);assert.equal(await basemap.page.evaluate(()=>window.mock.destroys),2);await basemap.page.close();
  const delayed=await newPage({mapDelay:250});await delayed.page.waitForFunction(()=>window.mock.maps.length===1);assert.equal(await delayed.page.evaluate(()=>window.mock.searches.length),0,'SDK load alone does not count as a loaded map');await waitReady(delayed.page);await delayed.page.close();
  const changed=await newPage();await waitReady(changed.page);await changed.page.evaluate(()=>window.mock.maps[0].emit('error'));await changed.page.route('**/api/map/config',route=>route.fulfill({json:{provider:'amap',enabled:true,key:'corrected-fixture-key',serviceHost:'/_AMapService'}}));await changed.page.getByRole('button',{name:'重新加载地图',exact:true}).click();await changed.page.waitForFunction(()=>document.getElementById('map-status').textContent.includes('配置已更新'));assert.equal(changed.loads(),1);await Promise.all([changed.page.waitForEvent('load'),changed.page.getByRole('button',{name:'刷新并重试',exact:true}).click()]);await waitReady(changed.page);assert.equal(changed.loads(),2,'changed SDK identity requests a fresh page rather than reusing stale credentials');assert.equal(await changed.page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved);await changed.page.close();
  const timeout=await newPage({neverComplete:true});await timeout.page.waitForFunction(()=>document.querySelector('.route-map').dataset.mapPhase==='error',null,{timeout:25000});assert.equal(await timeout.page.evaluate(()=>window.mock.searches.length),0);assert.equal(await timeout.page.evaluate(()=>window.mock.destroys),1,'basemap completion timeout destroys the failed instance');await timeout.page.close();
  assert.deepEqual(errors,[]);console.log('PASS: signature POI queries paced at least 390 ms apart; SDK DOM drags change center and provider-POI projection on desktop/565px touch while workspace position/scale remains unchanged; late exploration POIs retain the dragged camera and native wheel zoom; SDK zoom controls; 12 signature / 26 detailed landmarks and distinct miniature geometries; truthful accepted/example/exploration labels; real map membership buttons add to selected day, remove, preserve profile and survive refresh; accepted and exploratory building selection, explicit endpoints, transport, swap and clear preserve saved bytes, active day and itinerary cards; 390px dense landmarks remain keyboard accessible, signature offsets stay within 36px, detailed landmarks retain exact provider anchors; exploration-to-itinerary routing, toggle cleanup and excluded landmark preservation; SDK/config lifecycle, 3D camera/fit/reset, collision offsets with unchanged provider positions/routes, animation-frame event coalescing, POI anchor leaders, stable origin/destination selection, keyboard selection, swap/clear, directed route cache and geometry/distance/time, stale callbacks, failure/retry, unchanged saved trip bytes, explicit ambiguity/address selection, daily routes, SDK retry, mobile targets and attribution. Fixture coverage only; all non-fixture external browser requests blocked and no live provider calls.');
 }catch(error){
  for(const [index,page]of browser.contexts().flatMap(context=>context.pages()).entries()){
    await page.screenshot({path:`artifacts/map-advisor/failure-${index}.png`,fullPage:true}).catch(()=>{});
    console.error('Map failure view',index,await page.evaluate(()=>({markers:[...document.querySelectorAll('.map-marker')].map(node=>{const rect=node.getBoundingClientRect();return {id:node.dataset.stop,rect:rect.toJSON(),hit:document.elementFromPoint(rect.x+rect.width/2,rect.y+rect.height/2)?.closest('.map-marker')?.dataset.stop};}),phase:document.querySelector('.route-map')?.dataset.mapPhase})).catch(()=>{}));
  }
  throw error;
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
