import assert from 'node:assert/strict';import {chromium} from 'playwright';import {createApp} from '../server.js';
const server=createApp({key:'',tripoKey:''});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.goto(base+'/collection.html');await page.locator('.world-viewport').waitFor();await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),s=await openKeepsakeStore();for(const id of ['first','second'])await s.save({keepsake:{id,schemaVersion:1,title:'同一天的广州',city:'广州',kind:'magnet',scope:'personal',participants:[{id:'me',name:'我'}],modelRef:'pending',memoryIds:[id+'-memory'],dateStart:'2026-10-05',dateEnd:'2026-10-05',createdAt:1,updatedAt:1,origin:'user'},memories:[{id:id+'-memory',keepsakeId:id,authorId:'me',date:'2026-10-05',placeName:'广州',story:id.toUpperCase(),photoIds:[]}],photos:[]});await s.setMeta('world-layout-v1',{groups:{first:{x:999,y:666}},assets:{}});});await page.reload();await page.locator('.studio-shelf-item').first().waitFor();assert.equal(await page.locator('.world-group').count(),2,'same title/date remain independent');
 await page.getByRole('link',{name:'地图',exact:true}).click();await page.locator('.world-map-marker').waitFor();await page.locator('.world-map-marker').click();assert.equal(await page.locator('.world-city-options button').count(),2);await page.locator('.world-city-options button').nth(1).click();assert.match(await page.locator('.world-inspector').textContent(),/SECOND/);
 await page.getByRole('link',{name:'自由画布',exact:true}).click();await page.locator('.studio-shelf-item').first().waitFor();await page.getByRole('button',{name:'浏览示例布局',exact:true}).click();await page.getByRole('button',{name:'整理画布',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'自动整理',exact:true}).click();assert.deepEqual(await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js');return (await (await openKeepsakeStore()).getMeta('world-layout-v1')).groups.first;}),{x:999,y:666});
 await page.getByRole('button',{name:'添加旅行回忆',exact:true}).click();await page.locator('[name=photo]').setInputFiles('public/assets/keepsakes/memory-1.webp');await page.waitForFunction(()=>!document.querySelector('[data-action=save-upload]').disabled);await page.evaluate(()=>{const orig=IDBDatabase.prototype.transaction,d=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'oncomplete');IDBDatabase.prototype.transaction=function(...a){const t=orig.apply(this,a);if(a[1]==='readwrite')Object.defineProperty(t,'oncomplete',{set(f){d.set.call(t,e=>setTimeout(()=>f(e),350));}});return t;};});await page.getByRole('button',{name:'保存到画布',exact:true}).click();await page.getByRole('button',{name:'添加旅行回忆',exact:true}).click();assert.equal(await page.locator('dialog[open]').count(),0,'inline saving must not open a newer form');await page.waitForFunction(()=>document.querySelector('.world-toast')?.textContent.includes('已保存'));await page.locator('#collection-dialog').waitFor({state:'hidden'});
 const backup=await page.evaluate(async()=>{const {openKeepsakeStore}=await import('/src/travel-keepsake-store.js'),{exportKeepsakeBackup,decodeKeepsakeBackup}=await import('/src/travel-keepsake-backup.js'),s=await openKeepsakeStore();const blob=await exportKeepsakeBackup(s);return decodeKeepsakeBackup(new Uint8Array(await blob.arrayBuffer())).meta;});assert.equal(backup[0].value.groups.first.x,999);
 console.log('PASS: independent matching uploads, same-city chooser, demo reset preserves personal layout, save single-flight and layout backup.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
