import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {initialState} from '../public/src/travel-state.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';

const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州一天，每天4小时，喜欢美食，必去广州塔'}).profile;
const plan={...buildDailyPlan({...planFromCatalog(normalizeRequest({destination:'广州',hours:4}),undefined,{placeIds:['gz-tower'],title:'原广州攻略'}),mode:'ai',trace:[]},profile),kind:'plan'};
plan.guide={status:'ready',summary:'沿用旅行偏好，参观后留出休息时间。',days:[{dayIndex:1,overview:'先看建筑外观，再按实际预约与天气决定游览方式。',stops:plan.stops.map(stop=>({stopId:stop.id,name:stop.name,howToPlay:'先在入口了解参观路线，再按个人兴趣慢慢游览。每个观景区域都可以停下来拍照和休息，不必赶着看完所有内容。留出弹性时间，遇到排队就先休息。',highlights:['建筑外观与城市天际线','不同角度的公共空间'],food:[{name:'附近粤菜或粥粉面',kind:'cuisine',note:'到店前核实营业状态和排队情况，按自己的预算选择，优先考虑步行可达、顺路的店铺。',sourceIds:[]}],transport:'使用地图核对实际步行入口和出行距离。若遇降雨，可以选择公共交通。',reservation:'出发前查看官方网站，确认预约、票价和开放时间。',rainyAlternative:'按天气调整室外部分，保留室内参观与休息时间。',sourceIds:[]}))}],sources:[],warnings:['费用和开放规则仍需临行核实。']};
const server=createApp({accountsEnabled:false,key:'test',amapJsKey:'',fetchImpl:async()=>{throw Error('No external calls in UI regression');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/travel.html`);
  await page.evaluate(raw=>localStorage.setItem('lvzang.v1',raw),JSON.stringify({...initialState(),profile,plan}));await page.reload();
  assert.equal(await page.locator('#route-refresh').count(),1,'A visible refresh action must exist in the shared toolbar');
  assert.equal(await page.locator('#route-destination').inputValue(),'广州');
  for(const width of [1146,1440,580,390]){
    await page.setViewportSize({width,height:900});await page.reload();await page.waitForSelector('.stop-guide');
    const initialVisibility=await page.locator('#route-refresh').evaluate(button=>{const r=button.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)?.closest('#route-refresh')===button;});
    assert.ok(initialVisibility,`${width}px: global refresh is visible and actionable on the initial screen`);
    await page.locator('.canvas-panel').scrollIntoViewIfNeeded();
    const guideBox=await page.locator('#guide-pane').boundingBox();await page.mouse.move(guideBox.x+guideBox.width/2,Math.min(850,Math.max(guideBox.y+70,guideBox.y+guideBox.height/2)));await page.mouse.wheel(0,600);await page.waitForTimeout(120);
    const visibility=await page.locator('#route-refresh').evaluate(button=>{const r=button.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:innerHeight,guideScroll:document.getElementById('guide-pane').scrollTop,inView:r.top>=0&&r.bottom<=innerHeight&&document.elementFromPoint(r.left+r.width/2,r.top+r.height/2)?.closest('#route-refresh')===button};});
    assert.ok(visibility.guideScroll>100,`${width}px: the regression actually scrolls into the guide`);
    assert.ok(visibility.inView,`${width}px: refresh stays actionable after reading the middle of the guide: ${JSON.stringify(visibility)}`);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px: toolbar does not overflow`);
  }
  assert.equal(await page.locator('#app-main #route-refresh-slot').count(),1);
  assert.equal(await page.locator('.workspace #route-refresh-slot').count(),0,'The refresh toolbar is shared outside chat and map/guide panes');
  assert.equal(await page.locator('#canvas-viewport #route-refresh-slot').count(),0,'The refresh toolbar lives outside the scrolling workspace');
  assert.equal(await page.locator('#route-refresh').textContent(),'刷新攻略');
  assert.match(await page.locator('label[for="route-destination"]').textContent(),/城市|地区|目的地/);
  assert.match(await page.locator('#route-destination').getAttribute('placeholder'),/地区/);assert.match(await page.locator('#route-destination').getAttribute('placeholder'),/西藏/);
  assert.match(await page.locator('#route-current-destination').textContent(),/广州/);
  await page.setViewportSize({width:1440,height:900});
  let submitted;
  let releaseFailure;const holdFailure=new Promise(resolve=>releaseFailure=resolve);
  await page.route('**/api/travel-chat/stream',async route=>{
    submitted=route.request().postDataJSON();
    await holdFailure;
    await route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'error',error:'测试刷新失败，旧攻略保留。'})+'\n'});
  });
  await page.locator('#travel-brief').fill('尚未发送的新想法');
  await page.locator('#route-destination').fill('西藏');await page.locator('#route-refresh').click();
  await page.waitForFunction(()=>document.querySelector('#route-refresh').disabled);
  assert.match(await page.locator('#map-title').textContent(),/广州/);assert.match(await page.locator('#workspace-title').textContent(),/广州/);
  assert.match(await page.locator('#route-current-destination').textContent(),/广州/);
  assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')))).plan.city,'广州','Pending destination never changes the accepted map city');
  releaseFailure();
  await page.waitForFunction(()=>!document.querySelector('#route-refresh').disabled);
  assert.equal(submitted.destination,'西藏');assert.equal(submitted.textRevision,false);assert.equal(submitted.mode,'ai');
  assert.match(submitted.description,/重新规划西藏.*完整行程/);assert.equal(submitted.currentPlan.city,'广州');assert.deepEqual(submitted.profile,profile);
  assert.equal(await page.locator('#travel-brief').inputValue(),'尚未发送的新想法');assert.equal(await page.locator('#route-destination').inputValue(),'西藏');
  assert.match(await page.locator('#route-refresh-note').textContent(),/失败/);assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')))).plan.title,'原广州攻略');
  assert.match(await page.locator('#map-title').textContent(),/广州/);assert.match(await page.locator('#workspace-title').textContent(),/广州/);
  assert.match(await page.locator('#route-current-destination').textContent(),/广州/);
  const pendingProfile=updateTravelProfile(profile,{text:'目的地是西藏'}).profile;
  await page.route('**/api/travel-chat/stream',async route=>{await route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'result',response:{kind:'clarify',status:'partial',mode:'ai',trace:[],profile:pendingProfile,followUps:[],assistantReply:'已记下西藏，当前具体安排未完成，旧方案保留。'}})+'\n'});});
  await page.locator('#route-refresh').click();await page.waitForFunction(()=>!document.querySelector('#route-refresh').disabled);
  const partialState=await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')));assert.equal(partialState.profile.fields.destination.value,'西藏');assert.equal(partialState.plan.city,'广州');
  for(const id of ['map-title','workspace-title','route-current-destination'])assert.match(await page.locator('#'+id).textContent(),/广州/,'An unfinished destination profile is not an accepted replacement route');
  const updatedProfile=updateTravelProfile(profile,{text:'目的地是杭州'}).profile;
  const updated={...buildDailyPlan({...planFromCatalog(normalizeRequest({destination:'杭州',hours:4}),undefined,{title:'刷新后的杭州攻略'}),mode:'ai',trace:[]},updatedProfile),kind:'plan',assistantReply:'新的杭州攻略已生成。'};
  await page.route('**/api/travel-chat/stream',async route=>{submitted=route.request().postDataJSON();await route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'result',response:updated})+'\n'});});
  await page.locator('#route-destination').fill('杭州');await page.locator('#route-refresh').click();await page.waitForFunction(()=>!document.querySelector('#route-refresh').disabled);
  assert.equal(submitted.destination,'杭州');assert.match(await page.locator('#route-title').textContent(),/刷新后的杭州/);assert.equal(await page.locator('#travel-brief').inputValue(),'尚未发送的新想法');
  for(const id of ['map-title','workspace-title','route-current-destination'])assert.match(await page.locator('#'+id).textContent(),/杭州/,'Accepted result updates the visible city consistently');
  assert.equal(await page.locator('#route-destination').inputValue(),'杭州');
  await page.reload();assert.match(await page.locator('#route-title').textContent(),/刷新后的杭州/);for(const id of ['map-title','workspace-title','route-current-destination'])assert.match(await page.locator('#'+id).textContent(),/杭州/);
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.deepEqual(errors,[]);console.log('PASS: refresh stays actionable while reading at four widths; region input and saved context, pending/failure keep accepted map city, successful city switch updates all titles and persists, draft preserved.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
