import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {initialState} from '../public/src/travel-state.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';
import {applyItineraryEdit} from '../public/src/travel-itinerary-edit.js';
import {travelPlanStatus} from '../public/src/travel-workspace.js';

const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州三天，每天4小时，正常节奏'}).profile;profile.followUps=[];
const makePlan=ids=>buildDailyPlan({...planFromCatalog(normalizeRequest({destination:'广州',hours:4}),undefined,{placeIds:ids}),mode:'ai',trace:[]},profile);
const sparse=makePlan(['gz-museum']),complete=makePlan(['gz-museum','gz-square','gz-opera']);
const guide={status:'unavailable',days:[],sources:[{id:'official',title:'已经读取的资料',url:'https://www.gdmuseum.com/',accessStatus:'fetched'}],warnings:['本次检索未找到可引用的公开旅行网页。']};
sparse.guide={...guide,summary:'后两天是自由日。',days:[{dayIndex:2,overview:'自由日，未安排固定地点',stops:[]}]};complete.guide=guide;
const removeSquare={action:'remove',stopId:'gz-square',stopName:'花城广场'};
const removed=applyItineraryEdit({profile,currentPlan:complete},removeSquare);
assert.deepEqual(removed.planningCoverage.freeDays,[2]);assert.deepEqual(removed.planningCoverage.missingDays,[]);
const restored=applyItineraryEdit({profile:removed.profile,currentPlan:removed},{action:'add',stopId:'gz-square',stopName:'花城广场',dayIndex:2});
assert.deepEqual(restored.planningCoverage.freeDays,[],'Adding a place back removes the explicit free-day marker');
const stillSparse=applyItineraryEdit({profile,currentPlan:sparse},{action:'remove',stopId:'gz-museum',stopName:'广东省博物馆'});
assert.deepEqual(stillSparse.planningCoverage.freeDays,[1]);assert.deepEqual(stillSparse.planningCoverage.missingDays,[2,3],'Removing one day cannot relabel pre-existing gaps as intentional free time');
assert.equal(travelPlanStatus(stillSparse,{dayIndex:1}).label,'行程待补充');
const server=createApp({accountsEnabled:false,key:'',amapJsKey:'',amapSecurityJsCode:'',fetchImpl:async()=>{throw Error('No external requests');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:844},reducedMotion:'reduce'}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(`http://127.0.0.1:${server.address().port}/travel.html`);
 const seed=async plan=>{await page.evaluate(raw=>localStorage.setItem('lvzang.v1',raw),JSON.stringify({...initialState(),profile:plan.profile??profile,plan}));await page.reload();};
 await seed(sparse);await page.locator('[data-day="1"]').click();
 assert.equal(await page.locator('#route-state').textContent(),'行程待补充');
 assert.match(await page.locator('.day-empty').textContent(),/第2天还没有排入具体地点/);
 assert.doesNotMatch(await page.locator('#route-stops').textContent(),/自由/);
 const missingDayGuide=await page.locator('#travel-guide-overview').textContent();
 assert.match(missingDayGuide,/这一天尚待补齐具体安排/);assert.doesNotMatch(missingDayGuide,/自由日|未安排固定地点/,'An old model-written free-day overview cannot certify an unplanned day');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')).plan.guide.days[0].overview),'自由日，未安排固定地点','Suppressing a misleading overview does not rewrite saved source data');
 assert.match(await page.locator('#workspace-status').textContent(),/第2天、 第3天|第2天、第3天/);
 await seed(complete);
 assert.equal(await page.locator('#route-state').textContent(),'攻略待补充');
 const guideText=await page.locator('#travel-guide-overview').textContent();
 assert.match(guideText,/详细攻略待补充/);assert.match(guideText,/部分检索未取得/);assert.doesNotMatch(guideText,/本次检索未找到/);
 const failedSearch={...complete,guide:{...guide,sources:[]}};await seed(failedSearch);
 assert.match(await page.locator('#travel-guide-overview').textContent(),/本次检索未找到/,'Without any sources the original failure remains accurate');
 await seed(complete);await page.locator('[data-day="1"]').click();
 await page.locator('[data-remove-stop="gz-square"]').click();
 await page.waitForFunction(()=>!document.getElementById('plan-button').disabled&&JSON.parse(localStorage.getItem('lvzang.v1')).plan.stops.length===2);
 assert.equal(await page.locator('#route-state').textContent(),'自由安排');assert.match(await page.locator('.day-empty').textContent(),/按你的选择/);
 await page.reload();await page.locator('[data-day="1"]').click();assert.equal(await page.locator('#route-state').textContent(),'自由安排');
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')).plan);
 await page.route('**/api/travel-chat/stream',route=>route.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({type:'result',response:{kind:'clarify',status:'partial',mode:'ai',profile,followUps:[],trace:[],assistantReply:'第2天和第3天尚未安排具体地点，本次规划未完成，已保留原方案。'}})+'\n'}));
 await page.locator('#travel-brief').fill('请重新安排三天行程');await page.locator('#travel-brief').press('Enter');
 await page.waitForFunction(()=>!document.getElementById('plan-button').disabled&&document.getElementById('plan-status').textContent.includes('本次规划尚未完成'));
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1')).plan),before,'A partial new plan never replaces the saved route');
 assert.doesNotMatch(await page.locator('#workspace-status').textContent(),/等你补充条件/);
 assert.doesNotMatch(await page.locator('#plan-status').textContent(),/直接回答|一次回答/);
 assert.deepEqual(errors,[]);
 console.log('PASS: legacy missing days remain incomplete, guide failures are visible, mixed research results are accurately described, explicit removal creates persistent free time, adding back clears it, and partial generation preserves the old route without fake follow-up prompts.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
