import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {initialState} from '../public/src/travel-state.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';

const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州一天每天六小时'}).profile;
const plan=buildDailyPlan({...planFromCatalog(normalizeRequest({destination:'广州',hours:6}),undefined,{placeIds:['gz-museum','gz-square']}),mode:'ai',trace:[]},profile);
plan.guide={status:'ready',summary:'先参观，再漫步城市公共空间。',days:[{dayIndex:1,overview:'上午看展、午后散步，路线中的开放与交通条件还需出发前核实。',stops:plan.stops.map(stop=>({stopId:stop.id,name:stop.name,howToPlay:'先在入口看清导览和临时公告，再按自己的兴趣选择常设展或建筑外观。每一站留出拍照和休息时间，不必赶着把所有内容看完。遇到需要预约的活动，以官方当天发布的信息为准。',highlights:['展览主题与当地文化','建筑细节与城市公共空间'],food:[{name:'附近粤菜或粥粉面',note:'优先选择顺路步行可达的店铺。餐饮地址和营业状态出发前核实；如遇排队，先在附近休息，再决定是否继续等待。',sourceIds:[]}],transport:'先核对出入口，再用地图查实际步行路线；下雨可按情况选择公共交通。',reservation:'提前核对官方预约规则、身份证件与当天开放时间。',rainyAlternative:'优先留在室内展馆，户外散步按天气调整，不必强行赶路。',sourceIds:[]}))}],sources:[],warnings:['费用、营业和预约仍需临行核实。']};
const saved=JSON.stringify({...initialState(),profile,plan}),server=createApp({accountsEnabled:false,key:'',fetchImpl:async()=>{throw Error('No external calls');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true}),root=`http://127.0.0.1:${server.address().port}`,observations=[],failures=[];
try{
  const page=await browser.newPage({viewport:{width:1146,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',error=>errors.push(error.message));
  page.setDefaultTimeout(5000);await page.addInitScript(saved=>{localStorage.setItem('lvzang.v1',saved);},saved);
  await page.route('**/*',route=>route.request().url().startsWith(root+'/')?route.continue():route.abort());
  const snapshot=()=>page.evaluate(()=>{
    const item=selector=>{const node=document.querySelector(selector),r=node.getBoundingClientRect(),style=getComputedStyle(node);return {scrollTop:node.scrollTop,clientHeight:node.clientHeight,scrollHeight:node.scrollHeight,top:r.top,bottom:r.bottom,left:r.left,right:r.right,overflow:style.overflowY,overscroll:style.overscrollBehaviorY};};
    return {guide:item('#guide-pane'),content:item('.itinerary-content'),sources:item('#sources-node'),outer:scrollY,pageHeight:document.documentElement.scrollHeight,viewportHeight:innerHeight};
  });
  const settle=()=>page.waitForTimeout(100);
  const prepare=async width=>{
    await page.setViewportSize({width,height:900});await page.goto(root+'/travel.html');await page.waitForSelector('.stop-guide');
    // Bring the workspace into view once; all scrolling being asserted below is
    // generated by real wheel input, never by assigning element.scrollTop.
    await page.locator('#canvas-viewport').scrollIntoViewIfNeeded();await settle();
  };
  const wheelAt=async(selector,delta)=>{
    const point=await page.locator(selector).evaluate(node=>{const rect=node.getBoundingClientRect(),pane=document.getElementById('guide-pane').getBoundingClientRect();const top=Math.max(rect.top,pane.top,0),bottom=Math.min(rect.bottom,pane.bottom,innerHeight);return bottom>top?{x:(Math.max(rect.left,pane.left)+Math.min(rect.right,pane.right))/2,y:(top+bottom)/2}:null;});
    if(!point)return false;await page.mouse.move(point.x,point.y);await page.mouse.wheel(0,delta);await settle();return true;
  };
  for(const width of [1146,1440,580,390]){
    for(const [area,selector]of [['header','#route-section > .node-header'],['content','.itinerary-content']]){
      await prepare(width);const before=await snapshot(),hit=await wheelAt(selector,350),after=await snapshot();observations.push({width,area,hit,before,after});
      if(!hit||after.guide.scrollTop<=before.guide.scrollTop+30)failures.push(`${width}px ${area}: wheel must move the whole guide pane, got pane ${before.guide.scrollTop}→${after.guide.scrollTop}, nested ${before.content.scrollTop}→${after.content.scrollTop}, page ${before.outer}→${after.outer}`);
    }
    await prepare(width);
    for(let n=0;n<12;n++){
      const state=await snapshot();if(state.sources.top<Math.min(900,state.guide.bottom)-20&&state.sources.bottom>Math.max(0,state.guide.top)+20)break;
      if(!await wheelAt('#guide-pane',700))break;
    }
    const before=await snapshot(),hit=await wheelAt('#sources-node',-200),after=await snapshot();observations.push({width,area:'references',hit,before,after});
    if(!hit||after.guide.scrollTop>=before.guide.scrollTop-30)failures.push(`${width}px references: sources must be reachable and wheel over them must scroll the same guide pane; hit=${hit}, pane ${before.guide.scrollTop}→${after.guide.scrollTop}`);
    if(width<768){
      await prepare(width);const boundary=await snapshot();assert.equal(boundary.guide.scrollTop,0,'Start at the top boundary of the guide');
      await wheelAt('#guide-pane',-400);const chained=await snapshot();observations.push({width,area:'boundary-to-page',before:boundary,after:chained});
      if(boundary.outer<=0||chained.outer>=boundary.outer-30)failures.push(`${width}px boundary: wheel at the top of the guide must continue to the outer page; page ${boundary.outer}→${chained.outer}`);
    }
    assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),saved,'Wheel navigation does not alter the accepted trip');
  }
  await mkdir('artifacts/map-advisor',{recursive:true});await writeFile('artifacts/map-advisor/guide-scroll-geometry.json',JSON.stringify(observations,null,2));
  assert.deepEqual(errors,[]);assert.deepEqual(failures,[],'Wheel must scroll the complete guide rather than trapping users in nested regions');
  assert.equal(await page.locator('#guide-pane #route-refresh-slot').count(),0,'The global refresh action is outside the guide scroll surface');
  console.log('PASS: header, content and references scroll one guide pane at 1146/1440/580/390; global refresh is separate; narrow boundaries chain to the outer page; trip bytes unchanged.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
