import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {initialState} from '../public/src/travel-state.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';

const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州一天每天六小时',patch:{destination:'广州',dayCount:1,dailyHours:6}}).profile;
const plan=buildDailyPlan({...planFromCatalog(normalizeRequest({destination:'广州',hours:6}),undefined,{placeIds:['gz-museum','gz-square']}),mode:'ai',trace:[]},profile);
plan.guide={status:'ready',summary:'文化与城市漫游',days:[{dayIndex:1,overview:'上午看展，下午散步；中间安排午饭。',stops:plan.stops.map(stop=>({stopId:stop.id,name:stop.name,howToPlay:'先看主题展，再按兴趣选择常设展，累了就在休息区歇一会。',highlights:['建筑外观与展览主题'],food:[{name:'附近粤菜或粥粉面',note:'优先选择步行可达店铺，营业状态出发前核实。',sourceIds:[]}],transport:'步行到下一站，准确距离请用高德地图查询。',reservation:'核对官方预约规则。',rainyAlternative:'留在室内展馆或附近商场。',sourceIds:[]}))}],sources:[],warnings:[]};
const saved=JSON.stringify({...initialState(),profile,plan}),key='lvzang.guide-layout.v1';
const server=createApp({key:'',fetchImpl:async()=>{throw Error('No external request');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const root=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1146,height:704},hasTouch:true}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(saved=>{if(!localStorage.getItem('lvzang.v1'))localStorage.setItem('lvzang.v1',saved);},saved);
 await page.goto(root+'/travel.html');await page.waitForSelector('.stop-guide');
 const geometry=()=>page.evaluate(()=>{const node=document.querySelector('#route-section'),world=document.querySelector('#canvas-world'),body=document.querySelector('.stop-guide'),rect=node.getBoundingClientRect();return {width:node.offsetWidth,height:node.offsetHeight,x:Number(node.dataset.x),y:Number(node.dataset.y),scale:world.getBoundingClientRect().width/world.offsetWidth,transform:world.style.transform,font:parseFloat(getComputedStyle(body).fontSize),screenWidth:rect.width,screenHeight:rect.height};});
 const before=await geometry();console.log('Guide initial layout',before);
 const overlayHit=await page.evaluate(()=>{const card=document.querySelector('#route-section').getBoundingClientRect(),button=document.querySelector('#map-use-location').getBoundingClientRect();const left=Math.max(card.left,button.left),right=Math.min(card.right,button.right),top=Math.max(card.top,button.top),bottom=Math.min(card.bottom,button.bottom);return right>left&&bottom>top?document.elementFromPoint((left+right)/2,(top+bottom)/2)?.closest('button')?.id:null;});
 assert.notEqual(overlayHit,'map-use-location','Map controls cannot escape through the overlapping guide card');
 assert.equal(await page.locator('#guide-resize-handle').count(),1,'Guide has an independent resize control');
 assert.ok(before.font*before.scale>=17.9,'18px reading size remains readable after canvas zoom');
 assert.ok(before.screenWidth>=319,'Initial reading column has a usable real screen width');
 assert.ok(await page.locator('#guide-font-size').evaluate(node=>parseFloat(getComputedStyle(node).fontSize)*(document.querySelector('#canvas-world').getBoundingClientRect().width/document.querySelector('#canvas-world').offsetWidth)>=13.9),'Font controls stay readable at the current scale');
 const originalState=await page.evaluate(()=>localStorage.getItem('lvzang.v1'));
 const grip=page.locator('#guide-resize-handle');await grip.scrollIntoViewIfNeeded();
 const box=await grip.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2-125,box.y+box.height/2+35,{steps:10});await page.mouse.up();
 const resized=await geometry();assert.ok(resized.screenWidth>before.screenWidth+100,'Left handle drag widens the card at the current canvas scale');assert.ok(resized.screenHeight>before.screenHeight+20,'Vertical drag changes its independent height');
 assert.equal(resized.transform,before.transform,'Resizing does not pan or zoom the whole canvas');assert.equal(resized.y,before.y);assert.ok(resized.x<before.x,'Card grows to the left from its right edge');
 assert.equal(await page.evaluate(()=>{const route=document.querySelector('#route-section'),sources=document.querySelector('#sources-node');return Number(sources.dataset.y)>=Number(route.dataset.y)+route.offsetHeight+17;}),true,'Reference card follows the resized itinerary without overlap');
 assert.equal(await page.locator('#canvas-viewport').evaluate(node=>node.classList.contains('is-dragging')),false);
 await page.locator('#guide-font-size').selectOption('20');const bigger=await geometry();assert.ok(bigger.font*bigger.scale>=19.9);assert.equal(bigger.transform,before.transform);
 const preferences=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);assert.equal(preferences.fontSize,20);assert.ok(preferences.width>before.width);
 await page.reload();await page.waitForSelector('.stop-guide');assert.equal(await page.locator('#guide-font-size').inputValue(),'20');const restored=await geometry();assert.ok(Math.abs(restored.width-resized.width)<2,'Chosen width survives reload');assert.ok(Math.abs(restored.height-resized.height)<2,'Chosen height survives reload');
 assert.equal(await page.evaluate(()=>localStorage.getItem('lvzang.v1')),originalState,'Reading preferences never change the accepted trip');
 await page.locator('#guide-resize-handle').focus();const keyboardBefore=await geometry();await page.keyboard.press('ArrowLeft');const keyboardAfter=await geometry();assert.ok(keyboardAfter.width>keyboardBefore.width,'Keyboard can widen the card');assert.equal(keyboardAfter.transform,keyboardBefore.transform);
 await page.locator('#guide-reset-layout').click();assert.equal(await page.locator('#guide-font-size').inputValue(),'18');assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),null);
 await page.locator('#zoom-out').click();await page.locator('#zoom-out').click();await page.waitForFunction(()=>{const world=document.querySelector('#canvas-world');return parseFloat(getComputedStyle(document.querySelector('.stop-guide')).fontSize)*world.getBoundingClientRect().width/world.offsetWidth>=17.9;});const zoomed=await geometry();assert.ok(zoomed.font*zoomed.scale>=17.9,'Reading size stays legible at a smaller canvas zoom');
 await mkdir('artifacts/guide-layout',{recursive:true});await page.screenshot({path:'artifacts/guide-layout/desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('#route-section').scrollIntoViewIfNeeded();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile layout does not overflow horizontally');
 const mobile=await geometry();assert.ok(mobile.screenWidth<=390-20);assert.ok(mobile.font>=15.9);
 await page.locator('#guide-font-size').selectOption('22');assert.equal(await page.locator('#guide-font-size').inputValue(),'22');
 const touch=await page.context().newCDPSession(page);await page.locator('#guide-resize-handle').scrollIntoViewIfNeeded();const mobileGrip=await page.locator('#guide-resize-handle').boundingBox(),mobileBefore=await geometry();
 const touchPoint={x:Math.round(mobileGrip.x+mobileGrip.width/2),y:Math.round(mobileGrip.y+mobileGrip.height/2)};
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touchPoint]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...touchPoint,y:touchPoint.y-65}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const mobileAfter=await geometry();assert.ok(mobileAfter.height<mobileBefore.height-50,'Touch drag changes the card height');assert.equal(mobileAfter.screenWidth,mobileBefore.screenWidth);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('#route-section').screenshot({path:'artifacts/guide-layout/mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: scaled readable guide, independent pointer/keyboard resize, font controls, persistence, reset, mobile bounds and unchanged itinerary.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
