import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {emptyTravelProfile,updateTravelProfile} from '../public/src/travel-profile.js';
import {initialState} from '../public/src/travel-state.js';
import {normalizeRequest,planFromCatalog} from '../public/src/travel-domain.js';
import {buildDailyPlan} from '../public/src/travel-schedule.js';
const profile=updateTravelProfile(emptyTravelProfile(),{text:'广州三天，每天6小时，两个人，每人全程600元，正常节奏，必去花城广场和广州塔'}).profile;
const base=planFromCatalog(normalizeRequest({description:'广州一天',hours:6}),undefined,{placeIds:['gz-museum','gz-square','gz-tower','gz-opera']});
const plan=buildDailyPlan({...base,mode:'ai',trace:[],stops:base.stops.map(stop=>({...stop,dayIndex:stop.id==='gz-museum'?1:stop.id==='gz-opera'?3:2,transit:15}))},profile);
const saved={...initialState(),profile,plan};let providerCalls=0;
const server=createApp({accountsEnabled:false,advisorEnabled:true,key:'fixture',tripoKey:'',amapJsKey:'',amapSecurityJsCode:'',fetchImpl:async()=>{providerCalls++;throw Error('Local day edits and demo revisions must not call a provider');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const root=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage({viewport:{width:1500,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/*',route=>route.request().url().startsWith(root+'/')?route.continue():route.abort());await page.goto(root+'/travel.html');
 await page.evaluate(value=>localStorage.setItem('lvzang.v1',JSON.stringify(value)),saved);await page.reload();
 const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('lvzang.v1'))),submit=async text=>{await page.locator('#travel-brief').fill(text);await page.getByRole('button',{name:'发送消息',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled);};
 const mode=async value=>{await page.locator('.plan-options summary').click();await page.locator('#agent-mode').selectOption(value);await page.locator('.plan-options summary').click();};
 await mode('ai');await submit('第2天只玩2小时，下午14:00出发，轻松一点');
 const edited=(await state()).plan;assert.equal(edited.days[1].hours,2);assert.equal(edited.days[1].pace,'easy');assert.deepEqual(edited.dayOverrides,{'2':{hours:2,pace:'easy',startTime:'14:00'}});assert.equal(edited.mode,'ai');
 assert.equal(JSON.stringify(edited.days[0]),JSON.stringify(plan.days[0]));assert.equal(JSON.stringify(edited.days[2]),JSON.stringify(plan.days[2]));assert.deepEqual((await state()).profile,profile);assert.equal((await state()).profile.fields.dayCount.value,3);
 assert.ok(edited.days[1].stops.some(stop=>stop.id==='gz-tower'));assert.ok(edited.days[1].stops.some(stop=>stop.id==='gz-square'));assert.equal(providerCalls,0);
 assert.equal(await page.locator('[data-day="1"]').getAttribute('aria-pressed'),'true','successful local edit automatically opens the changed day');assert.match(await page.locator('#time-detail').textContent(),/2小时/);assert.match(await page.locator('#time-value').textContent(),/14:00.*16:00/s);
 await page.reload();assert.deepEqual((await state()).plan.dayOverrides,edited.dayOverrides);assert.equal((await state()).plan.days[1].hours,2);assert.equal(await page.locator('#storage-recovery').isVisible(),false);
 const stable=JSON.stringify((await state()).plan);await mode('ai');await submit('第二天只玩1小时');assert.equal(JSON.stringify((await state()).plan),stable);assert.match(await page.locator('.chat-message.assistant').last().textContent(),/必去|无法/);assert.deepEqual((await state()).profile,profile);
 await mode('demo');await submit('预算改为每人全程500元');
 const budget=(await state()).plan;assert.equal((await state()).profile.fields.budget.value.amount,500);assert.deepEqual(budget.dayOverrides,edited.dayOverrides);assert.equal(budget.days[1].hours,2);assert.equal(budget.days[1].pace,'easy');
 for(const index of [0,2])assert.equal(JSON.stringify(budget.days[index]),JSON.stringify(edited.days[index]));
 await page.reload();assert.deepEqual((await state()).plan.dayOverrides,edited.dayOverrides);
 await page.locator('#trip-daily-hours').fill('4');await page.getByRole('button',{name:'应用并调整行程',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled);
 assert.deepEqual((await state()).plan.dayOverrides,{'2':{pace:'easy',startTime:'14:00'}});assert.equal((await state()).profile.fields.dailyHours.value,4);assert.ok((await state()).plan.days.every(day=>day.hours===4));
 await mode('ai');await submit('第2天只玩2小时');assert.equal((await state()).plan.dayOverrides['2'].hours,2);
 await mode('demo');await submit('每天改为5小时');assert.deepEqual((await state()).plan.dayOverrides,{'2':{pace:'easy',startTime:'14:00'}});assert.ok((await state()).plan.days.every(day=>day.hours===5));
 await page.locator('#trip-pace').selectOption('active');await page.getByRole('button',{name:'应用并调整行程',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled);assert.deepEqual((await state()).plan.dayOverrides,{'2':{startTime:'14:00'}});
 await mode('demo');await submit('每天09:00开始');assert.deepEqual((await state()).plan.dayOverrides,{});assert.ok((await state()).plan.days.every(day=>day.startTime==='09:00'));
 await mode('ai');await submit('第2天只玩3小时');assert.equal((await state()).plan.dayOverrides['2'].hours,3);
 await page.locator('#trip-day-count').fill('2');await page.getByRole('button',{name:'应用并调整行程',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled);assert.deepEqual((await state()).plan.dayOverrides,{});assert.equal((await state()).profile.fields.dayCount.value,2);assert.equal((await state()).plan.days.length,2);
 await page.reload();assert.equal(await page.locator('#storage-recovery').isVisible(),false);assert.equal((await state()).plan.days.length,2);assert.equal(providerCalls,0);assert.deepEqual(errors,[]);
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mkdir('artifacts/map-advisor',{recursive:true});await page.screenshot({path:'artifacts/map-advisor/day-edit-mobile.png',fullPage:true});
 console.log('PASS: actual HTTP stream AI day2 edit performs no model calls and opens day2 at14:00-16:00; other days and global profile unchanged; mandatory-capacity refusal preserves plan; refresh and demo budget retain local hours/pace; explicit global form and natural-language hours, pace and day count clear only corresponding overrides; refresh/mobile.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
