import assert from 'node:assert/strict';
import test from 'node:test';
import {layoutLandmarks} from '../public/src/travel-map-layout.js';

const rect=(item,offset)=>({left:item.x+offset.dx-item.width/2,right:item.x+offset.dx+item.width/2,top:item.y+offset.dy-item.height,bottom:item.y+offset.dy});
const overlaps=(a,b,gap=12)=>!(a.right+gap<=b.left+1e-7||b.right+gap<=a.left+1e-7||a.bottom+gap<=b.top+1e-7||b.bottom+gap<=a.top+1e-7);
function bounds(items,result,{width,height,top=90,bottom=32}){result.forEach((offset,index)=>{assert.ok(Number.isFinite(offset.dx)&&Number.isFinite(offset.dy));const box=rect(items[index],offset);assert.ok(box.left>=-1e-7&&box.right<=width+1e-7);assert.ok(box.top>=top-1e-7&&box.bottom<=height-bottom+1e-7);});}
function separate(items,result){const boxes=items.map((item,index)=>rect(item,result[index]));for(let index=0;index<boxes.length;index++)for(let next=index+1;next<boxes.length;next++)assert.equal(overlaps(boxes[index],boxes[next]),false,`landmarks ${index} and ${next} overlap`);}
const near=[{id:'museum',x:248,y:253,width:116,height:161},{id:'square',x:317,y:257,width:116,height:161},{id:'opera',x:284,y:179,width:116,height:161}];

test('actual close Guangzhou anchors fit without overlap or covering controls',()=>{const area={width:502,height:360},result=layoutLandmarks(near,area);bounds(near,result,area);separate(near,result);assert.ok(result.some(offset=>offset.dx||offset.dy));});
test('wide separated legal anchors retain zero offsets',()=>{const items=[{id:'a',x:120,y:300,width:116,height:161},{id:'b',x:500,y:400,width:116,height:161},{id:'c',x:880,y:600,width:116,height:161}];assert.deepEqual(layoutLandmarks(items,{width:1000,height:700}),items.map(({id})=>({id,dx:0,dy:0})));});
test('single legal marker stays at its real point; near-controls marker shifts inside',()=>{const item={id:'only',x:250,y:300,width:116,height:161},area={width:502,height:360};assert.deepEqual(layoutLandmarks([item],area),[{id:'only',dx:0,dy:0}]);const high={...item,y:150},result=layoutLandmarks([high],area);bounds([high],result,area);assert.equal(result[0].dx,0);assert.equal(result[0].dy,101);});
test('fully offscreen POIs are never pulled back into view',()=>{const items=[{id:'left',x:-500,y:253,width:116,height:161},{id:'right',x:1500,y:253,width:116,height:161},{id:'above',x:250,y:-200,width:116,height:161},{id:'below',x:250,y:900,width:116,height:161}];assert.deepEqual(layoutLandmarks(items,{width:502,height:360}),items.map(({id})=>({id,dx:0,dy:0})));});
test('layout is deterministic, independent of input ordering, and immutable',()=>{const original=structuredClone(near),area={width:502,height:360},first=layoutLandmarks(near,area);assert.deepEqual(layoutLandmarks(near,area),first);const reversed=layoutLandmarks([...near].reverse(),area);const byId=value=>[...value].sort((a,b)=>a.id.localeCompare(b.id));assert.deepEqual(byId(reversed),byId(first));assert.deepEqual(near,original);});
test('mobile dimensions fit three close landmarks in a narrow map',()=>{const items=near.map(item=>({...item,x:item.x*.6,y:item.y+30,width:96,height:133})),area={width:342,height:420},result=layoutLandmarks(items,area);bounds(items,result,area);separate(items,result);});
test('insufficient space degrades to finite bounded placement without looping',()=>{const items=near.map(item=>({...item,x:90,y:260,width:96,height:133})),area={width:180,height:360},result=layoutLandmarks(items,area);bounds(items,result,area);assert.ok(overlaps(rect(items[0],result[0]),rect(items[1],result[1]))||overlaps(rect(items[0],result[0]),rect(items[2],result[2]))||overlaps(rect(items[1],result[1]),rect(items[2],result[2])));});
test('twelve clustered markers use bounded slots and leave legal distant marker alone',()=>{const items=Array.from({length:12},(_,index)=>({id:String(index),x:430+index,y:300+index,width:96,height:133})),area={width:1000,height:700},result=layoutLandmarks(items,area);bounds(items,result,area);separate(items,result);const distant={id:'distant',x:80,y:500,width:96,height:133};const mixed=layoutLandmarks([...near,distant],{width:1000,height:700});assert.deepEqual(mixed.at(-1),{id:'distant',dx:0,dy:0});separate([...near,distant],mixed);});
test('empty, malformed and oversized input remains finite',()=>{assert.deepEqual(layoutLandmarks([],{width:502,height:360}),[]);const items=[{id:'bad',x:NaN,y:1,width:96,height:133},{id:'oversized',x:100,y:150,width:300,height:500}];const result=layoutLandmarks(items,{width:180,height:300});assert.ok(result.every(offset=>Number.isFinite(offset.dx)&&Number.isFinite(offset.dy)));assert.deepEqual(result[0],{id:'bad',dx:0,dy:0});assert.deepEqual(layoutLandmarks(items,{width:0,height:0}),items.map(({id})=>({id,dx:0,dy:0})));});
test('eight Guangzhou miniatures remain independently clickable below two-row mobile controls',()=>{const items=Array.from({length:8},(_,index)=>({id:String(index),x:180+index*3,y:360+index*2,width:96,height:130})),area={width:340,height:620,top:160,bottom:32},result=layoutLandmarks(items,area);bounds(items,result,area);separate(items,result);});
