// NODE_PATH=<bundled node_modules> node tests/trip.browser.js
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import sharp from 'sharp';
import { mkdir } from 'node:fs/promises';
import { createApp } from '../server.js';
import { createDesign } from '../public/src/design.js';
const {chromium}=createRequire(import.meta.url)('playwright');
const red=await sharp({create:{width:120,height:90,channels:3,background:'#c85e49'}}).png().toBuffer();
const blue=await sharp({create:{width:120,height:90,channels:3,background:'#537fba'}}).png().toBuffer();
const image='data:image/png;base64,'+red.toString('base64');
const ring=Buffer.alloc(120*90*4);for(let y=0;y<90;y++)for(let x=0;x<120;x++){const i=(y*120+x)*4;ring[i]=83;ring[i+1]=127;ring[i+2]=186;ring[i+3]=x>40&&x<80&&y>28&&y<62?0:255;}
const ringImage='data:image/png;base64,'+(await sharp(ring,{raw:{width:120,height:90,channels:4}}).png().toBuffer()).toString('base64');
const server=createApp({key:'',tripoKey:''});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  let cutouts=0,failCutout=false,artworks=0;
  await page.route('**/api/**',async route=>{
    const path=new URL(route.request().url()).pathname;
    if(path==='/api/agent')return route.continue();
    if(path==='/api/trip-cutout'){
      assert.ok(Number.isFinite(JSON.parse(route.request().postData()).point?.x));
      cutouts++;if(failCutout){failCutout=false;return route.fulfill({status:502,json:{error:'模拟分割失败'}});}
      return route.fulfill({json:{kind:'subject',cutout:image}});
    }
    if(path==='/api/trip-painting')return route.fulfill({status:502,json:{error:'模拟生图失败'}});
    const photos=path==='/api/trip-curation'?JSON.parse(route.request().postData()).photos:[];
    const json=path==='/api/config'?{configured:true,tripoConfigured:true}:path==='/api/trip-curation'?{points:photos.map((photo,index)=>({photoId:photo.id,title:`片段 ${index+1}`,evidence:`照片 ${index+1} 可见`,storyDraft:`照片 ${index+1} 的故事`,cutoutPrompt:'可见的物件',cutoutKind:'subject',cutoutPoint:{x:.5,y:.5}}))}:path==='/api/design'?{design:{...createDesign({story:'旅行的一天'}),brief:{summary:'旅行记忆',elements:['旅行照片'],composition:'纪念这一刻',imagePrompt:'旅行纪念物'}}}:path==='/api/artwork'?{taskId:`art-${++artworks}`}:{status:'success',image};
    await route.fulfill({json});
  });
  const root=`http://127.0.0.1:${server.address().port}`;
  await page.route('**/seed',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>seed</title>'}));
  await page.goto(root+'/seed');
  await page.evaluate(image=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',1);request.onupgradeneeded=()=>request.result.createObjectStore('artworks',{keyPath:'id'});request.onsuccess=()=>{const db=request.result,tx=db.transaction('artworks','readwrite');tx.objectStore('artworks').put({id:'old',createdAt:1,image,design:{caption:'旧作品'},input:{place:'广州'}});tx.oncomplete=()=>{db.close();resolve();};};}),image);
  await page.goto(root);await page.locator('.history summary').click();await page.locator('.history-card').waitFor();assert.equal(await page.locator('.history-card').count(),1);
  await page.locator('#trip-name').fill('海边两日');
  await page.locator('#trip-photos').setInputFiles([{name:'a.png',mimeType:'image/png',buffer:red},{name:'b.png',mimeType:'image/png',buffer:blue}]);
  await page.waitForFunction(()=>document.querySelectorAll('.trip-upload-thumb').length===2);
  await page.locator('#trip-curate').click();await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('模拟生图失败'));
  assert.equal(cutouts,2);assert.equal(await page.locator('#trip-gallery').isHidden(),true);
  await mkdir('artifacts',{recursive:true});await page.locator('#trip-collage').screenshot({path:'artifacts/trip-collage.png'});
  const canvas=page.locator('#trip-collage'),box=await canvas.boundingBox();
  await canvas.click({position:{x:box.width*.55,y:box.height*.57}});await page.locator('#trip-detail[open]').waitFor();
  assert.equal(await page.locator('#trip-detail-title').textContent(),'片段 1');
  assert.equal(await page.locator('#trip-detail-image').getAttribute('src'),await page.locator('.trip-upload-thumb[data-photo-id="p1"] img').getAttribute('src'));
  await page.locator('#trip-detail-close').click();
  await page.locator('.trip-point-editor').nth(1).locator('.trip-point-story').fill('我和妈妈在海边吹风');
  await page.locator('.trip-point-editor').nth(1).locator('.trip-point-story').blur();
  await page.locator('#trip-edit-collage').click();await page.getByRole('button',{name:'打开片段：片段 2'}).click();
  await canvas.scrollIntoViewIfNeeded();const editBox=await canvas.boundingBox();
  await page.mouse.move(editBox.x+editBox.width*.2,editBox.y+editBox.height*.56);
  await page.mouse.down();await page.mouse.move(editBox.x+editBox.width*.27,editBox.y+editBox.height*.63,{steps:5});await page.mouse.up();
  await page.locator('#trip-piece-scale').fill('130');await page.locator('#trip-piece-scale').dispatchEvent('change');
  await page.locator('#trip-recut').click();await page.locator('#trip-recut-image').click({position:{x:30,y:25}});
  await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('已重新抠取'));assert.equal(cutouts,3);
  await page.reload();await page.locator('.trip-library-card').filter({hasText:'海边两日'}).locator('.trip-open').click();
  await page.waitForFunction(()=>document.querySelectorAll('#trip-piece-list button').length===2);
  const piece=await page.evaluate(()=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,get=db.transaction('trips').objectStore('trips').getAll();get.onsuccess=()=>{db.close();resolve(get.result.find(t=>t.name==='海边两日').memories.find(m=>m.photoId==='p2').piece);};};}));
  assert.equal(piece.scale,1.3);assert.ok(piece.point);assert.ok(piece.x>.2,`dragged placement survives reload: ${piece.x}`);
  await page.getByRole('button',{name:'打开片段：片段 2'}).click();assert.equal(await page.locator('#trip-detail-story').textContent(),'我和妈妈在海边吹风');
  assert.equal(await page.locator('#trip-model-panel').isHidden(),true,'an unmodeled memory stays a compact story card');
  assert.ok((await page.locator('#trip-detail').boundingBox()).width<650);
  assert.ok(Math.abs(await page.locator('#trip-detail').evaluate(node=>node.getBoundingClientRect().width/node.offsetWidth)-.7)<.01,'desktop card is scaled to 70%');
  assert.equal(await page.locator('#trip-detail-card-title').textContent(),'片段 2');
  await page.locator('#trip-detail').screenshot({path:'artifacts/trip-detail-compact.png'});
  await page.locator('#trip-make-object').click();await page.waitForFunction(()=>document.getElementById('story').value==='我和妈妈在海边吹风');
  await page.locator('#generate').click();await page.locator('#build-reference').waitFor({state:'visible',timeout:15000});
  await page.locator('#return-trip').click();await page.getByRole('button',{name:'打开片段：片段 2'}).click();
  await page.waitForFunction(()=>document.getElementById('trip-object-status').textContent.includes('参考图'));
  assert.equal(await page.locator('#trip-model-panel').isHidden(),true,'a reference image is not a finished 3D model');
  await page.locator('#trip-detail-close').click();await page.getByRole('button',{name:'打开片段：片段 1'}).click();
  await page.waitForFunction(()=>document.getElementById('trip-object-status').textContent.includes('尚未制作'));
  assert.match(await page.locator('#trip-object-status').textContent(),/尚未制作/);assert.equal(artworks,1);
  await page.locator('#trip-detail-close').click();
  await page.evaluate(image=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,get=db.transaction('trips').objectStore('trips').getAll();get.onsuccess=()=>{const trip=get.result.find(item=>item.name==='海边两日'),point=trip.memories.find(item=>item.photoId==='p1'),tx=db.transaction('artworks','readwrite');tx.objectStore('artworks').put({id:'modeled-memory',createdAt:Date.now()+1000,tripId:trip.id,memoryId:point.id,image,design:{caption:point.title},sculpture:{mesh:new Float32Array([-25,-15,5,25,-15,5,0,25,5]),widthMm:60,heightMm:40,totalDepthMm:5,exportable:true}});tx.oncomplete=()=>{db.close();resolve();};};};}),image);
  await page.evaluate(image=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,get=db.transaction('trips').objectStore('trips').getAll();get.onsuccess=()=>{const trip=get.result.find(item=>item.name==='海边两日'),point=trip.memories.find(item=>item.photoId==='p2'),tx=db.transaction('artworks','readwrite');tx.objectStore('artworks').put({id:'modeled-memory-2',createdAt:Date.now()+1001,tripId:trip.id,memoryId:point.id,image,design:{caption:point.title},sculpture:{mesh:new Float32Array([-20,-15,5,20,-15,5,0,30,5]),widthMm:60,heightMm:40,totalDepthMm:5,exportable:true}});tx.oncomplete=()=>{db.close();resolve();};};};}),image);
  await page.evaluate(()=>window.dispatchEvent(new Event('trip-artifact-saved')));
  await page.waitForFunction(()=>[...document.querySelectorAll('.trip-model-card canvas')].length===2&&[...document.querySelectorAll('.trip-model-card canvas')].every(canvas=>canvas.width>1));
  assert.equal(await page.locator('#trip-piece-list > button').count(),0,'completed models replace text cards');
  assert.deepEqual(await page.locator('.trip-model-open').allTextContents(),['片段 2','片段 1']);
  const showcaseFrames=await page.locator('.trip-model-card canvas').evaluateAll(canvases=>canvases.map(canvas=>canvas.toDataURL()));
  await page.waitForTimeout(180);
  const laterFrames=await page.locator('.trip-model-card canvas').evaluateAll(canvases=>canvases.map(canvas=>canvas.toDataURL()));
  laterFrames.forEach((frame,index)=>assert.notEqual(frame,showcaseFrames[index],`3D card ${index+1} rotates independently`));
  await page.locator('.trip-art-layout').screenshot({path:'artifacts/trip-showcase.png'});
  await page.goto(root+'/simple.html');await page.locator('.trip-library-card').filter({hasText:'海边两日'}).locator('.trip-open').click();
  await page.locator('.trip-model-card').first().waitFor({state:'visible'});
  const simpleModel=await page.locator('.trip-model-card').first().boundingBox(),simpleArt=await page.locator('#trip-collage-wrap').boundingBox();
  assert.ok(simpleModel.x<simpleArt.x,'simple desktop layout keeps the 3D model beside the painting');
  await page.goto(root);await page.locator('.trip-library-card').filter({hasText:'海边两日'}).locator('.trip-open').click();
  await page.getByRole('button',{name:'打开片段：片段 1'}).click();await page.locator('#trip-model-panel').waitFor({state:'visible'});
  assert.ok((await page.locator('#trip-detail').boundingBox()).width>750,'finished 3D expands the detail card');
  assert.ok(Math.abs(await page.locator('#trip-detail').evaluate(node=>node.getBoundingClientRect().width/node.offsetWidth)-.7)<.01,'3D card is scaled to 70%');
  assert.equal(await page.locator('#trip-model-canvas').isVisible(),true);
  assert.match(await page.locator('#trip-open-object').textContent(),/打开作品与导出/);
  await page.waitForFunction(()=>document.getElementById('trip-model-motion').textContent.includes('自动慢转')&&document.getElementById('trip-model-canvas').width>1);
  const firstFrame=await page.locator('#trip-model-canvas').evaluate(canvas=>canvas.toDataURL());
  await page.waitForTimeout(180);
  assert.notEqual(await page.locator('#trip-model-canvas').evaluate(canvas=>canvas.toDataURL()),firstFrame,'3D rotates automatically');
  await page.locator('#trip-detail').screenshot({path:'artifacts/trip-detail-model.png'});
  await page.locator('[data-trip-view="front"]').click();
  assert.equal(await page.locator('[data-trip-view="front"]').getAttribute('aria-pressed'),'true');
  const stoppedFrame=await page.locator('#trip-model-canvas').evaluate(canvas=>canvas.toDataURL());
  await page.waitForTimeout(100);
  assert.equal(await page.locator('#trip-model-canvas').evaluate(canvas=>canvas.toDataURL()),stoppedFrame,'manual view pauses rotation');
  const modelBox=await page.locator('#trip-model-canvas').boundingBox();
  await page.mouse.move(modelBox.x+modelBox.width*.5,modelBox.y+modelBox.height*.5);await page.mouse.down();await page.mouse.move(modelBox.x+modelBox.width*.65,modelBox.y+modelBox.height*.55,{steps:5});await page.mouse.up();
  assert.notEqual(await page.locator('#trip-model-canvas').evaluate(canvas=>canvas.toDataURL()),stoppedFrame,'drag rotates the model');
  await page.setViewportSize({width:390,height:844});
  assert.ok((await page.locator('#trip-detail').boundingBox()).width<=390,'3D detail fits a phone viewport');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.locator('#trip-detail').screenshot({path:'artifacts/trip-detail-mobile.png'});
  await page.setViewportSize({width:1280,height:720});
  await page.locator('#trip-detail-close').click();await page.locator('#trip-cover-select').selectOption('p2');
  await page.waitForFunction(()=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,get=db.transaction('trips').objectStore('trips').getAll();get.onsuccess=()=>{db.close();resolve(get.result.find(item=>item.name==='海边两日')?.coverId==='p2');};};}));
  await page.reload();await page.locator('.trip-library-card').filter({hasText:'海边两日'}).locator('.trip-open').click();
  await page.waitForFunction(()=>document.getElementById('trip-cover-select').value==='p2');
  assert.equal(await page.locator('#trip-cover-select').inputValue(),'p2','new cover persists');
  await page.locator('#trip-new').click();
  await page.locator('#trip-photos').setInputFiles(Array.from({length:9},(_,index)=>({name:`${index}.png`,mimeType:'image/png',buffer:index%2?blue:red})));
  await page.waitForFunction(()=>document.querySelectorAll('.trip-upload-thumb').length===9);
  failCutout=true;await page.locator('#trip-curate').click();await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('模拟生图失败'));
  assert.equal(await page.locator('#trip-piece-list button').count(),3);
  assert.equal(await page.locator('#trip-cabinet-grid .trip-cabinet-card').count(),9);
  await page.locator('#trip-collage').screenshot({path:'artifacts/trip-collage-nine.png'});
  const fallback=await page.evaluate(()=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,get=db.transaction('trips').objectStore('trips').getAll();get.onsuccess=()=>{db.close();resolve(get.result.find(t=>t.photos.length===9).memories[0].piece);};};}));
  assert.equal(fallback.kind,'paper','a failed single cutout keeps a torn photo fragment');
  await page.locator('#trip-new').click();
  await page.locator('#trip-photos').setInputFiles([{name:'a.png',mimeType:'image/png',buffer:red},{name:'b.png',mimeType:'image/png',buffer:blue}]);
  await page.locator('#trip-curate').click();await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('模拟生图失败'));
  assert.equal(await page.locator('#trip-piece-list button').count(),2);
  await page.evaluate(image=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,tx=db.transaction('trips','readwrite');tx.objectStore('trips').put({id:'legacy-trip',createdAt:2,name:'旧旅行',place:'',date:'',story:'',photos:[{id:'p1',image},{id:'p2',image}],coverId:'p1',memories:[{id:'old-point',photoId:'p1',title:'旧记忆',evidence:'可见',story:'旧故事',x:.5,y:.5}]});tx.oncomplete=()=>{db.close();resolve();};};}),image);
  await page.locator('#trip-refresh').click();await page.locator('.trip-library-card').filter({hasText:'旧旅行'}).locator('.trip-open').click();
  await page.waitForFunction(()=>document.getElementById('trip-name').value==='旧旅行');
  assert.equal(await page.locator('.trip-photo').count(),2);
  assert.equal(await page.locator('#trip-showcase-cabinet').isHidden(),true,'legacy trips do not show the previous trip cabinet');
  await page.locator('#trip-convert-legacy').click();await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('模拟生图失败'));
  assert.equal(await page.locator('.trip-point-editor').first().locator('.trip-point-story').inputValue(),'旧故事');
  await page.evaluate(({image,ringImage})=>new Promise(resolve=>{const request=indexedDB.open('shiguang-history',2);request.onsuccess=()=>{const db=request.result,tx=db.transaction('trips','readwrite'),piece={x:.5,y:.5,scale:1,rotation:0,baseSize:700};tx.objectStore('trips').put({id:'alpha-trip',createdAt:3,name:'透明测试',place:'',date:'',story:'',photos:[{id:'p1',image},{id:'p2',image}],coverId:'p1',collageVersion:1,memories:[{id:'under',photoId:'p1',title:'底层',story:'底层故事',evidence:'',piece:{...piece,z:0,cutout:image}},{id:'over',photoId:'p2',title:'上层',story:'上层故事',evidence:'',piece:{...piece,z:1,cutout:ringImage}}]});tx.oncomplete=()=>{db.close();resolve();};};}),{image,ringImage});
  await page.locator('#trip-refresh').click();await page.locator('.trip-library-card').filter({hasText:'透明测试'}).locator('.trip-open').click();
  await page.waitForFunction(()=>document.querySelectorAll('#trip-piece-list button').length===2);
  const overlap=page.locator('#trip-collage'),overlapBox=await overlap.boundingBox();
  await overlap.click({position:{x:overlapBox.width*.5,y:overlapBox.height*.5}});
  assert.equal(await page.locator('#trip-detail-title').textContent(),'底层','transparent pixels pass through to the lower piece');
  await page.locator('#trip-detail-close').click();
  await overlap.click({position:{x:overlapBox.width*.39,y:overlapBox.height*.5}});
  assert.equal(await page.locator('#trip-detail-title').textContent(),'上层','opaque overlap opens the top piece');
  await page.locator('#trip-detail-close').click();
  await page.evaluate(()=>{IDBObjectStore.prototype.put=function(){throw new DOMException('Full','QuotaExceededError');};});
  await page.locator('#trip-save').click();await page.waitForFunction(()=>document.getElementById('trip-status').textContent.includes('保存失败'));
  assert.equal(await page.locator('.trip-point-editor').first().locator('.trip-point-story').inputValue(),'底层故事');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('Trip collage browser flow passed: 2/9 photos, click, edit, persistence, linked reference, old trip, local cutout and save failure.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
