import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createApp} from '../server.js';
import {mkdir} from 'node:fs/promises';
let release;const gate=new Promise(r=>release=r);let calls=0;
const server=createApp({key:'test',fetchImpl:async()=>{calls++;if(calls===4)await gate;const data=calls===1?{intent:'plan',destination:'苏州',reply:'我会调整为苏州半日慢游。'}:calls===2?{summary:'仅整理演示资料'}:calls===3?{placeIds:['sz-museum','sz-pingjiang'],reason:'保留苏博，减少站点',constraints:{budget:'300元',hours:4,startTime:'13:00',easy:true},reply:'我将预算调整为300元，保留苏博并减少步行。'}:{placeIds:['sz-museum','sz-pingjiang'],title:'苏州半日慢游',reason:'就近安排两站'};return Response.json({choices:[{message:{content:JSON.stringify(data)}}]});}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const root=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('artifacts/workspace',{recursive:true});
try{const page=await browser.newPage({viewport:{width:1600,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root+'/travel.html');await page.waitForSelector('#canvas-world');await page.screenshot({path:'artifacts/workspace/guangzhou-initial.png',animations:'disabled'});await page.locator('.plan-options summary').click();await page.locator('#agent-mode').selectOption('ai');await page.locator('.plan-options summary').click();await page.locator('#travel-brief').fill('苏州下午4小时，每人全程预算300元，保留苏博，少走路');await page.getByRole('button',{name:'发送消息'}).click();await page.waitForFunction(()=>document.querySelector('#agent-trace .agent-step.working')?.textContent.includes('每日路线'));assert.match(await page.locator('#budget-value').textContent(),/300/);assert.ok(await page.locator('#budget-node.pending').count());
assert.match(await page.locator('#agent-trace').textContent(),/筛选|每日|重排/);assert.equal(await page.locator('#plan-button').isDisabled(),true);await page.screenshot({path:'artifacts/workspace/processing-desktop.png',animations:'disabled'});release();await page.waitForFunction(()=>!document.getElementById('plan-button').disabled);assert.equal(await page.locator('.chat-message.user').count(),1);assert.match(await page.locator('#chat-messages').textContent(),/300/);assert.equal(await page.locator('.stop-card').count(),2);
const initial=await page.locator('#canvas-world').evaluate(e=>e.style.transform);await page.getByRole('button',{name:'放大画布',exact:true}).click();assert.notEqual(await page.locator('#canvas-world').evaluate(e=>e.style.transform),initial);await page.getByRole('button',{name:'适应画布',exact:true}).click();const node=page.locator('#budget-node'),before=await node.boundingBox();await page.locator('#budget-node .node-header').dragTo(page.locator('#time-node .node-header'));assert.notEqual((await node.boundingBox()).x,before.x);await page.getByRole('button',{name:'重置布局',exact:true}).click();await page.screenshot({path:'artifacts/workspace/desktop.png',animations:'disabled'});
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'artifacts/workspace/mobile.png',fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);console.log('PASS: real stage updates before response, conversational answer, constraints, drag, zoom, reset, desktop and mobile.');}finally{release();await browser.close();await new Promise(r=>server.close(r));}
